// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: account_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountSyncService_SyncAccountBalances_FullMethodName = "/fintech.account_sync.v1.AccountSyncService/SyncAccountBalances"
)

// AccountSyncServiceClient is the client API for AccountSyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AccountSyncService - Real-time account balance synchronization
type AccountSyncServiceClient interface {
	// Bidirectional streaming for real-time account balance sync
	SyncAccountBalances(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BalanceCommand, BalanceUpdate], error)
}

type accountSyncServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountSyncServiceClient(cc grpc.ClientConnInterface) AccountSyncServiceClient {
	return &accountSyncServiceClient{cc}
}

func (c *accountSyncServiceClient) SyncAccountBalances(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[BalanceCommand, BalanceUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AccountSyncService_ServiceDesc.Streams[0], AccountSyncService_SyncAccountBalances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BalanceCommand, BalanceUpdate]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountSyncService_SyncAccountBalancesClient = grpc.BidiStreamingClient[BalanceCommand, BalanceUpdate]

// AccountSyncServiceServer is the server API for AccountSyncService service.
// All implementations must embed UnimplementedAccountSyncServiceServer
// for forward compatibility.
//
// AccountSyncService - Real-time account balance synchronization
type AccountSyncServiceServer interface {
	// Bidirectional streaming for real-time account balance sync
	SyncAccountBalances(grpc.BidiStreamingServer[BalanceCommand, BalanceUpdate]) error
	mustEmbedUnimplementedAccountSyncServiceServer()
}

// UnimplementedAccountSyncServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountSyncServiceServer struct{}

func (UnimplementedAccountSyncServiceServer) SyncAccountBalances(grpc.BidiStreamingServer[BalanceCommand, BalanceUpdate]) error {
	return status.Errorf(codes.Unimplemented, "method SyncAccountBalances not implemented")
}
func (UnimplementedAccountSyncServiceServer) mustEmbedUnimplementedAccountSyncServiceServer() {}
func (UnimplementedAccountSyncServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountSyncServiceServer will
// result in compilation errors.
type UnsafeAccountSyncServiceServer interface {
	mustEmbedUnimplementedAccountSyncServiceServer()
}

func RegisterAccountSyncServiceServer(s grpc.ServiceRegistrar, srv AccountSyncServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountSyncServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountSyncService_ServiceDesc, srv)
}

func _AccountSyncService_SyncAccountBalances_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AccountSyncServiceServer).SyncAccountBalances(&grpc.GenericServerStream[BalanceCommand, BalanceUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AccountSyncService_SyncAccountBalancesServer = grpc.BidiStreamingServer[BalanceCommand, BalanceUpdate]

// AccountSyncService_ServiceDesc is the grpc.ServiceDesc for AccountSyncService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountSyncService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fintech.account_sync.v1.AccountSyncService",
	HandlerType: (*AccountSyncServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncAccountBalances",
			Handler:       _AccountSyncService_SyncAccountBalances_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "account_sync.proto",
}
