// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/risk_monitoring.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskMonitoringService_MonitorRisk_FullMethodName = "/fintech.risk_monitoring.v1.RiskMonitoringService/MonitorRisk"
)

// RiskMonitoringServiceClient is the client API for RiskMonitoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RiskMonitoringService - Real-time risk assessment with dynamic rule updates
type RiskMonitoringServiceClient interface {
	// Bidirectional streaming for real-time risk monitoring
	MonitorRisk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RiskCommand, RiskEvent], error)
}

type riskMonitoringServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskMonitoringServiceClient(cc grpc.ClientConnInterface) RiskMonitoringServiceClient {
	return &riskMonitoringServiceClient{cc}
}

func (c *riskMonitoringServiceClient) MonitorRisk(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RiskCommand, RiskEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RiskMonitoringService_ServiceDesc.Streams[0], RiskMonitoringService_MonitorRisk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RiskCommand, RiskEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiskMonitoringService_MonitorRiskClient = grpc.BidiStreamingClient[RiskCommand, RiskEvent]

// RiskMonitoringServiceServer is the server API for RiskMonitoringService service.
// All implementations must embed UnimplementedRiskMonitoringServiceServer
// for forward compatibility.
//
// RiskMonitoringService - Real-time risk assessment with dynamic rule updates
type RiskMonitoringServiceServer interface {
	// Bidirectional streaming for real-time risk monitoring
	MonitorRisk(grpc.BidiStreamingServer[RiskCommand, RiskEvent]) error
	mustEmbedUnimplementedRiskMonitoringServiceServer()
}

// UnimplementedRiskMonitoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskMonitoringServiceServer struct{}

func (UnimplementedRiskMonitoringServiceServer) MonitorRisk(grpc.BidiStreamingServer[RiskCommand, RiskEvent]) error {
	return status.Errorf(codes.Unimplemented, "method MonitorRisk not implemented")
}
func (UnimplementedRiskMonitoringServiceServer) mustEmbedUnimplementedRiskMonitoringServiceServer() {}
func (UnimplementedRiskMonitoringServiceServer) testEmbeddedByValue()                               {}

// UnsafeRiskMonitoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskMonitoringServiceServer will
// result in compilation errors.
type UnsafeRiskMonitoringServiceServer interface {
	mustEmbedUnimplementedRiskMonitoringServiceServer()
}

func RegisterRiskMonitoringServiceServer(s grpc.ServiceRegistrar, srv RiskMonitoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedRiskMonitoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskMonitoringService_ServiceDesc, srv)
}

func _RiskMonitoringService_MonitorRisk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RiskMonitoringServiceServer).MonitorRisk(&grpc.GenericServerStream[RiskCommand, RiskEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RiskMonitoringService_MonitorRiskServer = grpc.BidiStreamingServer[RiskCommand, RiskEvent]

// RiskMonitoringService_ServiceDesc is the grpc.ServiceDesc for RiskMonitoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskMonitoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fintech.risk_monitoring.v1.RiskMonitoringService",
	HandlerType: (*RiskMonitoringServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MonitorRisk",
			Handler:       _RiskMonitoringService_MonitorRisk_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/risk_monitoring.proto",
}
