// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/transaction_validation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TransactionValidationService_ValidateTransaction_FullMethodName       = "/fintech.transaction_validation.v1.TransactionValidationService/ValidateTransaction"
	TransactionValidationService_BatchValidateTransactions_FullMethodName = "/fintech.transaction_validation.v1.TransactionValidationService/BatchValidateTransactions"
)

// TransactionValidationServiceClient is the client API for TransactionValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TransactionValidationService - Validate transactions before processing
type TransactionValidationServiceClient interface {
	// Validate a single transaction
	ValidateTransaction(ctx context.Context, in *ValidateTransactionRequest, opts ...grpc.CallOption) (*ValidateTransactionResponse, error)
	// Batch validate multiple transactions
	BatchValidateTransactions(ctx context.Context, in *BatchValidateRequest, opts ...grpc.CallOption) (*BatchValidateResponse, error)
}

type transactionValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionValidationServiceClient(cc grpc.ClientConnInterface) TransactionValidationServiceClient {
	return &transactionValidationServiceClient{cc}
}

func (c *transactionValidationServiceClient) ValidateTransaction(ctx context.Context, in *ValidateTransactionRequest, opts ...grpc.CallOption) (*ValidateTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTransactionResponse)
	err := c.cc.Invoke(ctx, TransactionValidationService_ValidateTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionValidationServiceClient) BatchValidateTransactions(ctx context.Context, in *BatchValidateRequest, opts ...grpc.CallOption) (*BatchValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchValidateResponse)
	err := c.cc.Invoke(ctx, TransactionValidationService_BatchValidateTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionValidationServiceServer is the server API for TransactionValidationService service.
// All implementations must embed UnimplementedTransactionValidationServiceServer
// for forward compatibility.
//
// TransactionValidationService - Validate transactions before processing
type TransactionValidationServiceServer interface {
	// Validate a single transaction
	ValidateTransaction(context.Context, *ValidateTransactionRequest) (*ValidateTransactionResponse, error)
	// Batch validate multiple transactions
	BatchValidateTransactions(context.Context, *BatchValidateRequest) (*BatchValidateResponse, error)
	mustEmbedUnimplementedTransactionValidationServiceServer()
}

// UnimplementedTransactionValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTransactionValidationServiceServer struct{}

func (UnimplementedTransactionValidationServiceServer) ValidateTransaction(context.Context, *ValidateTransactionRequest) (*ValidateTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateTransaction not implemented")
}
func (UnimplementedTransactionValidationServiceServer) BatchValidateTransactions(context.Context, *BatchValidateRequest) (*BatchValidateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchValidateTransactions not implemented")
}
func (UnimplementedTransactionValidationServiceServer) mustEmbedUnimplementedTransactionValidationServiceServer() {
}
func (UnimplementedTransactionValidationServiceServer) testEmbeddedByValue() {}

// UnsafeTransactionValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionValidationServiceServer will
// result in compilation errors.
type UnsafeTransactionValidationServiceServer interface {
	mustEmbedUnimplementedTransactionValidationServiceServer()
}

func RegisterTransactionValidationServiceServer(s grpc.ServiceRegistrar, srv TransactionValidationServiceServer) {
	// If the following call pancis, it indicates UnimplementedTransactionValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TransactionValidationService_ServiceDesc, srv)
}

func _TransactionValidationService_ValidateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionValidationServiceServer).ValidateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionValidationService_ValidateTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionValidationServiceServer).ValidateTransaction(ctx, req.(*ValidateTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionValidationService_BatchValidateTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionValidationServiceServer).BatchValidateTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TransactionValidationService_BatchValidateTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionValidationServiceServer).BatchValidateTransactions(ctx, req.(*BatchValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionValidationService_ServiceDesc is the grpc.ServiceDesc for TransactionValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fintech.transaction_validation.v1.TransactionValidationService",
	HandlerType: (*TransactionValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateTransaction",
			Handler:    _TransactionValidationService_ValidateTransaction_Handler,
		},
		{
			MethodName: "BatchValidateTransactions",
			Handler:    _TransactionValidationService_BatchValidateTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transaction_validation.proto",
}
