// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/account_sync.proto

package account_sync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account type enum
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_BANK        AccountType = 1
	AccountType_ACCOUNT_TYPE_CASH        AccountType = 2
	AccountType_ACCOUNT_TYPE_INVESTMENT  AccountType = 3
	AccountType_ACCOUNT_TYPE_CREDIT      AccountType = 4
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_BANK",
		2: "ACCOUNT_TYPE_CASH",
		3: "ACCOUNT_TYPE_INVESTMENT",
		4: "ACCOUNT_TYPE_CREDIT",
		5: "ACCOUNT_TYPE_SAVINGS",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_BANK":        1,
		"ACCOUNT_TYPE_CASH":        2,
		"ACCOUNT_TYPE_INVESTMENT":  3,
		"ACCOUNT_TYPE_CREDIT":      4,
		"ACCOUNT_TYPE_SAVINGS":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_sync_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_account_sync_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{0}
}

// Balance command message
type BalanceCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*BalanceCommand_Subscribe
	//	*BalanceCommand_Unsubscribe
	//	*BalanceCommand_Refresh
	//	*BalanceCommand_Update
	Command       isBalanceCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceCommand) Reset() {
	*x = BalanceCommand{}
	mi := &file_proto_account_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceCommand) ProtoMessage() {}

func (x *BalanceCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceCommand.ProtoReflect.Descriptor instead.
func (*BalanceCommand) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{0}
}

func (x *BalanceCommand) GetCommand() isBalanceCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *BalanceCommand) GetSubscribe() *SubscribeToAccount {
	if x != nil {
		if x, ok := x.Command.(*BalanceCommand_Subscribe); ok {
			return x.Subscribe
		}
	}
	return nil
}

func (x *BalanceCommand) GetUnsubscribe() *UnsubscribeFromAccount {
	if x != nil {
		if x, ok := x.Command.(*BalanceCommand_Unsubscribe); ok {
			return x.Unsubscribe
		}
	}
	return nil
}

func (x *BalanceCommand) GetRefresh() *RefreshBalance {
	if x != nil {
		if x, ok := x.Command.(*BalanceCommand_Refresh); ok {
			return x.Refresh
		}
	}
	return nil
}

func (x *BalanceCommand) GetUpdate() *UpdateBalance {
	if x != nil {
		if x, ok := x.Command.(*BalanceCommand_Update); ok {
			return x.Update
		}
	}
	return nil
}

type isBalanceCommand_Command interface {
	isBalanceCommand_Command()
}

type BalanceCommand_Subscribe struct {
	Subscribe *SubscribeToAccount `protobuf:"bytes,1,opt,name=subscribe,proto3,oneof"`
}

type BalanceCommand_Unsubscribe struct {
	Unsubscribe *UnsubscribeFromAccount `protobuf:"bytes,2,opt,name=unsubscribe,proto3,oneof"`
}

type BalanceCommand_Refresh struct {
	Refresh *RefreshBalance `protobuf:"bytes,3,opt,name=refresh,proto3,oneof"`
}

type BalanceCommand_Update struct {
	Update *UpdateBalance `protobuf:"bytes,4,opt,name=update,proto3,oneof"`
}

func (*BalanceCommand_Subscribe) isBalanceCommand_Command() {}

func (*BalanceCommand_Unsubscribe) isBalanceCommand_Command() {}

func (*BalanceCommand_Refresh) isBalanceCommand_Command() {}

func (*BalanceCommand_Update) isBalanceCommand_Command() {}

// Balance update message
type BalanceUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Update:
	//
	//	*BalanceUpdate_CurrentBalance
	//	*BalanceUpdate_BalanceChange
	//	*BalanceUpdate_BalanceError
	//	*BalanceUpdate_SyncStatus
	Update        isBalanceUpdate_Update `protobuf_oneof:"update"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceUpdate) Reset() {
	*x = BalanceUpdate{}
	mi := &file_proto_account_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceUpdate) ProtoMessage() {}

func (x *BalanceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceUpdate.ProtoReflect.Descriptor instead.
func (*BalanceUpdate) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{1}
}

func (x *BalanceUpdate) GetUpdate() isBalanceUpdate_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

func (x *BalanceUpdate) GetCurrentBalance() *CurrentBalance {
	if x != nil {
		if x, ok := x.Update.(*BalanceUpdate_CurrentBalance); ok {
			return x.CurrentBalance
		}
	}
	return nil
}

func (x *BalanceUpdate) GetBalanceChange() *BalanceChange {
	if x != nil {
		if x, ok := x.Update.(*BalanceUpdate_BalanceChange); ok {
			return x.BalanceChange
		}
	}
	return nil
}

func (x *BalanceUpdate) GetBalanceError() *BalanceError {
	if x != nil {
		if x, ok := x.Update.(*BalanceUpdate_BalanceError); ok {
			return x.BalanceError
		}
	}
	return nil
}

func (x *BalanceUpdate) GetSyncStatus() *SyncStatus {
	if x != nil {
		if x, ok := x.Update.(*BalanceUpdate_SyncStatus); ok {
			return x.SyncStatus
		}
	}
	return nil
}

type isBalanceUpdate_Update interface {
	isBalanceUpdate_Update()
}

type BalanceUpdate_CurrentBalance struct {
	CurrentBalance *CurrentBalance `protobuf:"bytes,1,opt,name=current_balance,json=currentBalance,proto3,oneof"`
}

type BalanceUpdate_BalanceChange struct {
	BalanceChange *BalanceChange `protobuf:"bytes,2,opt,name=balance_change,json=balanceChange,proto3,oneof"`
}

type BalanceUpdate_BalanceError struct {
	BalanceError *BalanceError `protobuf:"bytes,3,opt,name=balance_error,json=balanceError,proto3,oneof"`
}

type BalanceUpdate_SyncStatus struct {
	SyncStatus *SyncStatus `protobuf:"bytes,4,opt,name=sync_status,json=syncStatus,proto3,oneof"`
}

func (*BalanceUpdate_CurrentBalance) isBalanceUpdate_Update() {}

func (*BalanceUpdate_BalanceChange) isBalanceUpdate_Update() {}

func (*BalanceUpdate_BalanceError) isBalanceUpdate_Update() {}

func (*BalanceUpdate_SyncStatus) isBalanceUpdate_Update() {}

// Subscribe to account request
type SubscribeToAccount struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountIds      []string               `protobuf:"bytes,2,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	IncludePending  bool                   `protobuf:"varint,3,opt,name=include_pending,json=includePending,proto3" json:"include_pending,omitempty"`
	RealTimeUpdates bool                   `protobuf:"varint,4,opt,name=real_time_updates,json=realTimeUpdates,proto3" json:"real_time_updates,omitempty"`
	ThresholdAmount float64                `protobuf:"fixed64,5,opt,name=threshold_amount,json=thresholdAmount,proto3" json:"threshold_amount,omitempty"` // Only notify for changes above this amount
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeToAccount) Reset() {
	*x = SubscribeToAccount{}
	mi := &file_proto_account_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToAccount) ProtoMessage() {}

func (x *SubscribeToAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToAccount.ProtoReflect.Descriptor instead.
func (*SubscribeToAccount) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeToAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SubscribeToAccount) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *SubscribeToAccount) GetIncludePending() bool {
	if x != nil {
		return x.IncludePending
	}
	return false
}

func (x *SubscribeToAccount) GetRealTimeUpdates() bool {
	if x != nil {
		return x.RealTimeUpdates
	}
	return false
}

func (x *SubscribeToAccount) GetThresholdAmount() float64 {
	if x != nil {
		return x.ThresholdAmount
	}
	return 0
}

// Unsubscribe from account request
type UnsubscribeFromAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountIds    []string               `protobuf:"bytes,2,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnsubscribeFromAccount) Reset() {
	*x = UnsubscribeFromAccount{}
	mi := &file_proto_account_sync_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnsubscribeFromAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnsubscribeFromAccount) ProtoMessage() {}

func (x *UnsubscribeFromAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnsubscribeFromAccount.ProtoReflect.Descriptor instead.
func (*UnsubscribeFromAccount) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{3}
}

func (x *UnsubscribeFromAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnsubscribeFromAccount) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

// Refresh balance request
type RefreshBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ForceRefresh  bool                   `protobuf:"varint,2,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshBalance) Reset() {
	*x = RefreshBalance{}
	mi := &file_proto_account_sync_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshBalance) ProtoMessage() {}

func (x *RefreshBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshBalance.ProtoReflect.Descriptor instead.
func (*RefreshBalance) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshBalance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RefreshBalance) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

// Update balance request
type UpdateBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBalance) Reset() {
	*x = UpdateBalance{}
	mi := &file_proto_account_sync_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBalance) ProtoMessage() {}

func (x *UpdateBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBalance.ProtoReflect.Descriptor instead.
func (*UpdateBalance) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBalance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *UpdateBalance) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *UpdateBalance) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateBalance) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Current balance response
type CurrentBalance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   float64                `protobuf:"fixed64,4,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	TotalBalance     float64                `protobuf:"fixed64,5,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AccountType      AccountType            `protobuf:"varint,7,opt,name=account_type,json=accountType,proto3,enum=fintech.account_sync.v1.AccountType" json:"account_type,omitempty"`
	LastUpdated      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	AccountName      string                 `protobuf:"bytes,9,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CurrentBalance) Reset() {
	*x = CurrentBalance{}
	mi := &file_proto_account_sync_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrentBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentBalance) ProtoMessage() {}

func (x *CurrentBalance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentBalance.ProtoReflect.Descriptor instead.
func (*CurrentBalance) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{6}
}

func (x *CurrentBalance) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *CurrentBalance) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CurrentBalance) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *CurrentBalance) GetPendingBalance() float64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *CurrentBalance) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *CurrentBalance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CurrentBalance) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *CurrentBalance) GetLastUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdated
	}
	return nil
}

func (x *CurrentBalance) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

// Balance change response
type BalanceChange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	PreviousBalance float64                `protobuf:"fixed64,2,opt,name=previous_balance,json=previousBalance,proto3" json:"previous_balance,omitempty"`
	NewBalance      float64                `protobuf:"fixed64,3,opt,name=new_balance,json=newBalance,proto3" json:"new_balance,omitempty"`
	ChangeAmount    float64                `protobuf:"fixed64,4,opt,name=change_amount,json=changeAmount,proto3" json:"change_amount,omitempty"`
	TransactionId   string                 `protobuf:"bytes,5,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ChangeType      string                 `protobuf:"bytes,6,opt,name=change_type,json=changeType,proto3" json:"change_type,omitempty"` // "debit", "credit", "transfer"
	Description     string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ChangedAt       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=changed_at,json=changedAt,proto3" json:"changed_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BalanceChange) Reset() {
	*x = BalanceChange{}
	mi := &file_proto_account_sync_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceChange) ProtoMessage() {}

func (x *BalanceChange) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceChange.ProtoReflect.Descriptor instead.
func (*BalanceChange) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{7}
}

func (x *BalanceChange) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceChange) GetPreviousBalance() float64 {
	if x != nil {
		return x.PreviousBalance
	}
	return 0
}

func (x *BalanceChange) GetNewBalance() float64 {
	if x != nil {
		return x.NewBalance
	}
	return 0
}

func (x *BalanceChange) GetChangeAmount() float64 {
	if x != nil {
		return x.ChangeAmount
	}
	return 0
}

func (x *BalanceChange) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *BalanceChange) GetChangeType() string {
	if x != nil {
		return x.ChangeType
	}
	return ""
}

func (x *BalanceChange) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BalanceChange) GetChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ChangedAt
	}
	return nil
}

// Balance error response
type BalanceError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	IsRetryable   bool                   `protobuf:"varint,4,opt,name=is_retryable,json=isRetryable,proto3" json:"is_retryable,omitempty"`
	ErrorAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=error_at,json=errorAt,proto3" json:"error_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BalanceError) Reset() {
	*x = BalanceError{}
	mi := &file_proto_account_sync_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceError) ProtoMessage() {}

func (x *BalanceError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceError.ProtoReflect.Descriptor instead.
func (*BalanceError) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{8}
}

func (x *BalanceError) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *BalanceError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *BalanceError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *BalanceError) GetIsRetryable() bool {
	if x != nil {
		return x.IsRetryable
	}
	return false
}

func (x *BalanceError) GetErrorAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ErrorAt
	}
	return nil
}

// Sync status response
type SyncStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsSyncing          bool                   `protobuf:"varint,1,opt,name=is_syncing,json=isSyncing,proto3" json:"is_syncing,omitempty"`
	SessionId          string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SubscribedAccounts int32                  `protobuf:"varint,3,opt,name=subscribed_accounts,json=subscribedAccounts,proto3" json:"subscribed_accounts,omitempty"`
	ActiveConnections  int32                  `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	StartedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	AccountStatuses    map[string]string      `protobuf:"bytes,6,rep,name=account_statuses,json=accountStatuses,proto3" json:"account_statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Message            string                 `protobuf:"bytes,7,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_proto_account_sync_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_sync_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_proto_account_sync_proto_rawDescGZIP(), []int{9}
}

func (x *SyncStatus) GetIsSyncing() bool {
	if x != nil {
		return x.IsSyncing
	}
	return false
}

func (x *SyncStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SyncStatus) GetSubscribedAccounts() int32 {
	if x != nil {
		return x.SubscribedAccounts
	}
	return 0
}

func (x *SyncStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *SyncStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SyncStatus) GetAccountStatuses() map[string]string {
	if x != nil {
		return x.AccountStatuses
	}
	return nil
}

func (x *SyncStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_account_sync_proto protoreflect.FileDescriptor

const file_proto_account_sync_proto_rawDesc = "" +
	"\n" +
	"\x18proto/account_sync.proto\x12\x17fintech.account_sync.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x02\n" +
	"\x0eBalanceCommand\x12K\n" +
	"\tsubscribe\x18\x01 \x01(\v2+.fintech.account_sync.v1.SubscribeToAccountH\x00R\tsubscribe\x12S\n" +
	"\vunsubscribe\x18\x02 \x01(\v2/.fintech.account_sync.v1.UnsubscribeFromAccountH\x00R\vunsubscribe\x12C\n" +
	"\arefresh\x18\x03 \x01(\v2'.fintech.account_sync.v1.RefreshBalanceH\x00R\arefresh\x12@\n" +
	"\x06update\x18\x04 \x01(\v2&.fintech.account_sync.v1.UpdateBalanceH\x00R\x06updateB\t\n" +
	"\acommand\"\xd4\x02\n" +
	"\rBalanceUpdate\x12R\n" +
	"\x0fcurrent_balance\x18\x01 \x01(\v2'.fintech.account_sync.v1.CurrentBalanceH\x00R\x0ecurrentBalance\x12O\n" +
	"\x0ebalance_change\x18\x02 \x01(\v2&.fintech.account_sync.v1.BalanceChangeH\x00R\rbalanceChange\x12L\n" +
	"\rbalance_error\x18\x03 \x01(\v2%.fintech.account_sync.v1.BalanceErrorH\x00R\fbalanceError\x12F\n" +
	"\vsync_status\x18\x04 \x01(\v2#.fintech.account_sync.v1.SyncStatusH\x00R\n" +
	"syncStatusB\b\n" +
	"\x06update\"\xce\x01\n" +
	"\x12SubscribeToAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaccount_ids\x18\x02 \x03(\tR\n" +
	"accountIds\x12'\n" +
	"\x0finclude_pending\x18\x03 \x01(\bR\x0eincludePending\x12*\n" +
	"\x11real_time_updates\x18\x04 \x01(\bR\x0frealTimeUpdates\x12)\n" +
	"\x10threshold_amount\x18\x05 \x01(\x01R\x0fthresholdAmount\"R\n" +
	"\x16UnsubscribeFromAccount\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaccount_ids\x18\x02 \x03(\tR\n" +
	"accountIds\"T\n" +
	"\x0eRefreshBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12#\n" +
	"\rforce_refresh\x18\x02 \x01(\bR\fforceRefresh\"\x8f\x01\n" +
	"\rUpdateBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"\x8a\x03\n" +
	"\x0eCurrentBalance\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\x01R\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x04 \x01(\x01R\x0ependingBalance\x12#\n" +
	"\rtotal_balance\x18\x05 \x01(\x01R\ftotalBalance\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12G\n" +
	"\faccount_type\x18\a \x01(\x0e2$.fintech.account_sync.v1.AccountTypeR\vaccountType\x12=\n" +
	"\flast_updated\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vlastUpdated\x12!\n" +
	"\faccount_name\x18\t \x01(\tR\vaccountName\"\xc4\x02\n" +
	"\rBalanceChange\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12)\n" +
	"\x10previous_balance\x18\x02 \x01(\x01R\x0fpreviousBalance\x12\x1f\n" +
	"\vnew_balance\x18\x03 \x01(\x01R\n" +
	"newBalance\x12#\n" +
	"\rchange_amount\x18\x04 \x01(\x01R\fchangeAmount\x12%\n" +
	"\x0etransaction_id\x18\x05 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vchange_type\x18\x06 \x01(\tR\n" +
	"changeType\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x129\n" +
	"\n" +
	"changed_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tchangedAt\"\xcb\x01\n" +
	"\fBalanceError\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12!\n" +
	"\fis_retryable\x18\x04 \x01(\bR\visRetryable\x125\n" +
	"\berror_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\aerrorAt\"\xa8\x03\n" +
	"\n" +
	"SyncStatus\x12\x1d\n" +
	"\n" +
	"is_syncing\x18\x01 \x01(\bR\tisSyncing\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12/\n" +
	"\x13subscribed_accounts\x18\x03 \x01(\x05R\x12subscribedAccounts\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\x05R\x11activeConnections\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12c\n" +
	"\x10account_statuses\x18\x06 \x03(\v28.fintech.account_sync.v1.SyncStatus.AccountStatusesEntryR\x0faccountStatuses\x12\x18\n" +
	"\amessage\x18\a \x01(\tR\amessage\x1aB\n" +
	"\x14AccountStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xa9\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_BANK\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_TYPE_CASH\x10\x02\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_CREDIT\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x052\x80\x01\n" +
	"\x12AccountSyncService\x12j\n" +
	"\x13SyncAccountBalances\x12'.fintech.account_sync.v1.BalanceCommand\x1a&.fintech.account_sync.v1.BalanceUpdate(\x010\x01B5Z3fintech-api/proto/gen/account_sync;account_syncb\x06proto3"

var (
	file_proto_account_sync_proto_rawDescOnce sync.Once
	file_proto_account_sync_proto_rawDescData []byte
)

func file_proto_account_sync_proto_rawDescGZIP() []byte {
	file_proto_account_sync_proto_rawDescOnce.Do(func() {
		file_proto_account_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_sync_proto_rawDesc), len(file_proto_account_sync_proto_rawDesc)))
	})
	return file_proto_account_sync_proto_rawDescData
}

var file_proto_account_sync_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_account_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_account_sync_proto_goTypes = []any{
	(AccountType)(0),               // 0: fintech.account_sync.v1.AccountType
	(*BalanceCommand)(nil),         // 1: fintech.account_sync.v1.BalanceCommand
	(*BalanceUpdate)(nil),          // 2: fintech.account_sync.v1.BalanceUpdate
	(*SubscribeToAccount)(nil),     // 3: fintech.account_sync.v1.SubscribeToAccount
	(*UnsubscribeFromAccount)(nil), // 4: fintech.account_sync.v1.UnsubscribeFromAccount
	(*RefreshBalance)(nil),         // 5: fintech.account_sync.v1.RefreshBalance
	(*UpdateBalance)(nil),          // 6: fintech.account_sync.v1.UpdateBalance
	(*CurrentBalance)(nil),         // 7: fintech.account_sync.v1.CurrentBalance
	(*BalanceChange)(nil),          // 8: fintech.account_sync.v1.BalanceChange
	(*BalanceError)(nil),           // 9: fintech.account_sync.v1.BalanceError
	(*SyncStatus)(nil),             // 10: fintech.account_sync.v1.SyncStatus
	nil,                            // 11: fintech.account_sync.v1.SyncStatus.AccountStatusesEntry
	(*timestamppb.Timestamp)(nil),  // 12: google.protobuf.Timestamp
}
var file_proto_account_sync_proto_depIdxs = []int32{
	3,  // 0: fintech.account_sync.v1.BalanceCommand.subscribe:type_name -> fintech.account_sync.v1.SubscribeToAccount
	4,  // 1: fintech.account_sync.v1.BalanceCommand.unsubscribe:type_name -> fintech.account_sync.v1.UnsubscribeFromAccount
	5,  // 2: fintech.account_sync.v1.BalanceCommand.refresh:type_name -> fintech.account_sync.v1.RefreshBalance
	6,  // 3: fintech.account_sync.v1.BalanceCommand.update:type_name -> fintech.account_sync.v1.UpdateBalance
	7,  // 4: fintech.account_sync.v1.BalanceUpdate.current_balance:type_name -> fintech.account_sync.v1.CurrentBalance
	8,  // 5: fintech.account_sync.v1.BalanceUpdate.balance_change:type_name -> fintech.account_sync.v1.BalanceChange
	9,  // 6: fintech.account_sync.v1.BalanceUpdate.balance_error:type_name -> fintech.account_sync.v1.BalanceError
	10, // 7: fintech.account_sync.v1.BalanceUpdate.sync_status:type_name -> fintech.account_sync.v1.SyncStatus
	0,  // 8: fintech.account_sync.v1.CurrentBalance.account_type:type_name -> fintech.account_sync.v1.AccountType
	12, // 9: fintech.account_sync.v1.CurrentBalance.last_updated:type_name -> google.protobuf.Timestamp
	12, // 10: fintech.account_sync.v1.BalanceChange.changed_at:type_name -> google.protobuf.Timestamp
	12, // 11: fintech.account_sync.v1.BalanceError.error_at:type_name -> google.protobuf.Timestamp
	12, // 12: fintech.account_sync.v1.SyncStatus.started_at:type_name -> google.protobuf.Timestamp
	11, // 13: fintech.account_sync.v1.SyncStatus.account_statuses:type_name -> fintech.account_sync.v1.SyncStatus.AccountStatusesEntry
	1,  // 14: fintech.account_sync.v1.AccountSyncService.SyncAccountBalances:input_type -> fintech.account_sync.v1.BalanceCommand
	2,  // 15: fintech.account_sync.v1.AccountSyncService.SyncAccountBalances:output_type -> fintech.account_sync.v1.BalanceUpdate
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_account_sync_proto_init() }
func file_proto_account_sync_proto_init() {
	if File_proto_account_sync_proto != nil {
		return
	}
	file_proto_account_sync_proto_msgTypes[0].OneofWrappers = []any{
		(*BalanceCommand_Subscribe)(nil),
		(*BalanceCommand_Unsubscribe)(nil),
		(*BalanceCommand_Refresh)(nil),
		(*BalanceCommand_Update)(nil),
	}
	file_proto_account_sync_proto_msgTypes[1].OneofWrappers = []any{
		(*BalanceUpdate_CurrentBalance)(nil),
		(*BalanceUpdate_BalanceChange)(nil),
		(*BalanceUpdate_BalanceError)(nil),
		(*BalanceUpdate_SyncStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_sync_proto_rawDesc), len(file_proto_account_sync_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_account_sync_proto_goTypes,
		DependencyIndexes: file_proto_account_sync_proto_depIdxs,
		EnumInfos:         file_proto_account_sync_proto_enumTypes,
		MessageInfos:      file_proto_account_sync_proto_msgTypes,
	}.Build()
	File_proto_account_sync_proto = out.File
	file_proto_account_sync_proto_goTypes = nil
	file_proto_account_sync_proto_depIdxs = nil
}
