// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/account_info.proto

package account_info

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account type enum
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_BANK        AccountType = 1
	AccountType_ACCOUNT_TYPE_CASH        AccountType = 2
	AccountType_ACCOUNT_TYPE_INVESTMENT  AccountType = 3
	AccountType_ACCOUNT_TYPE_CREDIT      AccountType = 4
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 5
	AccountType_ACCOUNT_TYPE_ASSET       AccountType = 6
	AccountType_ACCOUNT_TYPE_LIABILITY   AccountType = 7
	AccountType_ACCOUNT_TYPE_EQUITY      AccountType = 8
	AccountType_ACCOUNT_TYPE_REVENUE     AccountType = 9
	AccountType_ACCOUNT_TYPE_EXPENSE     AccountType = 10
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0:  "ACCOUNT_TYPE_UNSPECIFIED",
		1:  "ACCOUNT_TYPE_BANK",
		2:  "ACCOUNT_TYPE_CASH",
		3:  "ACCOUNT_TYPE_INVESTMENT",
		4:  "ACCOUNT_TYPE_CREDIT",
		5:  "ACCOUNT_TYPE_SAVINGS",
		6:  "ACCOUNT_TYPE_ASSET",
		7:  "ACCOUNT_TYPE_LIABILITY",
		8:  "ACCOUNT_TYPE_EQUITY",
		9:  "ACCOUNT_TYPE_REVENUE",
		10: "ACCOUNT_TYPE_EXPENSE",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_BANK":        1,
		"ACCOUNT_TYPE_CASH":        2,
		"ACCOUNT_TYPE_INVESTMENT":  3,
		"ACCOUNT_TYPE_CREDIT":      4,
		"ACCOUNT_TYPE_SAVINGS":     5,
		"ACCOUNT_TYPE_ASSET":       6,
		"ACCOUNT_TYPE_LIABILITY":   7,
		"ACCOUNT_TYPE_EQUITY":      8,
		"ACCOUNT_TYPE_REVENUE":     9,
		"ACCOUNT_TYPE_EXPENSE":     10,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_info_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_account_info_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{0}
}

// Account status enum
type AccountStatus int32

const (
	AccountStatus_ACCOUNT_STATUS_UNSPECIFIED AccountStatus = 0
	AccountStatus_ACCOUNT_STATUS_ACTIVE      AccountStatus = 1
	AccountStatus_ACCOUNT_STATUS_INACTIVE    AccountStatus = 2
	AccountStatus_ACCOUNT_STATUS_SUSPENDED   AccountStatus = 3
	AccountStatus_ACCOUNT_STATUS_CLOSED      AccountStatus = 4
)

// Enum value maps for AccountStatus.
var (
	AccountStatus_name = map[int32]string{
		0: "ACCOUNT_STATUS_UNSPECIFIED",
		1: "ACCOUNT_STATUS_ACTIVE",
		2: "ACCOUNT_STATUS_INACTIVE",
		3: "ACCOUNT_STATUS_SUSPENDED",
		4: "ACCOUNT_STATUS_CLOSED",
	}
	AccountStatus_value = map[string]int32{
		"ACCOUNT_STATUS_UNSPECIFIED": 0,
		"ACCOUNT_STATUS_ACTIVE":      1,
		"ACCOUNT_STATUS_INACTIVE":    2,
		"ACCOUNT_STATUS_SUSPENDED":   3,
		"ACCOUNT_STATUS_CLOSED":      4,
	}
)

func (x AccountStatus) Enum() *AccountStatus {
	p := new(AccountStatus)
	*p = x
	return p
}

func (x AccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_info_proto_enumTypes[1].Descriptor()
}

func (AccountStatus) Type() protoreflect.EnumType {
	return &file_proto_account_info_proto_enumTypes[1]
}

func (x AccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountStatus.Descriptor instead.
func (AccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{1}
}

// Transaction type enum
type TransactionType int32

const (
	TransactionType_TRANSACTION_TYPE_UNSPECIFIED TransactionType = 0
	TransactionType_TRANSACTION_TYPE_TRANSFER    TransactionType = 1
	TransactionType_TRANSACTION_TYPE_DEPOSIT     TransactionType = 2
	TransactionType_TRANSACTION_TYPE_WITHDRAWAL  TransactionType = 3
	TransactionType_TRANSACTION_TYPE_PAYMENT     TransactionType = 4
	TransactionType_TRANSACTION_TYPE_REFUND      TransactionType = 5
	TransactionType_TRANSACTION_TYPE_FEE         TransactionType = 6
	TransactionType_TRANSACTION_TYPE_ADJUSTMENT  TransactionType = 7
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "TRANSACTION_TYPE_UNSPECIFIED",
		1: "TRANSACTION_TYPE_TRANSFER",
		2: "TRANSACTION_TYPE_DEPOSIT",
		3: "TRANSACTION_TYPE_WITHDRAWAL",
		4: "TRANSACTION_TYPE_PAYMENT",
		5: "TRANSACTION_TYPE_REFUND",
		6: "TRANSACTION_TYPE_FEE",
		7: "TRANSACTION_TYPE_ADJUSTMENT",
	}
	TransactionType_value = map[string]int32{
		"TRANSACTION_TYPE_UNSPECIFIED": 0,
		"TRANSACTION_TYPE_TRANSFER":    1,
		"TRANSACTION_TYPE_DEPOSIT":     2,
		"TRANSACTION_TYPE_WITHDRAWAL":  3,
		"TRANSACTION_TYPE_PAYMENT":     4,
		"TRANSACTION_TYPE_REFUND":      5,
		"TRANSACTION_TYPE_FEE":         6,
		"TRANSACTION_TYPE_ADJUSTMENT":  7,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_account_info_proto_enumTypes[2].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_account_info_proto_enumTypes[2]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{2}
}

// Get account info request
type GetAccountInfoRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AccountId                 string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IncludeBalance            bool                   `protobuf:"varint,2,opt,name=include_balance,json=includeBalance,proto3" json:"include_balance,omitempty"`
	IncludeRecentTransactions bool                   `protobuf:"varint,3,opt,name=include_recent_transactions,json=includeRecentTransactions,proto3" json:"include_recent_transactions,omitempty"`
	RecentTransactionLimit    int32                  `protobuf:"varint,4,opt,name=recent_transaction_limit,json=recentTransactionLimit,proto3" json:"recent_transaction_limit,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetAccountInfoRequest) Reset() {
	*x = GetAccountInfoRequest{}
	mi := &file_proto_account_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoRequest) ProtoMessage() {}

func (x *GetAccountInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoRequest.ProtoReflect.Descriptor instead.
func (*GetAccountInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{0}
}

func (x *GetAccountInfoRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *GetAccountInfoRequest) GetIncludeBalance() bool {
	if x != nil {
		return x.IncludeBalance
	}
	return false
}

func (x *GetAccountInfoRequest) GetIncludeRecentTransactions() bool {
	if x != nil {
		return x.IncludeRecentTransactions
	}
	return false
}

func (x *GetAccountInfoRequest) GetRecentTransactionLimit() int32 {
	if x != nil {
		return x.RecentTransactionLimit
	}
	return 0
}

// Get account info response
type GetAccountInfoResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Account            *LedgerAccount         `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	CurrentBalance     float64                `protobuf:"fixed64,2,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	RecentTransactions []*Transaction         `protobuf:"bytes,3,rep,name=recent_transactions,json=recentTransactions,proto3" json:"recent_transactions,omitempty"`
	Metrics            *AccountMetrics        `protobuf:"bytes,4,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAccountInfoResponse) Reset() {
	*x = GetAccountInfoResponse{}
	mi := &file_proto_account_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoResponse) ProtoMessage() {}

func (x *GetAccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{1}
}

func (x *GetAccountInfoResponse) GetAccount() *LedgerAccount {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *GetAccountInfoResponse) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *GetAccountInfoResponse) GetRecentTransactions() []*Transaction {
	if x != nil {
		return x.RecentTransactions
	}
	return nil
}

func (x *GetAccountInfoResponse) GetMetrics() *AccountMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Get account summary request
type GetAccountSummaryRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	UserId             string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountIds         []string               `protobuf:"bytes,2,rep,name=account_ids,json=accountIds,proto3" json:"account_ids,omitempty"`
	IncludeSubAccounts bool                   `protobuf:"varint,3,opt,name=include_sub_accounts,json=includeSubAccounts,proto3" json:"include_sub_accounts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAccountSummaryRequest) Reset() {
	*x = GetAccountSummaryRequest{}
	mi := &file_proto_account_info_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryRequest) ProtoMessage() {}

func (x *GetAccountSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAccountSummaryRequest) GetAccountIds() []string {
	if x != nil {
		return x.AccountIds
	}
	return nil
}

func (x *GetAccountSummaryRequest) GetIncludeSubAccounts() bool {
	if x != nil {
		return x.IncludeSubAccounts
	}
	return false
}

// Get account summary response
type GetAccountSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []*AccountSummary      `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	TotalBalance  float64                `protobuf:"fixed64,2,opt,name=total_balance,json=totalBalance,proto3" json:"total_balance,omitempty"`
	BaseCurrency  string                 `protobuf:"bytes,3,opt,name=base_currency,json=baseCurrency,proto3" json:"base_currency,omitempty"`
	TotalAccounts int32                  `protobuf:"varint,4,opt,name=total_accounts,json=totalAccounts,proto3" json:"total_accounts,omitempty"`
	SummaryAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=summary_at,json=summaryAt,proto3" json:"summary_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountSummaryResponse) Reset() {
	*x = GetAccountSummaryResponse{}
	mi := &file_proto_account_info_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountSummaryResponse) ProtoMessage() {}

func (x *GetAccountSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAccountSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountSummaryResponse) GetAccounts() []*AccountSummary {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *GetAccountSummaryResponse) GetTotalBalance() float64 {
	if x != nil {
		return x.TotalBalance
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetBaseCurrency() string {
	if x != nil {
		return x.BaseCurrency
	}
	return ""
}

func (x *GetAccountSummaryResponse) GetTotalAccounts() int32 {
	if x != nil {
		return x.TotalAccounts
	}
	return 0
}

func (x *GetAccountSummaryResponse) GetSummaryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SummaryAt
	}
	return nil
}

// Transaction history request
type TransactionHistoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	FromDate         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=from_date,json=fromDate,proto3" json:"from_date,omitempty"`
	ToDate           *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=to_date,json=toDate,proto3" json:"to_date,omitempty"`
	Limit            int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset           int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	TransactionTypes []TransactionType      `protobuf:"varint,6,rep,packed,name=transaction_types,json=transactionTypes,proto3,enum=fintech.account_info.v1.TransactionType" json:"transaction_types,omitempty"`
	MinAmount        float64                `protobuf:"fixed64,7,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount        float64                `protobuf:"fixed64,8,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	IncludePending   bool                   `protobuf:"varint,9,opt,name=include_pending,json=includePending,proto3" json:"include_pending,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionHistoryRequest) Reset() {
	*x = TransactionHistoryRequest{}
	mi := &file_proto_account_info_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHistoryRequest) ProtoMessage() {}

func (x *TransactionHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHistoryRequest.ProtoReflect.Descriptor instead.
func (*TransactionHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionHistoryRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *TransactionHistoryRequest) GetFromDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FromDate
	}
	return nil
}

func (x *TransactionHistoryRequest) GetToDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ToDate
	}
	return nil
}

func (x *TransactionHistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TransactionHistoryRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *TransactionHistoryRequest) GetTransactionTypes() []TransactionType {
	if x != nil {
		return x.TransactionTypes
	}
	return nil
}

func (x *TransactionHistoryRequest) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *TransactionHistoryRequest) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *TransactionHistoryRequest) GetIncludePending() bool {
	if x != nil {
		return x.IncludePending
	}
	return false
}

// Transaction history response
type TransactionHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	IsLast        bool                   `protobuf:"varint,2,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	CurrentIndex  int32                  `protobuf:"varint,4,opt,name=current_index,json=currentIndex,proto3" json:"current_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHistoryResponse) Reset() {
	*x = TransactionHistoryResponse{}
	mi := &file_proto_account_info_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHistoryResponse) ProtoMessage() {}

func (x *TransactionHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHistoryResponse.ProtoReflect.Descriptor instead.
func (*TransactionHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionHistoryResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *TransactionHistoryResponse) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *TransactionHistoryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *TransactionHistoryResponse) GetCurrentIndex() int32 {
	if x != nil {
		return x.CurrentIndex
	}
	return 0
}

// Ledger account details
type LedgerAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountNumber string                 `protobuf:"bytes,3,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Type          AccountType            `protobuf:"varint,6,opt,name=type,proto3,enum=fintech.account_info.v1.AccountType" json:"type,omitempty"`
	Status        AccountStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=fintech.account_info.v1.AccountStatus" json:"status,omitempty"`
	Currency      string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	ParentId      string                 `protobuf:"bytes,9,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	IsSystem      bool                   `protobuf:"varint,10,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerAccount) Reset() {
	*x = LedgerAccount{}
	mi := &file_proto_account_info_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerAccount) ProtoMessage() {}

func (x *LedgerAccount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerAccount.ProtoReflect.Descriptor instead.
func (*LedgerAccount) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{6}
}

func (x *LedgerAccount) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LedgerAccount) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *LedgerAccount) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *LedgerAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LedgerAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerAccount) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *LedgerAccount) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *LedgerAccount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LedgerAccount) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *LedgerAccount) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *LedgerAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LedgerAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Transaction details
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          TransactionType        `protobuf:"varint,3,opt,name=type,proto3,enum=fintech.account_info.v1.TransactionType" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Reference     string                 `protobuf:"bytes,5,opt,name=reference,proto3" json:"reference,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,6,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Entries       []*LedgerEntry         `protobuf:"bytes,10,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_account_info_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{7}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_TRANSACTION_TYPE_UNSPECIFIED
}

func (x *Transaction) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Transaction) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *Transaction) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Transaction) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Ledger entry details
type LedgerEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EntryId         string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	TransactionId   string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	DebitAccountId  string                 `protobuf:"bytes,3,opt,name=debit_account_id,json=debitAccountId,proto3" json:"debit_account_id,omitempty"`
	CreditAccountId string                 `protobuf:"bytes,4,opt,name=credit_account_id,json=creditAccountId,proto3" json:"credit_account_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	EntryType       string                 `protobuf:"bytes,7,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Reference       string                 `protobuf:"bytes,9,opt,name=reference,proto3" json:"reference,omitempty"`
	Timestamp       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_proto_account_info_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{8}
}

func (x *LedgerEntry) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *LedgerEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LedgerEntry) GetDebitAccountId() string {
	if x != nil {
		return x.DebitAccountId
	}
	return ""
}

func (x *LedgerEntry) GetCreditAccountId() string {
	if x != nil {
		return x.CreditAccountId
	}
	return ""
}

func (x *LedgerEntry) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LedgerEntry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *LedgerEntry) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *LedgerEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LedgerEntry) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *LedgerEntry) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// Account summary
type AccountSummary struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccountId        string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName      string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	AccountType      AccountType            `protobuf:"varint,3,opt,name=account_type,json=accountType,proto3,enum=fintech.account_info.v1.AccountType" json:"account_type,omitempty"`
	CurrentBalance   float64                `protobuf:"fixed64,4,opt,name=current_balance,json=currentBalance,proto3" json:"current_balance,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,5,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	PendingBalance   float64                `protobuf:"fixed64,6,opt,name=pending_balance,json=pendingBalance,proto3" json:"pending_balance,omitempty"`
	Currency         string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           AccountStatus          `protobuf:"varint,8,opt,name=status,proto3,enum=fintech.account_info.v1.AccountStatus" json:"status,omitempty"`
	LastActivity     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_activity,json=lastActivity,proto3" json:"last_activity,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AccountSummary) Reset() {
	*x = AccountSummary{}
	mi := &file_proto_account_info_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSummary) ProtoMessage() {}

func (x *AccountSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSummary.ProtoReflect.Descriptor instead.
func (*AccountSummary) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{9}
}

func (x *AccountSummary) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *AccountSummary) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *AccountSummary) GetAccountType() AccountType {
	if x != nil {
		return x.AccountType
	}
	return AccountType_ACCOUNT_TYPE_UNSPECIFIED
}

func (x *AccountSummary) GetCurrentBalance() float64 {
	if x != nil {
		return x.CurrentBalance
	}
	return 0
}

func (x *AccountSummary) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *AccountSummary) GetPendingBalance() float64 {
	if x != nil {
		return x.PendingBalance
	}
	return 0
}

func (x *AccountSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AccountSummary) GetStatus() AccountStatus {
	if x != nil {
		return x.Status
	}
	return AccountStatus_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *AccountSummary) GetLastActivity() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivity
	}
	return nil
}

// Account metrics
type AccountMetrics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalTransactions     int32                  `protobuf:"varint,1,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	TotalDebits           float64                `protobuf:"fixed64,2,opt,name=total_debits,json=totalDebits,proto3" json:"total_debits,omitempty"`
	TotalCredits          float64                `protobuf:"fixed64,3,opt,name=total_credits,json=totalCredits,proto3" json:"total_credits,omitempty"`
	AvgTransactionAmount  float64                `protobuf:"fixed64,4,opt,name=avg_transaction_amount,json=avgTransactionAmount,proto3" json:"avg_transaction_amount,omitempty"`
	FirstTransaction      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=first_transaction,json=firstTransaction,proto3" json:"first_transaction,omitempty"`
	LastTransaction       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_transaction,json=lastTransaction,proto3" json:"last_transaction,omitempty"`
	TransactionTypeCounts map[string]int32       `protobuf:"bytes,7,rep,name=transaction_type_counts,json=transactionTypeCounts,proto3" json:"transaction_type_counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *AccountMetrics) Reset() {
	*x = AccountMetrics{}
	mi := &file_proto_account_info_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountMetrics) ProtoMessage() {}

func (x *AccountMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_info_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountMetrics.ProtoReflect.Descriptor instead.
func (*AccountMetrics) Descriptor() ([]byte, []int) {
	return file_proto_account_info_proto_rawDescGZIP(), []int{10}
}

func (x *AccountMetrics) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *AccountMetrics) GetTotalDebits() float64 {
	if x != nil {
		return x.TotalDebits
	}
	return 0
}

func (x *AccountMetrics) GetTotalCredits() float64 {
	if x != nil {
		return x.TotalCredits
	}
	return 0
}

func (x *AccountMetrics) GetAvgTransactionAmount() float64 {
	if x != nil {
		return x.AvgTransactionAmount
	}
	return 0
}

func (x *AccountMetrics) GetFirstTransaction() *timestamppb.Timestamp {
	if x != nil {
		return x.FirstTransaction
	}
	return nil
}

func (x *AccountMetrics) GetLastTransaction() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransaction
	}
	return nil
}

func (x *AccountMetrics) GetTransactionTypeCounts() map[string]int32 {
	if x != nil {
		return x.TransactionTypeCounts
	}
	return nil
}

var File_proto_account_info_proto protoreflect.FileDescriptor

const file_proto_account_info_proto_rawDesc = "" +
	"\n" +
	"\x18proto/account_info.proto\x12\x17fintech.account_info.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\x15GetAccountInfoRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0finclude_balance\x18\x02 \x01(\bR\x0eincludeBalance\x12>\n" +
	"\x1binclude_recent_transactions\x18\x03 \x01(\bR\x19includeRecentTransactions\x128\n" +
	"\x18recent_transaction_limit\x18\x04 \x01(\x05R\x16recentTransactionLimit\"\x9d\x02\n" +
	"\x16GetAccountInfoResponse\x12@\n" +
	"\aaccount\x18\x01 \x01(\v2&.fintech.account_info.v1.LedgerAccountR\aaccount\x12'\n" +
	"\x0fcurrent_balance\x18\x02 \x01(\x01R\x0ecurrentBalance\x12U\n" +
	"\x13recent_transactions\x18\x03 \x03(\v2$.fintech.account_info.v1.TransactionR\x12recentTransactions\x12A\n" +
	"\ametrics\x18\x04 \x01(\v2'.fintech.account_info.v1.AccountMetricsR\ametrics\"\x86\x01\n" +
	"\x18GetAccountSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vaccount_ids\x18\x02 \x03(\tR\n" +
	"accountIds\x120\n" +
	"\x14include_sub_accounts\x18\x03 \x01(\bR\x12includeSubAccounts\"\x8c\x02\n" +
	"\x19GetAccountSummaryResponse\x12C\n" +
	"\baccounts\x18\x01 \x03(\v2'.fintech.account_info.v1.AccountSummaryR\baccounts\x12#\n" +
	"\rtotal_balance\x18\x02 \x01(\x01R\ftotalBalance\x12#\n" +
	"\rbase_currency\x18\x03 \x01(\tR\fbaseCurrency\x12%\n" +
	"\x0etotal_accounts\x18\x04 \x01(\x05R\rtotalAccounts\x129\n" +
	"\n" +
	"summary_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tsummaryAt\"\x94\x03\n" +
	"\x19TransactionHistoryRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x127\n" +
	"\tfrom_date\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bfromDate\x123\n" +
	"\ato_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06toDate\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12U\n" +
	"\x11transaction_types\x18\x06 \x03(\x0e2(.fintech.account_info.v1.TransactionTypeR\x10transactionTypes\x12\x1d\n" +
	"\n" +
	"min_amount\x18\a \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\b \x01(\x01R\tmaxAmount\x12'\n" +
	"\x0finclude_pending\x18\t \x01(\bR\x0eincludePending\"\xc3\x01\n" +
	"\x1aTransactionHistoryResponse\x12F\n" +
	"\vtransaction\x18\x01 \x01(\v2$.fintech.account_info.v1.TransactionR\vtransaction\x12\x17\n" +
	"\ais_last\x18\x02 \x01(\bR\x06isLast\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rcurrent_index\x18\x04 \x01(\x05R\fcurrentIndex\"\xea\x03\n" +
	"\rLedgerAccount\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12%\n" +
	"\x0eaccount_number\x18\x03 \x01(\tR\raccountNumber\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x128\n" +
	"\x04type\x18\x06 \x01(\x0e2$.fintech.account_info.v1.AccountTypeR\x04type\x12>\n" +
	"\x06status\x18\a \x01(\x0e2&.fintech.account_info.v1.AccountStatusR\x06status\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1b\n" +
	"\tparent_id\x18\t \x01(\tR\bparentId\x12\x1b\n" +
	"\tis_system\x18\n" +
	" \x01(\bR\bisSystem\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9c\x03\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12<\n" +
	"\x04type\x18\x03 \x01(\x0e2(.fintech.account_info.v1.TransactionTypeR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1c\n" +
	"\treference\x18\x05 \x01(\tR\treference\x12!\n" +
	"\ftotal_amount\x18\x06 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x128\n" +
	"\ttimestamp\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12>\n" +
	"\aentries\x18\n" +
	" \x03(\v2$.fintech.account_info.v1.LedgerEntryR\aentries\"\xf2\x02\n" +
	"\vLedgerEntry\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12(\n" +
	"\x10debit_account_id\x18\x03 \x01(\tR\x0edebitAccountId\x12*\n" +
	"\x11credit_account_id\x18\x04 \x01(\tR\x0fcreditAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"entry_type\x18\a \x01(\tR\tentryType\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1c\n" +
	"\treference\x18\t \x01(\tR\treference\x128\n" +
	"\ttimestamp\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xb7\x03\n" +
	"\x0eAccountSummary\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12G\n" +
	"\faccount_type\x18\x03 \x01(\x0e2$.fintech.account_info.v1.AccountTypeR\vaccountType\x12'\n" +
	"\x0fcurrent_balance\x18\x04 \x01(\x01R\x0ecurrentBalance\x12+\n" +
	"\x11available_balance\x18\x05 \x01(\x01R\x10availableBalance\x12'\n" +
	"\x0fpending_balance\x18\x06 \x01(\x01R\x0ependingBalance\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12>\n" +
	"\x06status\x18\b \x01(\x0e2&.fintech.account_info.v1.AccountStatusR\x06status\x12?\n" +
	"\rlast_activity\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\flastActivity\"\x93\x04\n" +
	"\x0eAccountMetrics\x12-\n" +
	"\x12total_transactions\x18\x01 \x01(\x05R\x11totalTransactions\x12!\n" +
	"\ftotal_debits\x18\x02 \x01(\x01R\vtotalDebits\x12#\n" +
	"\rtotal_credits\x18\x03 \x01(\x01R\ftotalCredits\x124\n" +
	"\x16avg_transaction_amount\x18\x04 \x01(\x01R\x14avgTransactionAmount\x12G\n" +
	"\x11first_transaction\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x10firstTransaction\x12E\n" +
	"\x10last_transaction\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0flastTransaction\x12z\n" +
	"\x17transaction_type_counts\x18\a \x03(\v2B.fintech.account_info.v1.AccountMetrics.TransactionTypeCountsEntryR\x15transactionTypeCounts\x1aH\n" +
	"\x1aTransactionTypeCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01*\xaa\x02\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_BANK\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_TYPE_CASH\x10\x02\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_CREDIT\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x05\x12\x16\n" +
	"\x12ACCOUNT_TYPE_ASSET\x10\x06\x12\x1a\n" +
	"\x16ACCOUNT_TYPE_LIABILITY\x10\a\x12\x17\n" +
	"\x13ACCOUNT_TYPE_EQUITY\x10\b\x12\x18\n" +
	"\x14ACCOUNT_TYPE_REVENUE\x10\t\x12\x18\n" +
	"\x14ACCOUNT_TYPE_EXPENSE\x10\n" +
	"*\xa0\x01\n" +
	"\rAccountStatus\x12\x1e\n" +
	"\x1aACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCOUNT_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17ACCOUNT_STATUS_INACTIVE\x10\x02\x12\x1c\n" +
	"\x18ACCOUNT_STATUS_SUSPENDED\x10\x03\x12\x19\n" +
	"\x15ACCOUNT_STATUS_CLOSED\x10\x04*\x87\x02\n" +
	"\x0fTransactionType\x12 \n" +
	"\x1cTRANSACTION_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19TRANSACTION_TYPE_TRANSFER\x10\x01\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_DEPOSIT\x10\x02\x12\x1f\n" +
	"\x1bTRANSACTION_TYPE_WITHDRAWAL\x10\x03\x12\x1c\n" +
	"\x18TRANSACTION_TYPE_PAYMENT\x10\x04\x12\x1b\n" +
	"\x17TRANSACTION_TYPE_REFUND\x10\x05\x12\x18\n" +
	"\x14TRANSACTION_TYPE_FEE\x10\x06\x12\x1f\n" +
	"\x1bTRANSACTION_TYPE_ADJUSTMENT\x10\a2\x8b\x03\n" +
	"\x12AccountInfoService\x12q\n" +
	"\x0eGetAccountInfo\x12..fintech.account_info.v1.GetAccountInfoRequest\x1a/.fintech.account_info.v1.GetAccountInfoResponse\x12z\n" +
	"\x11GetAccountSummary\x121.fintech.account_info.v1.GetAccountSummaryRequest\x1a2.fintech.account_info.v1.GetAccountSummaryResponse\x12\x85\x01\n" +
	"\x18StreamTransactionHistory\x122.fintech.account_info.v1.TransactionHistoryRequest\x1a3.fintech.account_info.v1.TransactionHistoryResponse0\x01B5Z3fintech-api/proto/gen/account_info;account_infob\x06proto3"

var (
	file_proto_account_info_proto_rawDescOnce sync.Once
	file_proto_account_info_proto_rawDescData []byte
)

func file_proto_account_info_proto_rawDescGZIP() []byte {
	file_proto_account_info_proto_rawDescOnce.Do(func() {
		file_proto_account_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_info_proto_rawDesc), len(file_proto_account_info_proto_rawDesc)))
	})
	return file_proto_account_info_proto_rawDescData
}

var file_proto_account_info_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_account_info_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_account_info_proto_goTypes = []any{
	(AccountType)(0),                   // 0: fintech.account_info.v1.AccountType
	(AccountStatus)(0),                 // 1: fintech.account_info.v1.AccountStatus
	(TransactionType)(0),               // 2: fintech.account_info.v1.TransactionType
	(*GetAccountInfoRequest)(nil),      // 3: fintech.account_info.v1.GetAccountInfoRequest
	(*GetAccountInfoResponse)(nil),     // 4: fintech.account_info.v1.GetAccountInfoResponse
	(*GetAccountSummaryRequest)(nil),   // 5: fintech.account_info.v1.GetAccountSummaryRequest
	(*GetAccountSummaryResponse)(nil),  // 6: fintech.account_info.v1.GetAccountSummaryResponse
	(*TransactionHistoryRequest)(nil),  // 7: fintech.account_info.v1.TransactionHistoryRequest
	(*TransactionHistoryResponse)(nil), // 8: fintech.account_info.v1.TransactionHistoryResponse
	(*LedgerAccount)(nil),              // 9: fintech.account_info.v1.LedgerAccount
	(*Transaction)(nil),                // 10: fintech.account_info.v1.Transaction
	(*LedgerEntry)(nil),                // 11: fintech.account_info.v1.LedgerEntry
	(*AccountSummary)(nil),             // 12: fintech.account_info.v1.AccountSummary
	(*AccountMetrics)(nil),             // 13: fintech.account_info.v1.AccountMetrics
	nil,                                // 14: fintech.account_info.v1.AccountMetrics.TransactionTypeCountsEntry
	(*timestamppb.Timestamp)(nil),      // 15: google.protobuf.Timestamp
}
var file_proto_account_info_proto_depIdxs = []int32{
	9,  // 0: fintech.account_info.v1.GetAccountInfoResponse.account:type_name -> fintech.account_info.v1.LedgerAccount
	10, // 1: fintech.account_info.v1.GetAccountInfoResponse.recent_transactions:type_name -> fintech.account_info.v1.Transaction
	13, // 2: fintech.account_info.v1.GetAccountInfoResponse.metrics:type_name -> fintech.account_info.v1.AccountMetrics
	12, // 3: fintech.account_info.v1.GetAccountSummaryResponse.accounts:type_name -> fintech.account_info.v1.AccountSummary
	15, // 4: fintech.account_info.v1.GetAccountSummaryResponse.summary_at:type_name -> google.protobuf.Timestamp
	15, // 5: fintech.account_info.v1.TransactionHistoryRequest.from_date:type_name -> google.protobuf.Timestamp
	15, // 6: fintech.account_info.v1.TransactionHistoryRequest.to_date:type_name -> google.protobuf.Timestamp
	2,  // 7: fintech.account_info.v1.TransactionHistoryRequest.transaction_types:type_name -> fintech.account_info.v1.TransactionType
	10, // 8: fintech.account_info.v1.TransactionHistoryResponse.transaction:type_name -> fintech.account_info.v1.Transaction
	0,  // 9: fintech.account_info.v1.LedgerAccount.type:type_name -> fintech.account_info.v1.AccountType
	1,  // 10: fintech.account_info.v1.LedgerAccount.status:type_name -> fintech.account_info.v1.AccountStatus
	15, // 11: fintech.account_info.v1.LedgerAccount.created_at:type_name -> google.protobuf.Timestamp
	15, // 12: fintech.account_info.v1.LedgerAccount.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 13: fintech.account_info.v1.Transaction.type:type_name -> fintech.account_info.v1.TransactionType
	15, // 14: fintech.account_info.v1.Transaction.timestamp:type_name -> google.protobuf.Timestamp
	11, // 15: fintech.account_info.v1.Transaction.entries:type_name -> fintech.account_info.v1.LedgerEntry
	15, // 16: fintech.account_info.v1.LedgerEntry.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 17: fintech.account_info.v1.AccountSummary.account_type:type_name -> fintech.account_info.v1.AccountType
	1,  // 18: fintech.account_info.v1.AccountSummary.status:type_name -> fintech.account_info.v1.AccountStatus
	15, // 19: fintech.account_info.v1.AccountSummary.last_activity:type_name -> google.protobuf.Timestamp
	15, // 20: fintech.account_info.v1.AccountMetrics.first_transaction:type_name -> google.protobuf.Timestamp
	15, // 21: fintech.account_info.v1.AccountMetrics.last_transaction:type_name -> google.protobuf.Timestamp
	14, // 22: fintech.account_info.v1.AccountMetrics.transaction_type_counts:type_name -> fintech.account_info.v1.AccountMetrics.TransactionTypeCountsEntry
	3,  // 23: fintech.account_info.v1.AccountInfoService.GetAccountInfo:input_type -> fintech.account_info.v1.GetAccountInfoRequest
	5,  // 24: fintech.account_info.v1.AccountInfoService.GetAccountSummary:input_type -> fintech.account_info.v1.GetAccountSummaryRequest
	7,  // 25: fintech.account_info.v1.AccountInfoService.StreamTransactionHistory:input_type -> fintech.account_info.v1.TransactionHistoryRequest
	4,  // 26: fintech.account_info.v1.AccountInfoService.GetAccountInfo:output_type -> fintech.account_info.v1.GetAccountInfoResponse
	6,  // 27: fintech.account_info.v1.AccountInfoService.GetAccountSummary:output_type -> fintech.account_info.v1.GetAccountSummaryResponse
	8,  // 28: fintech.account_info.v1.AccountInfoService.StreamTransactionHistory:output_type -> fintech.account_info.v1.TransactionHistoryResponse
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_proto_account_info_proto_init() }
func file_proto_account_info_proto_init() {
	if File_proto_account_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_info_proto_rawDesc), len(file_proto_account_info_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_account_info_proto_goTypes,
		DependencyIndexes: file_proto_account_info_proto_depIdxs,
		EnumInfos:         file_proto_account_info_proto_enumTypes,
		MessageInfos:      file_proto_account_info_proto_msgTypes,
	}.Build()
	File_proto_account_info_proto = out.File
	file_proto_account_info_proto_goTypes = nil
	file_proto_account_info_proto_depIdxs = nil
}
