// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/payment_rail.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Payment rail types
type PaymentRailType int32

const (
	PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED     PaymentRailType = 0
	PaymentRailType_PAYMENT_RAIL_TYPE_UPI             PaymentRailType = 1
	PaymentRailType_PAYMENT_RAIL_TYPE_SEPA            PaymentRailType = 2
	PaymentRailType_PAYMENT_RAIL_TYPE_CRYPTO          PaymentRailType = 3
	PaymentRailType_PAYMENT_RAIL_TYPE_ACH             PaymentRailType = 4
	PaymentRailType_PAYMENT_RAIL_TYPE_SWIFT           PaymentRailType = 5
	PaymentRailType_PAYMENT_RAIL_TYPE_PIX             PaymentRailType = 6
	PaymentRailType_PAYMENT_RAIL_TYPE_FASTER_PAYMENTS PaymentRailType = 7
	PaymentRailType_PAYMENT_RAIL_TYPE_INTERAC         PaymentRailType = 8
)

// Enum value maps for PaymentRailType.
var (
	PaymentRailType_name = map[int32]string{
		0: "PAYMENT_RAIL_TYPE_UNSPECIFIED",
		1: "PAYMENT_RAIL_TYPE_UPI",
		2: "PAYMENT_RAIL_TYPE_SEPA",
		3: "PAYMENT_RAIL_TYPE_CRYPTO",
		4: "PAYMENT_RAIL_TYPE_ACH",
		5: "PAYMENT_RAIL_TYPE_SWIFT",
		6: "PAYMENT_RAIL_TYPE_PIX",
		7: "PAYMENT_RAIL_TYPE_FASTER_PAYMENTS",
		8: "PAYMENT_RAIL_TYPE_INTERAC",
	}
	PaymentRailType_value = map[string]int32{
		"PAYMENT_RAIL_TYPE_UNSPECIFIED":     0,
		"PAYMENT_RAIL_TYPE_UPI":             1,
		"PAYMENT_RAIL_TYPE_SEPA":            2,
		"PAYMENT_RAIL_TYPE_CRYPTO":          3,
		"PAYMENT_RAIL_TYPE_ACH":             4,
		"PAYMENT_RAIL_TYPE_SWIFT":           5,
		"PAYMENT_RAIL_TYPE_PIX":             6,
		"PAYMENT_RAIL_TYPE_FASTER_PAYMENTS": 7,
		"PAYMENT_RAIL_TYPE_INTERAC":         8,
	}
)

func (x PaymentRailType) Enum() *PaymentRailType {
	p := new(PaymentRailType)
	*p = x
	return p
}

func (x PaymentRailType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentRailType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_rail_proto_enumTypes[0].Descriptor()
}

func (PaymentRailType) Type() protoreflect.EnumType {
	return &file_proto_payment_rail_proto_enumTypes[0]
}

func (x PaymentRailType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentRailType.Descriptor instead.
func (PaymentRailType) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{0}
}

// Rail selection priority
type SelectionPriority int32

const (
	SelectionPriority_SELECTION_PRIORITY_UNSPECIFIED SelectionPriority = 0
	SelectionPriority_SELECTION_PRIORITY_SPEED       SelectionPriority = 1
	SelectionPriority_SELECTION_PRIORITY_COST        SelectionPriority = 2
	SelectionPriority_SELECTION_PRIORITY_RELIABILITY SelectionPriority = 3
	SelectionPriority_SELECTION_PRIORITY_COMPLIANCE  SelectionPriority = 4
)

// Enum value maps for SelectionPriority.
var (
	SelectionPriority_name = map[int32]string{
		0: "SELECTION_PRIORITY_UNSPECIFIED",
		1: "SELECTION_PRIORITY_SPEED",
		2: "SELECTION_PRIORITY_COST",
		3: "SELECTION_PRIORITY_RELIABILITY",
		4: "SELECTION_PRIORITY_COMPLIANCE",
	}
	SelectionPriority_value = map[string]int32{
		"SELECTION_PRIORITY_UNSPECIFIED": 0,
		"SELECTION_PRIORITY_SPEED":       1,
		"SELECTION_PRIORITY_COST":        2,
		"SELECTION_PRIORITY_RELIABILITY": 3,
		"SELECTION_PRIORITY_COMPLIANCE":  4,
	}
)

func (x SelectionPriority) Enum() *SelectionPriority {
	p := new(SelectionPriority)
	*p = x
	return p
}

func (x SelectionPriority) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectionPriority) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_rail_proto_enumTypes[1].Descriptor()
}

func (SelectionPriority) Type() protoreflect.EnumType {
	return &file_proto_payment_rail_proto_enumTypes[1]
}

func (x SelectionPriority) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectionPriority.Descriptor instead.
func (SelectionPriority) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{1}
}

// Rail status
type RailStatus int32

const (
	RailStatus_RAIL_STATUS_UNSPECIFIED RailStatus = 0
	RailStatus_RAIL_STATUS_ACTIVE      RailStatus = 1
	RailStatus_RAIL_STATUS_MAINTENANCE RailStatus = 2
	RailStatus_RAIL_STATUS_DEGRADED    RailStatus = 3
	RailStatus_RAIL_STATUS_OFFLINE     RailStatus = 4
)

// Enum value maps for RailStatus.
var (
	RailStatus_name = map[int32]string{
		0: "RAIL_STATUS_UNSPECIFIED",
		1: "RAIL_STATUS_ACTIVE",
		2: "RAIL_STATUS_MAINTENANCE",
		3: "RAIL_STATUS_DEGRADED",
		4: "RAIL_STATUS_OFFLINE",
	}
	RailStatus_value = map[string]int32{
		"RAIL_STATUS_UNSPECIFIED": 0,
		"RAIL_STATUS_ACTIVE":      1,
		"RAIL_STATUS_MAINTENANCE": 2,
		"RAIL_STATUS_DEGRADED":    3,
		"RAIL_STATUS_OFFLINE":     4,
	}
)

func (x RailStatus) Enum() *RailStatus {
	p := new(RailStatus)
	*p = x
	return p
}

func (x RailStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RailStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_payment_rail_proto_enumTypes[2].Descriptor()
}

func (RailStatus) Type() protoreflect.EnumType {
	return &file_proto_payment_rail_proto_enumTypes[2]
}

func (x RailStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RailStatus.Descriptor instead.
func (RailStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{2}
}

// Select payment rail request
type SelectRailRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	FromCountry         string                 `protobuf:"bytes,1,opt,name=from_country,json=fromCountry,proto3" json:"from_country,omitempty"`
	ToCountry           string                 `protobuf:"bytes,2,opt,name=to_country,json=toCountry,proto3" json:"to_country,omitempty"`
	Amount              float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency            string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Priority            SelectionPriority      `protobuf:"varint,5,opt,name=priority,proto3,enum=fintech.payment_rail.v1.SelectionPriority" json:"priority,omitempty"`
	IncludeAlternatives bool                   `protobuf:"varint,6,opt,name=include_alternatives,json=includeAlternatives,proto3" json:"include_alternatives,omitempty"`
	ExcludedRails       []PaymentRailType      `protobuf:"varint,7,rep,packed,name=excluded_rails,json=excludedRails,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"excluded_rails,omitempty"`
	Metadata            map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SelectRailRequest) Reset() {
	*x = SelectRailRequest{}
	mi := &file_proto_payment_rail_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRailRequest) ProtoMessage() {}

func (x *SelectRailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRailRequest.ProtoReflect.Descriptor instead.
func (*SelectRailRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{0}
}

func (x *SelectRailRequest) GetFromCountry() string {
	if x != nil {
		return x.FromCountry
	}
	return ""
}

func (x *SelectRailRequest) GetToCountry() string {
	if x != nil {
		return x.ToCountry
	}
	return ""
}

func (x *SelectRailRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SelectRailRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SelectRailRequest) GetPriority() SelectionPriority {
	if x != nil {
		return x.Priority
	}
	return SelectionPriority_SELECTION_PRIORITY_UNSPECIFIED
}

func (x *SelectRailRequest) GetIncludeAlternatives() bool {
	if x != nil {
		return x.IncludeAlternatives
	}
	return false
}

func (x *SelectRailRequest) GetExcludedRails() []PaymentRailType {
	if x != nil {
		return x.ExcludedRails
	}
	return nil
}

func (x *SelectRailRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Select payment rail response
type SelectRailResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SelectedRail    PaymentRailType        `protobuf:"varint,1,opt,name=selected_rail,json=selectedRail,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"selected_rail,omitempty"`
	EstimatedFee    float64                `protobuf:"fixed64,2,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	EstimatedTime   string                 `protobuf:"bytes,3,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	FxRate          float64                `protobuf:"fixed64,4,opt,name=fx_rate,json=fxRate,proto3" json:"fx_rate,omitempty"`
	Reason          string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	RailConfig      *RailConfig            `protobuf:"bytes,6,opt,name=rail_config,json=railConfig,proto3" json:"rail_config,omitempty"`
	Alternatives    []*RailOption          `protobuf:"bytes,7,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	ConfidenceScore float64                `protobuf:"fixed64,8,opt,name=confidence_score,json=confidenceScore,proto3" json:"confidence_score,omitempty"`
	SelectedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=selected_at,json=selectedAt,proto3" json:"selected_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelectRailResponse) Reset() {
	*x = SelectRailResponse{}
	mi := &file_proto_payment_rail_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRailResponse) ProtoMessage() {}

func (x *SelectRailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRailResponse.ProtoReflect.Descriptor instead.
func (*SelectRailResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{1}
}

func (x *SelectRailResponse) GetSelectedRail() PaymentRailType {
	if x != nil {
		return x.SelectedRail
	}
	return PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED
}

func (x *SelectRailResponse) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *SelectRailResponse) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

func (x *SelectRailResponse) GetFxRate() float64 {
	if x != nil {
		return x.FxRate
	}
	return 0
}

func (x *SelectRailResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SelectRailResponse) GetRailConfig() *RailConfig {
	if x != nil {
		return x.RailConfig
	}
	return nil
}

func (x *SelectRailResponse) GetAlternatives() []*RailOption {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *SelectRailResponse) GetConfidenceScore() float64 {
	if x != nil {
		return x.ConfidenceScore
	}
	return 0
}

func (x *SelectRailResponse) GetSelectedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SelectedAt
	}
	return nil
}

// Get available rails request
type GetRailsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FromCountry     string                 `protobuf:"bytes,1,opt,name=from_country,json=fromCountry,proto3" json:"from_country,omitempty"`
	ToCountry       string                 `protobuf:"bytes,2,opt,name=to_country,json=toCountry,proto3" json:"to_country,omitempty"`
	Currency        string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	MinAmount       float64                `protobuf:"fixed64,4,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount       float64                `protobuf:"fixed64,5,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	IncludeInactive bool                   `protobuf:"varint,6,opt,name=include_inactive,json=includeInactive,proto3" json:"include_inactive,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetRailsRequest) Reset() {
	*x = GetRailsRequest{}
	mi := &file_proto_payment_rail_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRailsRequest) ProtoMessage() {}

func (x *GetRailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRailsRequest.ProtoReflect.Descriptor instead.
func (*GetRailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{2}
}

func (x *GetRailsRequest) GetFromCountry() string {
	if x != nil {
		return x.FromCountry
	}
	return ""
}

func (x *GetRailsRequest) GetToCountry() string {
	if x != nil {
		return x.ToCountry
	}
	return ""
}

func (x *GetRailsRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetRailsRequest) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *GetRailsRequest) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *GetRailsRequest) GetIncludeInactive() bool {
	if x != nil {
		return x.IncludeInactive
	}
	return false
}

// Get available rails response
type GetRailsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AvailableRails []*RailOption          `protobuf:"bytes,1,rep,name=available_rails,json=availableRails,proto3" json:"available_rails,omitempty"`
	TotalCount     int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	RouteId        string                 `protobuf:"bytes,3,opt,name=route_id,json=routeId,proto3" json:"route_id,omitempty"`
	CachedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=cached_at,json=cachedAt,proto3" json:"cached_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRailsResponse) Reset() {
	*x = GetRailsResponse{}
	mi := &file_proto_payment_rail_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRailsResponse) ProtoMessage() {}

func (x *GetRailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRailsResponse.ProtoReflect.Descriptor instead.
func (*GetRailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{3}
}

func (x *GetRailsResponse) GetAvailableRails() []*RailOption {
	if x != nil {
		return x.AvailableRails
	}
	return nil
}

func (x *GetRailsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetRailsResponse) GetRouteId() string {
	if x != nil {
		return x.RouteId
	}
	return ""
}

func (x *GetRailsResponse) GetCachedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CachedAt
	}
	return nil
}

// Get rail metrics request
type GetRailMetricsRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RailType             PaymentRailType        `protobuf:"varint,1,opt,name=rail_type,json=railType,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"rail_type,omitempty"`
	TimePeriod           string                 `protobuf:"bytes,2,opt,name=time_period,json=timePeriod,proto3" json:"time_period,omitempty"` // "1h", "24h", "7d", "30d"
	IncludeDetailedStats bool                   `protobuf:"varint,3,opt,name=include_detailed_stats,json=includeDetailedStats,proto3" json:"include_detailed_stats,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetRailMetricsRequest) Reset() {
	*x = GetRailMetricsRequest{}
	mi := &file_proto_payment_rail_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRailMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRailMetricsRequest) ProtoMessage() {}

func (x *GetRailMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRailMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetRailMetricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{4}
}

func (x *GetRailMetricsRequest) GetRailType() PaymentRailType {
	if x != nil {
		return x.RailType
	}
	return PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED
}

func (x *GetRailMetricsRequest) GetTimePeriod() string {
	if x != nil {
		return x.TimePeriod
	}
	return ""
}

func (x *GetRailMetricsRequest) GetIncludeDetailedStats() bool {
	if x != nil {
		return x.IncludeDetailedStats
	}
	return false
}

// Get rail metrics response
type GetRailMetricsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RailType          PaymentRailType        `protobuf:"varint,1,opt,name=rail_type,json=railType,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"rail_type,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,2,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgProcessingTime float64                `protobuf:"fixed64,3,opt,name=avg_processing_time,json=avgProcessingTime,proto3" json:"avg_processing_time,omitempty"`
	AvgFee            float64                `protobuf:"fixed64,4,opt,name=avg_fee,json=avgFee,proto3" json:"avg_fee,omitempty"`
	TotalTransactions int32                  `protobuf:"varint,5,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	CurrentStatus     RailStatus             `protobuf:"varint,6,opt,name=current_status,json=currentStatus,proto3,enum=fintech.payment_rail.v1.RailStatus" json:"current_status,omitempty"`
	Metrics           []*MetricDataPoint     `protobuf:"bytes,7,rep,name=metrics,proto3" json:"metrics,omitempty"`
	MetricsFrom       *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=metrics_from,json=metricsFrom,proto3" json:"metrics_from,omitempty"`
	MetricsTo         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=metrics_to,json=metricsTo,proto3" json:"metrics_to,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetRailMetricsResponse) Reset() {
	*x = GetRailMetricsResponse{}
	mi := &file_proto_payment_rail_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRailMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRailMetricsResponse) ProtoMessage() {}

func (x *GetRailMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRailMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetRailMetricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{5}
}

func (x *GetRailMetricsResponse) GetRailType() PaymentRailType {
	if x != nil {
		return x.RailType
	}
	return PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED
}

func (x *GetRailMetricsResponse) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *GetRailMetricsResponse) GetAvgProcessingTime() float64 {
	if x != nil {
		return x.AvgProcessingTime
	}
	return 0
}

func (x *GetRailMetricsResponse) GetAvgFee() float64 {
	if x != nil {
		return x.AvgFee
	}
	return 0
}

func (x *GetRailMetricsResponse) GetTotalTransactions() int32 {
	if x != nil {
		return x.TotalTransactions
	}
	return 0
}

func (x *GetRailMetricsResponse) GetCurrentStatus() RailStatus {
	if x != nil {
		return x.CurrentStatus
	}
	return RailStatus_RAIL_STATUS_UNSPECIFIED
}

func (x *GetRailMetricsResponse) GetMetrics() []*MetricDataPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *GetRailMetricsResponse) GetMetricsFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.MetricsFrom
	}
	return nil
}

func (x *GetRailMetricsResponse) GetMetricsTo() *timestamppb.Timestamp {
	if x != nil {
		return x.MetricsTo
	}
	return nil
}

// Rail configuration
type RailConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RailType            PaymentRailType        `protobuf:"varint,1,opt,name=rail_type,json=railType,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"rail_type,omitempty"`
	MinAmount           float64                `protobuf:"fixed64,2,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`
	MaxAmount           float64                `protobuf:"fixed64,3,opt,name=max_amount,json=maxAmount,proto3" json:"max_amount,omitempty"`
	SupportedCurrencies []string               `protobuf:"bytes,4,rep,name=supported_currencies,json=supportedCurrencies,proto3" json:"supported_currencies,omitempty"`
	SupportedCountries  []string               `protobuf:"bytes,5,rep,name=supported_countries,json=supportedCountries,proto3" json:"supported_countries,omitempty"`
	ProcessingTime      string                 `protobuf:"bytes,6,opt,name=processing_time,json=processingTime,proto3" json:"processing_time,omitempty"`
	BaseFee             float64                `protobuf:"fixed64,7,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	PercentageFee       float64                `protobuf:"fixed64,8,opt,name=percentage_fee,json=percentageFee,proto3" json:"percentage_fee,omitempty"`
	ConfigParams        map[string]string      `protobuf:"bytes,9,rep,name=config_params,json=configParams,proto3" json:"config_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RailConfig) Reset() {
	*x = RailConfig{}
	mi := &file_proto_payment_rail_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RailConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RailConfig) ProtoMessage() {}

func (x *RailConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RailConfig.ProtoReflect.Descriptor instead.
func (*RailConfig) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{6}
}

func (x *RailConfig) GetRailType() PaymentRailType {
	if x != nil {
		return x.RailType
	}
	return PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED
}

func (x *RailConfig) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *RailConfig) GetMaxAmount() float64 {
	if x != nil {
		return x.MaxAmount
	}
	return 0
}

func (x *RailConfig) GetSupportedCurrencies() []string {
	if x != nil {
		return x.SupportedCurrencies
	}
	return nil
}

func (x *RailConfig) GetSupportedCountries() []string {
	if x != nil {
		return x.SupportedCountries
	}
	return nil
}

func (x *RailConfig) GetProcessingTime() string {
	if x != nil {
		return x.ProcessingTime
	}
	return ""
}

func (x *RailConfig) GetBaseFee() float64 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

func (x *RailConfig) GetPercentageFee() float64 {
	if x != nil {
		return x.PercentageFee
	}
	return 0
}

func (x *RailConfig) GetConfigParams() map[string]string {
	if x != nil {
		return x.ConfigParams
	}
	return nil
}

// Rail option details
type RailOption struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RailType         PaymentRailType        `protobuf:"varint,1,opt,name=rail_type,json=railType,proto3,enum=fintech.payment_rail.v1.PaymentRailType" json:"rail_type,omitempty"`
	RailName         string                 `protobuf:"bytes,2,opt,name=rail_name,json=railName,proto3" json:"rail_name,omitempty"`
	EstimatedFee     float64                `protobuf:"fixed64,3,opt,name=estimated_fee,json=estimatedFee,proto3" json:"estimated_fee,omitempty"`
	EstimatedTime    string                 `protobuf:"bytes,4,opt,name=estimated_time,json=estimatedTime,proto3" json:"estimated_time,omitempty"`
	FxRate           float64                `protobuf:"fixed64,5,opt,name=fx_rate,json=fxRate,proto3" json:"fx_rate,omitempty"`
	Status           RailStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=fintech.payment_rail.v1.RailStatus" json:"status,omitempty"`
	ReliabilityScore float64                `protobuf:"fixed64,7,opt,name=reliability_score,json=reliabilityScore,proto3" json:"reliability_score,omitempty"`
	Description      string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Features         []string               `protobuf:"bytes,9,rep,name=features,proto3" json:"features,omitempty"`
	Config           *RailConfig            `protobuf:"bytes,10,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RailOption) Reset() {
	*x = RailOption{}
	mi := &file_proto_payment_rail_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RailOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RailOption) ProtoMessage() {}

func (x *RailOption) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RailOption.ProtoReflect.Descriptor instead.
func (*RailOption) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{7}
}

func (x *RailOption) GetRailType() PaymentRailType {
	if x != nil {
		return x.RailType
	}
	return PaymentRailType_PAYMENT_RAIL_TYPE_UNSPECIFIED
}

func (x *RailOption) GetRailName() string {
	if x != nil {
		return x.RailName
	}
	return ""
}

func (x *RailOption) GetEstimatedFee() float64 {
	if x != nil {
		return x.EstimatedFee
	}
	return 0
}

func (x *RailOption) GetEstimatedTime() string {
	if x != nil {
		return x.EstimatedTime
	}
	return ""
}

func (x *RailOption) GetFxRate() float64 {
	if x != nil {
		return x.FxRate
	}
	return 0
}

func (x *RailOption) GetStatus() RailStatus {
	if x != nil {
		return x.Status
	}
	return RailStatus_RAIL_STATUS_UNSPECIFIED
}

func (x *RailOption) GetReliabilityScore() float64 {
	if x != nil {
		return x.ReliabilityScore
	}
	return 0
}

func (x *RailOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RailOption) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *RailOption) GetConfig() *RailConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Metrics data point
type MetricDataPoint struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	SuccessRate       float64                `protobuf:"fixed64,2,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	AvgProcessingTime float64                `protobuf:"fixed64,3,opt,name=avg_processing_time,json=avgProcessingTime,proto3" json:"avg_processing_time,omitempty"`
	AvgFee            float64                `protobuf:"fixed64,4,opt,name=avg_fee,json=avgFee,proto3" json:"avg_fee,omitempty"`
	TransactionCount  int32                  `protobuf:"varint,5,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	Status            RailStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=fintech.payment_rail.v1.RailStatus" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MetricDataPoint) Reset() {
	*x = MetricDataPoint{}
	mi := &file_proto_payment_rail_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDataPoint) ProtoMessage() {}

func (x *MetricDataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_rail_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDataPoint.ProtoReflect.Descriptor instead.
func (*MetricDataPoint) Descriptor() ([]byte, []int) {
	return file_proto_payment_rail_proto_rawDescGZIP(), []int{8}
}

func (x *MetricDataPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricDataPoint) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *MetricDataPoint) GetAvgProcessingTime() float64 {
	if x != nil {
		return x.AvgProcessingTime
	}
	return 0
}

func (x *MetricDataPoint) GetAvgFee() float64 {
	if x != nil {
		return x.AvgFee
	}
	return 0
}

func (x *MetricDataPoint) GetTransactionCount() int32 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *MetricDataPoint) GetStatus() RailStatus {
	if x != nil {
		return x.Status
	}
	return RailStatus_RAIL_STATUS_UNSPECIFIED
}

var File_proto_payment_rail_proto protoreflect.FileDescriptor

const file_proto_payment_rail_proto_rawDesc = "" +
	"\n" +
	"\x18proto/payment_rail.proto\x12\x17fintech.payment_rail.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x03\n" +
	"\x11SelectRailRequest\x12!\n" +
	"\ffrom_country\x18\x01 \x01(\tR\vfromCountry\x12\x1d\n" +
	"\n" +
	"to_country\x18\x02 \x01(\tR\ttoCountry\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12F\n" +
	"\bpriority\x18\x05 \x01(\x0e2*.fintech.payment_rail.v1.SelectionPriorityR\bpriority\x121\n" +
	"\x14include_alternatives\x18\x06 \x01(\bR\x13includeAlternatives\x12O\n" +
	"\x0eexcluded_rails\x18\a \x03(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\rexcludedRails\x12T\n" +
	"\bmetadata\x18\b \x03(\v28.fintech.payment_rail.v1.SelectRailRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x03\n" +
	"\x12SelectRailResponse\x12M\n" +
	"\rselected_rail\x18\x01 \x01(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\fselectedRail\x12#\n" +
	"\restimated_fee\x18\x02 \x01(\x01R\festimatedFee\x12%\n" +
	"\x0eestimated_time\x18\x03 \x01(\tR\restimatedTime\x12\x17\n" +
	"\afx_rate\x18\x04 \x01(\x01R\x06fxRate\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12D\n" +
	"\vrail_config\x18\x06 \x01(\v2#.fintech.payment_rail.v1.RailConfigR\n" +
	"railConfig\x12G\n" +
	"\falternatives\x18\a \x03(\v2#.fintech.payment_rail.v1.RailOptionR\falternatives\x12)\n" +
	"\x10confidence_score\x18\b \x01(\x01R\x0fconfidenceScore\x12;\n" +
	"\vselected_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"selectedAt\"\xd8\x01\n" +
	"\x0fGetRailsRequest\x12!\n" +
	"\ffrom_country\x18\x01 \x01(\tR\vfromCountry\x12\x1d\n" +
	"\n" +
	"to_country\x18\x02 \x01(\tR\ttoCountry\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x04 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x05 \x01(\x01R\tmaxAmount\x12)\n" +
	"\x10include_inactive\x18\x06 \x01(\bR\x0fincludeInactive\"\xd5\x01\n" +
	"\x10GetRailsResponse\x12L\n" +
	"\x0favailable_rails\x18\x01 \x03(\v2#.fintech.payment_rail.v1.RailOptionR\x0eavailableRails\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x19\n" +
	"\broute_id\x18\x03 \x01(\tR\arouteId\x127\n" +
	"\tcached_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bcachedAt\"\xb5\x01\n" +
	"\x15GetRailMetricsRequest\x12E\n" +
	"\trail_type\x18\x01 \x01(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\brailType\x12\x1f\n" +
	"\vtime_period\x18\x02 \x01(\tR\n" +
	"timePeriod\x124\n" +
	"\x16include_detailed_stats\x18\x03 \x01(\bR\x14includeDetailedStats\"\x84\x04\n" +
	"\x16GetRailMetricsResponse\x12E\n" +
	"\trail_type\x18\x01 \x01(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\brailType\x12!\n" +
	"\fsuccess_rate\x18\x02 \x01(\x01R\vsuccessRate\x12.\n" +
	"\x13avg_processing_time\x18\x03 \x01(\x01R\x11avgProcessingTime\x12\x17\n" +
	"\aavg_fee\x18\x04 \x01(\x01R\x06avgFee\x12-\n" +
	"\x12total_transactions\x18\x05 \x01(\x05R\x11totalTransactions\x12J\n" +
	"\x0ecurrent_status\x18\x06 \x01(\x0e2#.fintech.payment_rail.v1.RailStatusR\rcurrentStatus\x12B\n" +
	"\ametrics\x18\a \x03(\v2(.fintech.payment_rail.v1.MetricDataPointR\ametrics\x12=\n" +
	"\fmetrics_from\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vmetricsFrom\x129\n" +
	"\n" +
	"metrics_to\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tmetricsTo\"\xfd\x03\n" +
	"\n" +
	"RailConfig\x12E\n" +
	"\trail_type\x18\x01 \x01(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\brailType\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x02 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"max_amount\x18\x03 \x01(\x01R\tmaxAmount\x121\n" +
	"\x14supported_currencies\x18\x04 \x03(\tR\x13supportedCurrencies\x12/\n" +
	"\x13supported_countries\x18\x05 \x03(\tR\x12supportedCountries\x12'\n" +
	"\x0fprocessing_time\x18\x06 \x01(\tR\x0eprocessingTime\x12\x19\n" +
	"\bbase_fee\x18\a \x01(\x01R\abaseFee\x12%\n" +
	"\x0epercentage_fee\x18\b \x01(\x01R\rpercentageFee\x12Z\n" +
	"\rconfig_params\x18\t \x03(\v25.fintech.payment_rail.v1.RailConfig.ConfigParamsEntryR\fconfigParams\x1a?\n" +
	"\x11ConfigParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xba\x03\n" +
	"\n" +
	"RailOption\x12E\n" +
	"\trail_type\x18\x01 \x01(\x0e2(.fintech.payment_rail.v1.PaymentRailTypeR\brailType\x12\x1b\n" +
	"\trail_name\x18\x02 \x01(\tR\brailName\x12#\n" +
	"\restimated_fee\x18\x03 \x01(\x01R\festimatedFee\x12%\n" +
	"\x0eestimated_time\x18\x04 \x01(\tR\restimatedTime\x12\x17\n" +
	"\afx_rate\x18\x05 \x01(\x01R\x06fxRate\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.fintech.payment_rail.v1.RailStatusR\x06status\x12+\n" +
	"\x11reliability_score\x18\a \x01(\x01R\x10reliabilityScore\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1a\n" +
	"\bfeatures\x18\t \x03(\tR\bfeatures\x12;\n" +
	"\x06config\x18\n" +
	" \x01(\v2#.fintech.payment_rail.v1.RailConfigR\x06config\"\xa1\x02\n" +
	"\x0fMetricDataPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12!\n" +
	"\fsuccess_rate\x18\x02 \x01(\x01R\vsuccessRate\x12.\n" +
	"\x13avg_processing_time\x18\x03 \x01(\x01R\x11avgProcessingTime\x12\x17\n" +
	"\aavg_fee\x18\x04 \x01(\x01R\x06avgFee\x12+\n" +
	"\x11transaction_count\x18\x05 \x01(\x05R\x10transactionCount\x12;\n" +
	"\x06status\x18\x06 \x01(\x0e2#.fintech.payment_rail.v1.RailStatusR\x06status*\xa2\x02\n" +
	"\x0fPaymentRailType\x12!\n" +
	"\x1dPAYMENT_RAIL_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PAYMENT_RAIL_TYPE_UPI\x10\x01\x12\x1a\n" +
	"\x16PAYMENT_RAIL_TYPE_SEPA\x10\x02\x12\x1c\n" +
	"\x18PAYMENT_RAIL_TYPE_CRYPTO\x10\x03\x12\x19\n" +
	"\x15PAYMENT_RAIL_TYPE_ACH\x10\x04\x12\x1b\n" +
	"\x17PAYMENT_RAIL_TYPE_SWIFT\x10\x05\x12\x19\n" +
	"\x15PAYMENT_RAIL_TYPE_PIX\x10\x06\x12%\n" +
	"!PAYMENT_RAIL_TYPE_FASTER_PAYMENTS\x10\a\x12\x1d\n" +
	"\x19PAYMENT_RAIL_TYPE_INTERAC\x10\b*\xb9\x01\n" +
	"\x11SelectionPriority\x12\"\n" +
	"\x1eSELECTION_PRIORITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SELECTION_PRIORITY_SPEED\x10\x01\x12\x1b\n" +
	"\x17SELECTION_PRIORITY_COST\x10\x02\x12\"\n" +
	"\x1eSELECTION_PRIORITY_RELIABILITY\x10\x03\x12!\n" +
	"\x1dSELECTION_PRIORITY_COMPLIANCE\x10\x04*\x91\x01\n" +
	"\n" +
	"RailStatus\x12\x1b\n" +
	"\x17RAIL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RAIL_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17RAIL_STATUS_MAINTENANCE\x10\x02\x12\x18\n" +
	"\x14RAIL_STATUS_DEGRADED\x10\x03\x12\x17\n" +
	"\x13RAIL_STATUS_OFFLINE\x10\x042\xdf\x02\n" +
	"\x12PaymentRailService\x12l\n" +
	"\x11SelectPaymentRail\x12*.fintech.payment_rail.v1.SelectRailRequest\x1a+.fintech.payment_rail.v1.SelectRailResponse\x12h\n" +
	"\x11GetAvailableRails\x12(.fintech.payment_rail.v1.GetRailsRequest\x1a).fintech.payment_rail.v1.GetRailsResponse\x12q\n" +
	"\x0eGetRailMetrics\x12..fintech.payment_rail.v1.GetRailMetricsRequest\x1a/.fintech.payment_rail.v1.GetRailMetricsResponseB!Z\x1ffintech-api/proto/gen/protob\x06proto3"

var (
	file_proto_payment_rail_proto_rawDescOnce sync.Once
	file_proto_payment_rail_proto_rawDescData []byte
)

func file_proto_payment_rail_proto_rawDescGZIP() []byte {
	file_proto_payment_rail_proto_rawDescOnce.Do(func() {
		file_proto_payment_rail_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_rail_proto_rawDesc), len(file_proto_payment_rail_proto_rawDesc)))
	})
	return file_proto_payment_rail_proto_rawDescData
}

var file_proto_payment_rail_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_payment_rail_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_payment_rail_proto_goTypes = []any{
	(PaymentRailType)(0),           // 0: fintech.payment_rail.v1.PaymentRailType
	(SelectionPriority)(0),         // 1: fintech.payment_rail.v1.SelectionPriority
	(RailStatus)(0),                // 2: fintech.payment_rail.v1.RailStatus
	(*SelectRailRequest)(nil),      // 3: fintech.payment_rail.v1.SelectRailRequest
	(*SelectRailResponse)(nil),     // 4: fintech.payment_rail.v1.SelectRailResponse
	(*GetRailsRequest)(nil),        // 5: fintech.payment_rail.v1.GetRailsRequest
	(*GetRailsResponse)(nil),       // 6: fintech.payment_rail.v1.GetRailsResponse
	(*GetRailMetricsRequest)(nil),  // 7: fintech.payment_rail.v1.GetRailMetricsRequest
	(*GetRailMetricsResponse)(nil), // 8: fintech.payment_rail.v1.GetRailMetricsResponse
	(*RailConfig)(nil),             // 9: fintech.payment_rail.v1.RailConfig
	(*RailOption)(nil),             // 10: fintech.payment_rail.v1.RailOption
	(*MetricDataPoint)(nil),        // 11: fintech.payment_rail.v1.MetricDataPoint
	nil,                            // 12: fintech.payment_rail.v1.SelectRailRequest.MetadataEntry
	nil,                            // 13: fintech.payment_rail.v1.RailConfig.ConfigParamsEntry
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_proto_payment_rail_proto_depIdxs = []int32{
	1,  // 0: fintech.payment_rail.v1.SelectRailRequest.priority:type_name -> fintech.payment_rail.v1.SelectionPriority
	0,  // 1: fintech.payment_rail.v1.SelectRailRequest.excluded_rails:type_name -> fintech.payment_rail.v1.PaymentRailType
	12, // 2: fintech.payment_rail.v1.SelectRailRequest.metadata:type_name -> fintech.payment_rail.v1.SelectRailRequest.MetadataEntry
	0,  // 3: fintech.payment_rail.v1.SelectRailResponse.selected_rail:type_name -> fintech.payment_rail.v1.PaymentRailType
	9,  // 4: fintech.payment_rail.v1.SelectRailResponse.rail_config:type_name -> fintech.payment_rail.v1.RailConfig
	10, // 5: fintech.payment_rail.v1.SelectRailResponse.alternatives:type_name -> fintech.payment_rail.v1.RailOption
	14, // 6: fintech.payment_rail.v1.SelectRailResponse.selected_at:type_name -> google.protobuf.Timestamp
	10, // 7: fintech.payment_rail.v1.GetRailsResponse.available_rails:type_name -> fintech.payment_rail.v1.RailOption
	14, // 8: fintech.payment_rail.v1.GetRailsResponse.cached_at:type_name -> google.protobuf.Timestamp
	0,  // 9: fintech.payment_rail.v1.GetRailMetricsRequest.rail_type:type_name -> fintech.payment_rail.v1.PaymentRailType
	0,  // 10: fintech.payment_rail.v1.GetRailMetricsResponse.rail_type:type_name -> fintech.payment_rail.v1.PaymentRailType
	2,  // 11: fintech.payment_rail.v1.GetRailMetricsResponse.current_status:type_name -> fintech.payment_rail.v1.RailStatus
	11, // 12: fintech.payment_rail.v1.GetRailMetricsResponse.metrics:type_name -> fintech.payment_rail.v1.MetricDataPoint
	14, // 13: fintech.payment_rail.v1.GetRailMetricsResponse.metrics_from:type_name -> google.protobuf.Timestamp
	14, // 14: fintech.payment_rail.v1.GetRailMetricsResponse.metrics_to:type_name -> google.protobuf.Timestamp
	0,  // 15: fintech.payment_rail.v1.RailConfig.rail_type:type_name -> fintech.payment_rail.v1.PaymentRailType
	13, // 16: fintech.payment_rail.v1.RailConfig.config_params:type_name -> fintech.payment_rail.v1.RailConfig.ConfigParamsEntry
	0,  // 17: fintech.payment_rail.v1.RailOption.rail_type:type_name -> fintech.payment_rail.v1.PaymentRailType
	2,  // 18: fintech.payment_rail.v1.RailOption.status:type_name -> fintech.payment_rail.v1.RailStatus
	9,  // 19: fintech.payment_rail.v1.RailOption.config:type_name -> fintech.payment_rail.v1.RailConfig
	14, // 20: fintech.payment_rail.v1.MetricDataPoint.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 21: fintech.payment_rail.v1.MetricDataPoint.status:type_name -> fintech.payment_rail.v1.RailStatus
	3,  // 22: fintech.payment_rail.v1.PaymentRailService.SelectPaymentRail:input_type -> fintech.payment_rail.v1.SelectRailRequest
	5,  // 23: fintech.payment_rail.v1.PaymentRailService.GetAvailableRails:input_type -> fintech.payment_rail.v1.GetRailsRequest
	7,  // 24: fintech.payment_rail.v1.PaymentRailService.GetRailMetrics:input_type -> fintech.payment_rail.v1.GetRailMetricsRequest
	4,  // 25: fintech.payment_rail.v1.PaymentRailService.SelectPaymentRail:output_type -> fintech.payment_rail.v1.SelectRailResponse
	6,  // 26: fintech.payment_rail.v1.PaymentRailService.GetAvailableRails:output_type -> fintech.payment_rail.v1.GetRailsResponse
	8,  // 27: fintech.payment_rail.v1.PaymentRailService.GetRailMetrics:output_type -> fintech.payment_rail.v1.GetRailMetricsResponse
	25, // [25:28] is the sub-list for method output_type
	22, // [22:25] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_proto_payment_rail_proto_init() }
func file_proto_payment_rail_proto_init() {
	if File_proto_payment_rail_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_rail_proto_rawDesc), len(file_proto_payment_rail_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_rail_proto_goTypes,
		DependencyIndexes: file_proto_payment_rail_proto_depIdxs,
		EnumInfos:         file_proto_payment_rail_proto_enumTypes,
		MessageInfos:      file_proto_payment_rail_proto_msgTypes,
	}.Build()
	File_proto_payment_rail_proto = out.File
	file_proto_payment_rail_proto_goTypes = nil
	file_proto_payment_rail_proto_depIdxs = nil
}
