// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/payment_rail.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentRailService_SelectPaymentRail_FullMethodName = "/fintech.payment_rail.v1.PaymentRailService/SelectPaymentRail"
	PaymentRailService_GetAvailableRails_FullMethodName = "/fintech.payment_rail.v1.PaymentRailService/GetAvailableRails"
	PaymentRailService_GetRailMetrics_FullMethodName    = "/fintech.payment_rail.v1.PaymentRailService/GetRailMetrics"
)

// PaymentRailServiceClient is the client API for PaymentRailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentRailService - Select optimal payment rail for transactions
type PaymentRailServiceClient interface {
	// Select optimal payment rail for a transaction
	SelectPaymentRail(ctx context.Context, in *SelectRailRequest, opts ...grpc.CallOption) (*SelectRailResponse, error)
	// Get available rails for a route
	GetAvailableRails(ctx context.Context, in *GetRailsRequest, opts ...grpc.CallOption) (*GetRailsResponse, error)
	// Get rail performance metrics
	GetRailMetrics(ctx context.Context, in *GetRailMetricsRequest, opts ...grpc.CallOption) (*GetRailMetricsResponse, error)
}

type paymentRailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentRailServiceClient(cc grpc.ClientConnInterface) PaymentRailServiceClient {
	return &paymentRailServiceClient{cc}
}

func (c *paymentRailServiceClient) SelectPaymentRail(ctx context.Context, in *SelectRailRequest, opts ...grpc.CallOption) (*SelectRailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelectRailResponse)
	err := c.cc.Invoke(ctx, PaymentRailService_SelectPaymentRail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentRailServiceClient) GetAvailableRails(ctx context.Context, in *GetRailsRequest, opts ...grpc.CallOption) (*GetRailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRailsResponse)
	err := c.cc.Invoke(ctx, PaymentRailService_GetAvailableRails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentRailServiceClient) GetRailMetrics(ctx context.Context, in *GetRailMetricsRequest, opts ...grpc.CallOption) (*GetRailMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRailMetricsResponse)
	err := c.cc.Invoke(ctx, PaymentRailService_GetRailMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentRailServiceServer is the server API for PaymentRailService service.
// All implementations must embed UnimplementedPaymentRailServiceServer
// for forward compatibility.
//
// PaymentRailService - Select optimal payment rail for transactions
type PaymentRailServiceServer interface {
	// Select optimal payment rail for a transaction
	SelectPaymentRail(context.Context, *SelectRailRequest) (*SelectRailResponse, error)
	// Get available rails for a route
	GetAvailableRails(context.Context, *GetRailsRequest) (*GetRailsResponse, error)
	// Get rail performance metrics
	GetRailMetrics(context.Context, *GetRailMetricsRequest) (*GetRailMetricsResponse, error)
	mustEmbedUnimplementedPaymentRailServiceServer()
}

// UnimplementedPaymentRailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentRailServiceServer struct{}

func (UnimplementedPaymentRailServiceServer) SelectPaymentRail(context.Context, *SelectRailRequest) (*SelectRailResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SelectPaymentRail not implemented")
}
func (UnimplementedPaymentRailServiceServer) GetAvailableRails(context.Context, *GetRailsRequest) (*GetRailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableRails not implemented")
}
func (UnimplementedPaymentRailServiceServer) GetRailMetrics(context.Context, *GetRailMetricsRequest) (*GetRailMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRailMetrics not implemented")
}
func (UnimplementedPaymentRailServiceServer) mustEmbedUnimplementedPaymentRailServiceServer() {}
func (UnimplementedPaymentRailServiceServer) testEmbeddedByValue()                            {}

// UnsafePaymentRailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentRailServiceServer will
// result in compilation errors.
type UnsafePaymentRailServiceServer interface {
	mustEmbedUnimplementedPaymentRailServiceServer()
}

func RegisterPaymentRailServiceServer(s grpc.ServiceRegistrar, srv PaymentRailServiceServer) {
	// If the following call pancis, it indicates UnimplementedPaymentRailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentRailService_ServiceDesc, srv)
}

func _PaymentRailService_SelectPaymentRail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelectRailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRailServiceServer).SelectPaymentRail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRailService_SelectPaymentRail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRailServiceServer).SelectPaymentRail(ctx, req.(*SelectRailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentRailService_GetAvailableRails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRailServiceServer).GetAvailableRails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRailService_GetAvailableRails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRailServiceServer).GetAvailableRails(ctx, req.(*GetRailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentRailService_GetRailMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRailMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentRailServiceServer).GetRailMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentRailService_GetRailMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentRailServiceServer).GetRailMetrics(ctx, req.(*GetRailMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentRailService_ServiceDesc is the grpc.ServiceDesc for PaymentRailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentRailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fintech.payment_rail.v1.PaymentRailService",
	HandlerType: (*PaymentRailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelectPaymentRail",
			Handler:    _PaymentRailService_SelectPaymentRail_Handler,
		},
		{
			MethodName: "GetAvailableRails",
			Handler:    _PaymentRailService_GetAvailableRails_Handler,
		},
		{
			MethodName: "GetRailMetrics",
			Handler:    _PaymentRailService_GetRailMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment_rail.proto",
}
