// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/reconciliation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Reconciliation status enum
type ReconciliationStatus int32

const (
	ReconciliationStatus_RECONCILIATION_STATUS_UNSPECIFIED     ReconciliationStatus = 0
	ReconciliationStatus_RECONCILIATION_STATUS_PENDING         ReconciliationStatus = 1
	ReconciliationStatus_RECONCILIATION_STATUS_IN_PROGRESS     ReconciliationStatus = 2
	ReconciliationStatus_RECONCILIATION_STATUS_COMPLETED       ReconciliationStatus = 3
	ReconciliationStatus_RECONCILIATION_STATUS_FAILED          ReconciliationStatus = 4
	ReconciliationStatus_RECONCILIATION_STATUS_REQUIRES_REVIEW ReconciliationStatus = 5
)

// Enum value maps for ReconciliationStatus.
var (
	ReconciliationStatus_name = map[int32]string{
		0: "RECONCILIATION_STATUS_UNSPECIFIED",
		1: "RECONCILIATION_STATUS_PENDING",
		2: "RECONCILIATION_STATUS_IN_PROGRESS",
		3: "RECONCILIATION_STATUS_COMPLETED",
		4: "RECONCILIATION_STATUS_FAILED",
		5: "RECONCILIATION_STATUS_REQUIRES_REVIEW",
	}
	ReconciliationStatus_value = map[string]int32{
		"RECONCILIATION_STATUS_UNSPECIFIED":     0,
		"RECONCILIATION_STATUS_PENDING":         1,
		"RECONCILIATION_STATUS_IN_PROGRESS":     2,
		"RECONCILIATION_STATUS_COMPLETED":       3,
		"RECONCILIATION_STATUS_FAILED":          4,
		"RECONCILIATION_STATUS_REQUIRES_REVIEW": 5,
	}
)

func (x ReconciliationStatus) Enum() *ReconciliationStatus {
	p := new(ReconciliationStatus)
	*p = x
	return p
}

func (x ReconciliationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReconciliationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reconciliation_proto_enumTypes[0].Descriptor()
}

func (ReconciliationStatus) Type() protoreflect.EnumType {
	return &file_proto_reconciliation_proto_enumTypes[0]
}

func (x ReconciliationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReconciliationStatus.Descriptor instead.
func (ReconciliationStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{0}
}

// Variance type enum
type VarianceType int32

const (
	VarianceType_VARIANCE_TYPE_UNSPECIFIED      VarianceType = 0
	VarianceType_VARIANCE_TYPE_MISSING_INTERNAL VarianceType = 1 // Internal transaction missing
	VarianceType_VARIANCE_TYPE_MISSING_EXTERNAL VarianceType = 2 // External transaction missing
	VarianceType_VARIANCE_TYPE_AMOUNT_MISMATCH  VarianceType = 3 // Amount difference
	VarianceType_VARIANCE_TYPE_DATE_MISMATCH    VarianceType = 4 // Date difference
	VarianceType_VARIANCE_TYPE_DUPLICATE        VarianceType = 5 // Duplicate transaction
)

// Enum value maps for VarianceType.
var (
	VarianceType_name = map[int32]string{
		0: "VARIANCE_TYPE_UNSPECIFIED",
		1: "VARIANCE_TYPE_MISSING_INTERNAL",
		2: "VARIANCE_TYPE_MISSING_EXTERNAL",
		3: "VARIANCE_TYPE_AMOUNT_MISMATCH",
		4: "VARIANCE_TYPE_DATE_MISMATCH",
		5: "VARIANCE_TYPE_DUPLICATE",
	}
	VarianceType_value = map[string]int32{
		"VARIANCE_TYPE_UNSPECIFIED":      0,
		"VARIANCE_TYPE_MISSING_INTERNAL": 1,
		"VARIANCE_TYPE_MISSING_EXTERNAL": 2,
		"VARIANCE_TYPE_AMOUNT_MISMATCH":  3,
		"VARIANCE_TYPE_DATE_MISMATCH":    4,
		"VARIANCE_TYPE_DUPLICATE":        5,
	}
)

func (x VarianceType) Enum() *VarianceType {
	p := new(VarianceType)
	*p = x
	return p
}

func (x VarianceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VarianceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reconciliation_proto_enumTypes[1].Descriptor()
}

func (VarianceType) Type() protoreflect.EnumType {
	return &file_proto_reconciliation_proto_enumTypes[1]
}

func (x VarianceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VarianceType.Descriptor instead.
func (VarianceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{1}
}

// Action type enum
type ActionType int32

const (
	ActionType_ACTION_TYPE_UNSPECIFIED ActionType = 0
	ActionType_ACTION_TYPE_ACCEPT      ActionType = 1 // Accept variance as valid
	ActionType_ACTION_TYPE_REJECT      ActionType = 2 // Reject and investigate
	ActionType_ACTION_TYPE_ADJUST      ActionType = 3 // Make adjustment entry
	ActionType_ACTION_TYPE_IGNORE      ActionType = 4 // Ignore for this period
	ActionType_ACTION_TYPE_ESCALATE    ActionType = 5 // Escalate to supervisor
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_TYPE_UNSPECIFIED",
		1: "ACTION_TYPE_ACCEPT",
		2: "ACTION_TYPE_REJECT",
		3: "ACTION_TYPE_ADJUST",
		4: "ACTION_TYPE_IGNORE",
		5: "ACTION_TYPE_ESCALATE",
	}
	ActionType_value = map[string]int32{
		"ACTION_TYPE_UNSPECIFIED": 0,
		"ACTION_TYPE_ACCEPT":      1,
		"ACTION_TYPE_REJECT":      2,
		"ACTION_TYPE_ADJUST":      3,
		"ACTION_TYPE_IGNORE":      4,
		"ACTION_TYPE_ESCALATE":    5,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reconciliation_proto_enumTypes[2].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_proto_reconciliation_proto_enumTypes[2]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{2}
}

// Reconciliation report
type ReconciliationReport struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	ReportId                  string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	DateRangeStart            string                 `protobuf:"bytes,2,opt,name=date_range_start,json=dateRangeStart,proto3" json:"date_range_start,omitempty"` // YYYY-MM-DD
	DateRangeEnd              string                 `protobuf:"bytes,3,opt,name=date_range_end,json=dateRangeEnd,proto3" json:"date_range_end,omitempty"`       // YYYY-MM-DD
	Status                    ReconciliationStatus   `protobuf:"varint,4,opt,name=status,proto3,enum=fintech.reconciliation.v1.ReconciliationStatus" json:"status,omitempty"`
	TotalInternalTransactions int32                  `protobuf:"varint,5,opt,name=total_internal_transactions,json=totalInternalTransactions,proto3" json:"total_internal_transactions,omitempty"`
	TotalExternalTransactions int32                  `protobuf:"varint,6,opt,name=total_external_transactions,json=totalExternalTransactions,proto3" json:"total_external_transactions,omitempty"`
	TotalInternalAmount       float64                `protobuf:"fixed64,7,opt,name=total_internal_amount,json=totalInternalAmount,proto3" json:"total_internal_amount,omitempty"`
	TotalExternalAmount       float64                `protobuf:"fixed64,8,opt,name=total_external_amount,json=totalExternalAmount,proto3" json:"total_external_amount,omitempty"`
	MatchedTransactions       int32                  `protobuf:"varint,9,opt,name=matched_transactions,json=matchedTransactions,proto3" json:"matched_transactions,omitempty"`
	UnmatchedInternal         int32                  `protobuf:"varint,10,opt,name=unmatched_internal,json=unmatchedInternal,proto3" json:"unmatched_internal,omitempty"`
	UnmatchedExternal         int32                  `protobuf:"varint,11,opt,name=unmatched_external,json=unmatchedExternal,proto3" json:"unmatched_external,omitempty"`
	Variances                 []*Variance            `protobuf:"bytes,12,rep,name=variances,proto3" json:"variances,omitempty"`
	GeneratedAt               *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	CompletedAt               *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ReconciledBy              string                 `protobuf:"bytes,15,opt,name=reconciled_by,json=reconciledBy,proto3" json:"reconciled_by,omitempty"` // User ID who completed reconciliation
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ReconciliationReport) Reset() {
	*x = ReconciliationReport{}
	mi := &file_proto_reconciliation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationReport) ProtoMessage() {}

func (x *ReconciliationReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationReport.ProtoReflect.Descriptor instead.
func (*ReconciliationReport) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{0}
}

func (x *ReconciliationReport) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ReconciliationReport) GetDateRangeStart() string {
	if x != nil {
		return x.DateRangeStart
	}
	return ""
}

func (x *ReconciliationReport) GetDateRangeEnd() string {
	if x != nil {
		return x.DateRangeEnd
	}
	return ""
}

func (x *ReconciliationReport) GetStatus() ReconciliationStatus {
	if x != nil {
		return x.Status
	}
	return ReconciliationStatus_RECONCILIATION_STATUS_UNSPECIFIED
}

func (x *ReconciliationReport) GetTotalInternalTransactions() int32 {
	if x != nil {
		return x.TotalInternalTransactions
	}
	return 0
}

func (x *ReconciliationReport) GetTotalExternalTransactions() int32 {
	if x != nil {
		return x.TotalExternalTransactions
	}
	return 0
}

func (x *ReconciliationReport) GetTotalInternalAmount() float64 {
	if x != nil {
		return x.TotalInternalAmount
	}
	return 0
}

func (x *ReconciliationReport) GetTotalExternalAmount() float64 {
	if x != nil {
		return x.TotalExternalAmount
	}
	return 0
}

func (x *ReconciliationReport) GetMatchedTransactions() int32 {
	if x != nil {
		return x.MatchedTransactions
	}
	return 0
}

func (x *ReconciliationReport) GetUnmatchedInternal() int32 {
	if x != nil {
		return x.UnmatchedInternal
	}
	return 0
}

func (x *ReconciliationReport) GetUnmatchedExternal() int32 {
	if x != nil {
		return x.UnmatchedExternal
	}
	return 0
}

func (x *ReconciliationReport) GetVariances() []*Variance {
	if x != nil {
		return x.Variances
	}
	return nil
}

func (x *ReconciliationReport) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *ReconciliationReport) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *ReconciliationReport) GetReconciledBy() string {
	if x != nil {
		return x.ReconciledBy
	}
	return ""
}

// Individual variance/discrepancy
type Variance struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	VarianceId            string                 `protobuf:"bytes,1,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"`
	Type                  VarianceType           `protobuf:"varint,2,opt,name=type,proto3,enum=fintech.reconciliation.v1.VarianceType" json:"type,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	InternalTransactionId string                 `protobuf:"bytes,4,opt,name=internal_transaction_id,json=internalTransactionId,proto3" json:"internal_transaction_id,omitempty"` // Optional
	ExternalTransactionId string                 `protobuf:"bytes,5,opt,name=external_transaction_id,json=externalTransactionId,proto3" json:"external_transaction_id,omitempty"` // Optional
	InternalAmount        float64                `protobuf:"fixed64,6,opt,name=internal_amount,json=internalAmount,proto3" json:"internal_amount,omitempty"`
	ExternalAmount        float64                `protobuf:"fixed64,7,opt,name=external_amount,json=externalAmount,proto3" json:"external_amount,omitempty"`
	VarianceAmount        float64                `protobuf:"fixed64,8,opt,name=variance_amount,json=varianceAmount,proto3" json:"variance_amount,omitempty"` // Difference
	Currency              string                 `protobuf:"bytes,9,opt,name=currency,proto3" json:"currency,omitempty"`
	InternalDate          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=internal_date,json=internalDate,proto3" json:"internal_date,omitempty"`
	ExternalDate          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=external_date,json=externalDate,proto3" json:"external_date,omitempty"`
	SuggestedAction       string                 `protobuf:"bytes,12,opt,name=suggested_action,json=suggestedAction,proto3" json:"suggested_action,omitempty"`
	Notes                 string                 `protobuf:"bytes,13,opt,name=notes,proto3" json:"notes,omitempty"`
	RequiresApproval      bool                   `protobuf:"varint,14,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	AssignedTo            string                 `protobuf:"bytes,15,opt,name=assigned_to,json=assignedTo,proto3" json:"assigned_to,omitempty"` // User ID
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Variance) Reset() {
	*x = Variance{}
	mi := &file_proto_reconciliation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variance) ProtoMessage() {}

func (x *Variance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variance.ProtoReflect.Descriptor instead.
func (*Variance) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{1}
}

func (x *Variance) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

func (x *Variance) GetType() VarianceType {
	if x != nil {
		return x.Type
	}
	return VarianceType_VARIANCE_TYPE_UNSPECIFIED
}

func (x *Variance) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Variance) GetInternalTransactionId() string {
	if x != nil {
		return x.InternalTransactionId
	}
	return ""
}

func (x *Variance) GetExternalTransactionId() string {
	if x != nil {
		return x.ExternalTransactionId
	}
	return ""
}

func (x *Variance) GetInternalAmount() float64 {
	if x != nil {
		return x.InternalAmount
	}
	return 0
}

func (x *Variance) GetExternalAmount() float64 {
	if x != nil {
		return x.ExternalAmount
	}
	return 0
}

func (x *Variance) GetVarianceAmount() float64 {
	if x != nil {
		return x.VarianceAmount
	}
	return 0
}

func (x *Variance) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Variance) GetInternalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.InternalDate
	}
	return nil
}

func (x *Variance) GetExternalDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExternalDate
	}
	return nil
}

func (x *Variance) GetSuggestedAction() string {
	if x != nil {
		return x.SuggestedAction
	}
	return ""
}

func (x *Variance) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Variance) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

func (x *Variance) GetAssignedTo() string {
	if x != nil {
		return x.AssignedTo
	}
	return ""
}

// Bidirectional streaming messages for InteractiveReconciliation
type ReconAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Action:
	//
	//	*ReconAction_StartReconciliation
	//	*ReconAction_ProcessVariance
	//	*ReconAction_ApprovalRequest
	//	*ReconAction_GetProgress
	//	*ReconAction_CompleteReconciliation
	Action        isReconAction_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconAction) Reset() {
	*x = ReconAction{}
	mi := &file_proto_reconciliation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconAction) ProtoMessage() {}

func (x *ReconAction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconAction.ProtoReflect.Descriptor instead.
func (*ReconAction) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{2}
}

func (x *ReconAction) GetAction() isReconAction_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *ReconAction) GetStartReconciliation() *StartReconciliation {
	if x != nil {
		if x, ok := x.Action.(*ReconAction_StartReconciliation); ok {
			return x.StartReconciliation
		}
	}
	return nil
}

func (x *ReconAction) GetProcessVariance() *ProcessVariance {
	if x != nil {
		if x, ok := x.Action.(*ReconAction_ProcessVariance); ok {
			return x.ProcessVariance
		}
	}
	return nil
}

func (x *ReconAction) GetApprovalRequest() *ApprovalRequest {
	if x != nil {
		if x, ok := x.Action.(*ReconAction_ApprovalRequest); ok {
			return x.ApprovalRequest
		}
	}
	return nil
}

func (x *ReconAction) GetGetProgress() *GetProgress {
	if x != nil {
		if x, ok := x.Action.(*ReconAction_GetProgress); ok {
			return x.GetProgress
		}
	}
	return nil
}

func (x *ReconAction) GetCompleteReconciliation() *CompleteReconciliation {
	if x != nil {
		if x, ok := x.Action.(*ReconAction_CompleteReconciliation); ok {
			return x.CompleteReconciliation
		}
	}
	return nil
}

type isReconAction_Action interface {
	isReconAction_Action()
}

type ReconAction_StartReconciliation struct {
	StartReconciliation *StartReconciliation `protobuf:"bytes,1,opt,name=start_reconciliation,json=startReconciliation,proto3,oneof"`
}

type ReconAction_ProcessVariance struct {
	ProcessVariance *ProcessVariance `protobuf:"bytes,2,opt,name=process_variance,json=processVariance,proto3,oneof"`
}

type ReconAction_ApprovalRequest struct {
	ApprovalRequest *ApprovalRequest `protobuf:"bytes,3,opt,name=approval_request,json=approvalRequest,proto3,oneof"`
}

type ReconAction_GetProgress struct {
	GetProgress *GetProgress `protobuf:"bytes,4,opt,name=get_progress,json=getProgress,proto3,oneof"`
}

type ReconAction_CompleteReconciliation struct {
	CompleteReconciliation *CompleteReconciliation `protobuf:"bytes,5,opt,name=complete_reconciliation,json=completeReconciliation,proto3,oneof"`
}

func (*ReconAction_StartReconciliation) isReconAction_Action() {}

func (*ReconAction_ProcessVariance) isReconAction_Action() {}

func (*ReconAction_ApprovalRequest) isReconAction_Action() {}

func (*ReconAction_GetProgress) isReconAction_Action() {}

func (*ReconAction_CompleteReconciliation) isReconAction_Action() {}

type StartReconciliation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DateRangeStart   string                 `protobuf:"bytes,1,opt,name=date_range_start,json=dateRangeStart,proto3" json:"date_range_start,omitempty"`
	DateRangeEnd     string                 `protobuf:"bytes,2,opt,name=date_range_end,json=dateRangeEnd,proto3" json:"date_range_end,omitempty"`
	AccountFilter    []string               `protobuf:"bytes,3,rep,name=account_filter,json=accountFilter,proto3" json:"account_filter,omitempty"` // Optional: specific accounts
	AutoMatchEnabled bool                   `protobuf:"varint,4,opt,name=auto_match_enabled,json=autoMatchEnabled,proto3" json:"auto_match_enabled,omitempty"`
	ToleranceAmount  float64                `protobuf:"fixed64,5,opt,name=tolerance_amount,json=toleranceAmount,proto3" json:"tolerance_amount,omitempty"` // Auto-match tolerance
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StartReconciliation) Reset() {
	*x = StartReconciliation{}
	mi := &file_proto_reconciliation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartReconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartReconciliation) ProtoMessage() {}

func (x *StartReconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartReconciliation.ProtoReflect.Descriptor instead.
func (*StartReconciliation) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{3}
}

func (x *StartReconciliation) GetDateRangeStart() string {
	if x != nil {
		return x.DateRangeStart
	}
	return ""
}

func (x *StartReconciliation) GetDateRangeEnd() string {
	if x != nil {
		return x.DateRangeEnd
	}
	return ""
}

func (x *StartReconciliation) GetAccountFilter() []string {
	if x != nil {
		return x.AccountFilter
	}
	return nil
}

func (x *StartReconciliation) GetAutoMatchEnabled() bool {
	if x != nil {
		return x.AutoMatchEnabled
	}
	return false
}

func (x *StartReconciliation) GetToleranceAmount() float64 {
	if x != nil {
		return x.ToleranceAmount
	}
	return 0
}

type ProcessVariance struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VarianceId       string                 `protobuf:"bytes,1,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"`
	Action           ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=fintech.reconciliation.v1.ActionType" json:"action,omitempty"`
	Notes            string                 `protobuf:"bytes,3,opt,name=notes,proto3" json:"notes,omitempty"`
	AdjustmentAmount float64                `protobuf:"fixed64,4,opt,name=adjustment_amount,json=adjustmentAmount,proto3" json:"adjustment_amount,omitempty"` // For ACTION_TYPE_ADJUST
	AdjustmentReason string                 `protobuf:"bytes,5,opt,name=adjustment_reason,json=adjustmentReason,proto3" json:"adjustment_reason,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessVariance) Reset() {
	*x = ProcessVariance{}
	mi := &file_proto_reconciliation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVariance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVariance) ProtoMessage() {}

func (x *ProcessVariance) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVariance.ProtoReflect.Descriptor instead.
func (*ProcessVariance) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessVariance) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

func (x *ProcessVariance) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *ProcessVariance) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *ProcessVariance) GetAdjustmentAmount() float64 {
	if x != nil {
		return x.AdjustmentAmount
	}
	return 0
}

func (x *ProcessVariance) GetAdjustmentReason() string {
	if x != nil {
		return x.AdjustmentReason
	}
	return ""
}

type ApprovalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarianceId    string                 `protobuf:"bytes,1,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Approved      bool                   `protobuf:"varint,3,opt,name=approved,proto3" json:"approved,omitempty"`
	ApprovalNotes string                 `protobuf:"bytes,4,opt,name=approval_notes,json=approvalNotes,proto3" json:"approval_notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalRequest) Reset() {
	*x = ApprovalRequest{}
	mi := &file_proto_reconciliation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalRequest) ProtoMessage() {}

func (x *ApprovalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalRequest.ProtoReflect.Descriptor instead.
func (*ApprovalRequest) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{5}
}

func (x *ApprovalRequest) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

func (x *ApprovalRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApprovalRequest) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalRequest) GetApprovalNotes() string {
	if x != nil {
		return x.ApprovalNotes
	}
	return ""
}

type GetProgress struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeDetails bool                   `protobuf:"varint,1,opt,name=include_details,json=includeDetails,proto3" json:"include_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetProgress) Reset() {
	*x = GetProgress{}
	mi := &file_proto_reconciliation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgress) ProtoMessage() {}

func (x *GetProgress) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgress.ProtoReflect.Descriptor instead.
func (*GetProgress) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{6}
}

func (x *GetProgress) GetIncludeDetails() bool {
	if x != nil {
		return x.IncludeDetails
	}
	return false
}

type CompleteReconciliation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FinalNotes    string                 `protobuf:"bytes,1,opt,name=final_notes,json=finalNotes,proto3" json:"final_notes,omitempty"`
	ForceComplete bool                   `protobuf:"varint,2,opt,name=force_complete,json=forceComplete,proto3" json:"force_complete,omitempty"` // Complete even with unresolved variances
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteReconciliation) Reset() {
	*x = CompleteReconciliation{}
	mi := &file_proto_reconciliation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteReconciliation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteReconciliation) ProtoMessage() {}

func (x *CompleteReconciliation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteReconciliation.ProtoReflect.Descriptor instead.
func (*CompleteReconciliation) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteReconciliation) GetFinalNotes() string {
	if x != nil {
		return x.FinalNotes
	}
	return ""
}

func (x *CompleteReconciliation) GetForceComplete() bool {
	if x != nil {
		return x.ForceComplete
	}
	return false
}

type ReconResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ReconResult_ReconciliationStarted
	//	*ReconResult_VarianceDetected
	//	*ReconResult_VarianceProcessed
	//	*ReconResult_ApprovalResponse
	//	*ReconResult_ProgressUpdate
	//	*ReconResult_ReconciliationCompleted
	//	*ReconResult_ReconError
	Result        isReconResult_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconResult) Reset() {
	*x = ReconResult{}
	mi := &file_proto_reconciliation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconResult) ProtoMessage() {}

func (x *ReconResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconResult.ProtoReflect.Descriptor instead.
func (*ReconResult) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{8}
}

func (x *ReconResult) GetResult() isReconResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ReconResult) GetReconciliationStarted() *ReconciliationStarted {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_ReconciliationStarted); ok {
			return x.ReconciliationStarted
		}
	}
	return nil
}

func (x *ReconResult) GetVarianceDetected() *VarianceDetected {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_VarianceDetected); ok {
			return x.VarianceDetected
		}
	}
	return nil
}

func (x *ReconResult) GetVarianceProcessed() *VarianceProcessed {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_VarianceProcessed); ok {
			return x.VarianceProcessed
		}
	}
	return nil
}

func (x *ReconResult) GetApprovalResponse() *ApprovalResponse {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_ApprovalResponse); ok {
			return x.ApprovalResponse
		}
	}
	return nil
}

func (x *ReconResult) GetProgressUpdate() *ProgressUpdate {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_ProgressUpdate); ok {
			return x.ProgressUpdate
		}
	}
	return nil
}

func (x *ReconResult) GetReconciliationCompleted() *ReconciliationCompleted {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_ReconciliationCompleted); ok {
			return x.ReconciliationCompleted
		}
	}
	return nil
}

func (x *ReconResult) GetReconError() *ReconError {
	if x != nil {
		if x, ok := x.Result.(*ReconResult_ReconError); ok {
			return x.ReconError
		}
	}
	return nil
}

type isReconResult_Result interface {
	isReconResult_Result()
}

type ReconResult_ReconciliationStarted struct {
	ReconciliationStarted *ReconciliationStarted `protobuf:"bytes,1,opt,name=reconciliation_started,json=reconciliationStarted,proto3,oneof"`
}

type ReconResult_VarianceDetected struct {
	VarianceDetected *VarianceDetected `protobuf:"bytes,2,opt,name=variance_detected,json=varianceDetected,proto3,oneof"`
}

type ReconResult_VarianceProcessed struct {
	VarianceProcessed *VarianceProcessed `protobuf:"bytes,3,opt,name=variance_processed,json=varianceProcessed,proto3,oneof"`
}

type ReconResult_ApprovalResponse struct {
	ApprovalResponse *ApprovalResponse `protobuf:"bytes,4,opt,name=approval_response,json=approvalResponse,proto3,oneof"`
}

type ReconResult_ProgressUpdate struct {
	ProgressUpdate *ProgressUpdate `protobuf:"bytes,5,opt,name=progress_update,json=progressUpdate,proto3,oneof"`
}

type ReconResult_ReconciliationCompleted struct {
	ReconciliationCompleted *ReconciliationCompleted `protobuf:"bytes,6,opt,name=reconciliation_completed,json=reconciliationCompleted,proto3,oneof"`
}

type ReconResult_ReconError struct {
	ReconError *ReconError `protobuf:"bytes,7,opt,name=recon_error,json=reconError,proto3,oneof"`
}

func (*ReconResult_ReconciliationStarted) isReconResult_Result() {}

func (*ReconResult_VarianceDetected) isReconResult_Result() {}

func (*ReconResult_VarianceProcessed) isReconResult_Result() {}

func (*ReconResult_ApprovalResponse) isReconResult_Result() {}

func (*ReconResult_ProgressUpdate) isReconResult_Result() {}

func (*ReconResult_ReconciliationCompleted) isReconResult_Result() {}

func (*ReconResult_ReconError) isReconResult_Result() {}

type ReconciliationStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InitialReport *ReconciliationReport  `protobuf:"bytes,2,opt,name=initial_report,json=initialReport,proto3" json:"initial_report,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconciliationStarted) Reset() {
	*x = ReconciliationStarted{}
	mi := &file_proto_reconciliation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationStarted) ProtoMessage() {}

func (x *ReconciliationStarted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationStarted.ProtoReflect.Descriptor instead.
func (*ReconciliationStarted) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{9}
}

func (x *ReconciliationStarted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReconciliationStarted) GetInitialReport() *ReconciliationReport {
	if x != nil {
		return x.InitialReport
	}
	return nil
}

func (x *ReconciliationStarted) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type VarianceDetected struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Variance         *Variance              `protobuf:"bytes,1,opt,name=variance,proto3" json:"variance,omitempty"`
	Severity         string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"` // "low", "medium", "high", "critical"
	SuggestedActions []string               `protobuf:"bytes,3,rep,name=suggested_actions,json=suggestedActions,proto3" json:"suggested_actions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VarianceDetected) Reset() {
	*x = VarianceDetected{}
	mi := &file_proto_reconciliation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarianceDetected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarianceDetected) ProtoMessage() {}

func (x *VarianceDetected) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarianceDetected.ProtoReflect.Descriptor instead.
func (*VarianceDetected) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{10}
}

func (x *VarianceDetected) GetVariance() *Variance {
	if x != nil {
		return x.Variance
	}
	return nil
}

func (x *VarianceDetected) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *VarianceDetected) GetSuggestedActions() []string {
	if x != nil {
		return x.SuggestedActions
	}
	return nil
}

type VarianceProcessed struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	VarianceId       string                 `protobuf:"bytes,1,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"`
	ActionTaken      ActionType             `protobuf:"varint,2,opt,name=action_taken,json=actionTaken,proto3,enum=fintech.reconciliation.v1.ActionType" json:"action_taken,omitempty"`
	Success          bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	RequiresApproval bool                   `protobuf:"varint,5,opt,name=requires_approval,json=requiresApproval,proto3" json:"requires_approval,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *VarianceProcessed) Reset() {
	*x = VarianceProcessed{}
	mi := &file_proto_reconciliation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VarianceProcessed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VarianceProcessed) ProtoMessage() {}

func (x *VarianceProcessed) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VarianceProcessed.ProtoReflect.Descriptor instead.
func (*VarianceProcessed) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{11}
}

func (x *VarianceProcessed) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

func (x *VarianceProcessed) GetActionTaken() ActionType {
	if x != nil {
		return x.ActionTaken
	}
	return ActionType_ACTION_TYPE_UNSPECIFIED
}

func (x *VarianceProcessed) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VarianceProcessed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *VarianceProcessed) GetRequiresApproval() bool {
	if x != nil {
		return x.RequiresApproval
	}
	return false
}

type ApprovalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VarianceId    string                 `protobuf:"bytes,1,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"`
	Approved      bool                   `protobuf:"varint,2,opt,name=approved,proto3" json:"approved,omitempty"`
	ApproverId    string                 `protobuf:"bytes,3,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovalResponse) Reset() {
	*x = ApprovalResponse{}
	mi := &file_proto_reconciliation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovalResponse) ProtoMessage() {}

func (x *ApprovalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovalResponse.ProtoReflect.Descriptor instead.
func (*ApprovalResponse) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{12}
}

func (x *ApprovalResponse) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

func (x *ApprovalResponse) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ApprovalResponse) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *ApprovalResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ProgressUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SessionId            string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TotalVariances       int32                  `protobuf:"varint,2,opt,name=total_variances,json=totalVariances,proto3" json:"total_variances,omitempty"`
	ProcessedVariances   int32                  `protobuf:"varint,3,opt,name=processed_variances,json=processedVariances,proto3" json:"processed_variances,omitempty"`
	PendingApproval      int32                  `protobuf:"varint,4,opt,name=pending_approval,json=pendingApproval,proto3" json:"pending_approval,omitempty"`
	UnresolvedVariances  int32                  `protobuf:"varint,5,opt,name=unresolved_variances,json=unresolvedVariances,proto3" json:"unresolved_variances,omitempty"`
	CompletionPercentage float64                `protobuf:"fixed64,6,opt,name=completion_percentage,json=completionPercentage,proto3" json:"completion_percentage,omitempty"`
	CurrentStatus        string                 `protobuf:"bytes,7,opt,name=current_status,json=currentStatus,proto3" json:"current_status,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ProgressUpdate) Reset() {
	*x = ProgressUpdate{}
	mi := &file_proto_reconciliation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgressUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgressUpdate) ProtoMessage() {}

func (x *ProgressUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgressUpdate.ProtoReflect.Descriptor instead.
func (*ProgressUpdate) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{13}
}

func (x *ProgressUpdate) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ProgressUpdate) GetTotalVariances() int32 {
	if x != nil {
		return x.TotalVariances
	}
	return 0
}

func (x *ProgressUpdate) GetProcessedVariances() int32 {
	if x != nil {
		return x.ProcessedVariances
	}
	return 0
}

func (x *ProgressUpdate) GetPendingApproval() int32 {
	if x != nil {
		return x.PendingApproval
	}
	return 0
}

func (x *ProgressUpdate) GetUnresolvedVariances() int32 {
	if x != nil {
		return x.UnresolvedVariances
	}
	return 0
}

func (x *ProgressUpdate) GetCompletionPercentage() float64 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

func (x *ProgressUpdate) GetCurrentStatus() string {
	if x != nil {
		return x.CurrentStatus
	}
	return ""
}

type ReconciliationCompleted struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SessionId         string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FinalReport       *ReconciliationReport  `protobuf:"bytes,2,opt,name=final_report,json=finalReport,proto3" json:"final_report,omitempty"`
	CompletionMessage string                 `protobuf:"bytes,3,opt,name=completion_message,json=completionMessage,proto3" json:"completion_message,omitempty"`
	CompletedAt       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconciliationCompleted) Reset() {
	*x = ReconciliationCompleted{}
	mi := &file_proto_reconciliation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconciliationCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconciliationCompleted) ProtoMessage() {}

func (x *ReconciliationCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconciliationCompleted.ProtoReflect.Descriptor instead.
func (*ReconciliationCompleted) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{14}
}

func (x *ReconciliationCompleted) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ReconciliationCompleted) GetFinalReport() *ReconciliationReport {
	if x != nil {
		return x.FinalReport
	}
	return nil
}

func (x *ReconciliationCompleted) GetCompletionMessage() string {
	if x != nil {
		return x.CompletionMessage
	}
	return ""
}

func (x *ReconciliationCompleted) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type ReconError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorCode     string                 `protobuf:"bytes,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	VarianceId    string                 `protobuf:"bytes,3,opt,name=variance_id,json=varianceId,proto3" json:"variance_id,omitempty"` // Optional: if error relates to specific variance
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconError) Reset() {
	*x = ReconError{}
	mi := &file_proto_reconciliation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconError) ProtoMessage() {}

func (x *ReconError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconError.ProtoReflect.Descriptor instead.
func (*ReconError) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{15}
}

func (x *ReconError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ReconError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReconError) GetVarianceId() string {
	if x != nil {
		return x.VarianceId
	}
	return ""
}

// Standard request/response messages
type GenerateReconciliationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DateRangeStart   string                 `protobuf:"bytes,1,opt,name=date_range_start,json=dateRangeStart,proto3" json:"date_range_start,omitempty"`
	DateRangeEnd     string                 `protobuf:"bytes,2,opt,name=date_range_end,json=dateRangeEnd,proto3" json:"date_range_end,omitempty"`
	AccountFilter    []string               `protobuf:"bytes,3,rep,name=account_filter,json=accountFilter,proto3" json:"account_filter,omitempty"`
	AutoMatchEnabled bool                   `protobuf:"varint,4,opt,name=auto_match_enabled,json=autoMatchEnabled,proto3" json:"auto_match_enabled,omitempty"`
	ToleranceAmount  float64                `protobuf:"fixed64,5,opt,name=tolerance_amount,json=toleranceAmount,proto3" json:"tolerance_amount,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GenerateReconciliationRequest) Reset() {
	*x = GenerateReconciliationRequest{}
	mi := &file_proto_reconciliation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReconciliationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReconciliationRequest) ProtoMessage() {}

func (x *GenerateReconciliationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReconciliationRequest.ProtoReflect.Descriptor instead.
func (*GenerateReconciliationRequest) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateReconciliationRequest) GetDateRangeStart() string {
	if x != nil {
		return x.DateRangeStart
	}
	return ""
}

func (x *GenerateReconciliationRequest) GetDateRangeEnd() string {
	if x != nil {
		return x.DateRangeEnd
	}
	return ""
}

func (x *GenerateReconciliationRequest) GetAccountFilter() []string {
	if x != nil {
		return x.AccountFilter
	}
	return nil
}

func (x *GenerateReconciliationRequest) GetAutoMatchEnabled() bool {
	if x != nil {
		return x.AutoMatchEnabled
	}
	return false
}

func (x *GenerateReconciliationRequest) GetToleranceAmount() float64 {
	if x != nil {
		return x.ToleranceAmount
	}
	return 0
}

type GenerateReconciliationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ReconciliationReport  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReconciliationResponse) Reset() {
	*x = GenerateReconciliationResponse{}
	mi := &file_proto_reconciliation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReconciliationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReconciliationResponse) ProtoMessage() {}

func (x *GenerateReconciliationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReconciliationResponse.ProtoReflect.Descriptor instead.
func (*GenerateReconciliationResponse) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{17}
}

func (x *GenerateReconciliationResponse) GetReport() *ReconciliationReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GenerateReconciliationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetReconciliationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconciliationStatusRequest) Reset() {
	*x = GetReconciliationStatusRequest{}
	mi := &file_proto_reconciliation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconciliationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconciliationStatusRequest) ProtoMessage() {}

func (x *GetReconciliationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconciliationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetReconciliationStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{18}
}

func (x *GetReconciliationStatusRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetReconciliationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *ReconciliationReport  `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReconciliationStatusResponse) Reset() {
	*x = GetReconciliationStatusResponse{}
	mi := &file_proto_reconciliation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReconciliationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReconciliationStatusResponse) ProtoMessage() {}

func (x *GetReconciliationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reconciliation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReconciliationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetReconciliationStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_reconciliation_proto_rawDescGZIP(), []int{19}
}

func (x *GetReconciliationStatusResponse) GetReport() *ReconciliationReport {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_proto_reconciliation_proto protoreflect.FileDescriptor

const file_proto_reconciliation_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/reconciliation.proto\x12\x19fintech.reconciliation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x06\n" +
	"\x14ReconciliationReport\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12(\n" +
	"\x10date_range_start\x18\x02 \x01(\tR\x0edateRangeStart\x12$\n" +
	"\x0edate_range_end\x18\x03 \x01(\tR\fdateRangeEnd\x12G\n" +
	"\x06status\x18\x04 \x01(\x0e2/.fintech.reconciliation.v1.ReconciliationStatusR\x06status\x12>\n" +
	"\x1btotal_internal_transactions\x18\x05 \x01(\x05R\x19totalInternalTransactions\x12>\n" +
	"\x1btotal_external_transactions\x18\x06 \x01(\x05R\x19totalExternalTransactions\x122\n" +
	"\x15total_internal_amount\x18\a \x01(\x01R\x13totalInternalAmount\x122\n" +
	"\x15total_external_amount\x18\b \x01(\x01R\x13totalExternalAmount\x121\n" +
	"\x14matched_transactions\x18\t \x01(\x05R\x13matchedTransactions\x12-\n" +
	"\x12unmatched_internal\x18\n" +
	" \x01(\x05R\x11unmatchedInternal\x12-\n" +
	"\x12unmatched_external\x18\v \x01(\x05R\x11unmatchedExternal\x12A\n" +
	"\tvariances\x18\f \x03(\v2#.fintech.reconciliation.v1.VarianceR\tvariances\x12=\n" +
	"\fgenerated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x12=\n" +
	"\fcompleted_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12#\n" +
	"\rreconciled_by\x18\x0f \x01(\tR\freconciledBy\"\xa2\x05\n" +
	"\bVariance\x12\x1f\n" +
	"\vvariance_id\x18\x01 \x01(\tR\n" +
	"varianceId\x12;\n" +
	"\x04type\x18\x02 \x01(\x0e2'.fintech.reconciliation.v1.VarianceTypeR\x04type\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x126\n" +
	"\x17internal_transaction_id\x18\x04 \x01(\tR\x15internalTransactionId\x126\n" +
	"\x17external_transaction_id\x18\x05 \x01(\tR\x15externalTransactionId\x12'\n" +
	"\x0finternal_amount\x18\x06 \x01(\x01R\x0einternalAmount\x12'\n" +
	"\x0fexternal_amount\x18\a \x01(\x01R\x0eexternalAmount\x12'\n" +
	"\x0fvariance_amount\x18\b \x01(\x01R\x0evarianceAmount\x12\x1a\n" +
	"\bcurrency\x18\t \x01(\tR\bcurrency\x12?\n" +
	"\rinternal_date\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\finternalDate\x12?\n" +
	"\rexternal_date\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\fexternalDate\x12)\n" +
	"\x10suggested_action\x18\f \x01(\tR\x0fsuggestedAction\x12\x14\n" +
	"\x05notes\x18\r \x01(\tR\x05notes\x12+\n" +
	"\x11requires_approval\x18\x0e \x01(\bR\x10requiresApproval\x12\x1f\n" +
	"\vassigned_to\x18\x0f \x01(\tR\n" +
	"assignedTo\"\xe9\x03\n" +
	"\vReconAction\x12c\n" +
	"\x14start_reconciliation\x18\x01 \x01(\v2..fintech.reconciliation.v1.StartReconciliationH\x00R\x13startReconciliation\x12W\n" +
	"\x10process_variance\x18\x02 \x01(\v2*.fintech.reconciliation.v1.ProcessVarianceH\x00R\x0fprocessVariance\x12W\n" +
	"\x10approval_request\x18\x03 \x01(\v2*.fintech.reconciliation.v1.ApprovalRequestH\x00R\x0fapprovalRequest\x12K\n" +
	"\fget_progress\x18\x04 \x01(\v2&.fintech.reconciliation.v1.GetProgressH\x00R\vgetProgress\x12l\n" +
	"\x17complete_reconciliation\x18\x05 \x01(\v21.fintech.reconciliation.v1.CompleteReconciliationH\x00R\x16completeReconciliationB\b\n" +
	"\x06action\"\xe5\x01\n" +
	"\x13StartReconciliation\x12(\n" +
	"\x10date_range_start\x18\x01 \x01(\tR\x0edateRangeStart\x12$\n" +
	"\x0edate_range_end\x18\x02 \x01(\tR\fdateRangeEnd\x12%\n" +
	"\x0eaccount_filter\x18\x03 \x03(\tR\raccountFilter\x12,\n" +
	"\x12auto_match_enabled\x18\x04 \x01(\bR\x10autoMatchEnabled\x12)\n" +
	"\x10tolerance_amount\x18\x05 \x01(\x01R\x0ftoleranceAmount\"\xe1\x01\n" +
	"\x0fProcessVariance\x12\x1f\n" +
	"\vvariance_id\x18\x01 \x01(\tR\n" +
	"varianceId\x12=\n" +
	"\x06action\x18\x02 \x01(\x0e2%.fintech.reconciliation.v1.ActionTypeR\x06action\x12\x14\n" +
	"\x05notes\x18\x03 \x01(\tR\x05notes\x12+\n" +
	"\x11adjustment_amount\x18\x04 \x01(\x01R\x10adjustmentAmount\x12+\n" +
	"\x11adjustment_reason\x18\x05 \x01(\tR\x10adjustmentReason\"\x96\x01\n" +
	"\x0fApprovalRequest\x12\x1f\n" +
	"\vvariance_id\x18\x01 \x01(\tR\n" +
	"varianceId\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId\x12\x1a\n" +
	"\bapproved\x18\x03 \x01(\bR\bapproved\x12%\n" +
	"\x0eapproval_notes\x18\x04 \x01(\tR\rapprovalNotes\"6\n" +
	"\vGetProgress\x12'\n" +
	"\x0finclude_details\x18\x01 \x01(\bR\x0eincludeDetails\"`\n" +
	"\x16CompleteReconciliation\x12\x1f\n" +
	"\vfinal_notes\x18\x01 \x01(\tR\n" +
	"finalNotes\x12%\n" +
	"\x0eforce_complete\x18\x02 \x01(\bR\rforceComplete\"\xaa\x05\n" +
	"\vReconResult\x12i\n" +
	"\x16reconciliation_started\x18\x01 \x01(\v20.fintech.reconciliation.v1.ReconciliationStartedH\x00R\x15reconciliationStarted\x12Z\n" +
	"\x11variance_detected\x18\x02 \x01(\v2+.fintech.reconciliation.v1.VarianceDetectedH\x00R\x10varianceDetected\x12]\n" +
	"\x12variance_processed\x18\x03 \x01(\v2,.fintech.reconciliation.v1.VarianceProcessedH\x00R\x11varianceProcessed\x12Z\n" +
	"\x11approval_response\x18\x04 \x01(\v2+.fintech.reconciliation.v1.ApprovalResponseH\x00R\x10approvalResponse\x12T\n" +
	"\x0fprogress_update\x18\x05 \x01(\v2).fintech.reconciliation.v1.ProgressUpdateH\x00R\x0eprogressUpdate\x12o\n" +
	"\x18reconciliation_completed\x18\x06 \x01(\v22.fintech.reconciliation.v1.ReconciliationCompletedH\x00R\x17reconciliationCompleted\x12H\n" +
	"\vrecon_error\x18\a \x01(\v2%.fintech.reconciliation.v1.ReconErrorH\x00R\n" +
	"reconErrorB\b\n" +
	"\x06result\"\xa8\x01\n" +
	"\x15ReconciliationStarted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12V\n" +
	"\x0einitial_report\x18\x02 \x01(\v2/.fintech.reconciliation.v1.ReconciliationReportR\rinitialReport\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x9c\x01\n" +
	"\x10VarianceDetected\x12?\n" +
	"\bvariance\x18\x01 \x01(\v2#.fintech.reconciliation.v1.VarianceR\bvariance\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12+\n" +
	"\x11suggested_actions\x18\x03 \x03(\tR\x10suggestedActions\"\xdf\x01\n" +
	"\x11VarianceProcessed\x12\x1f\n" +
	"\vvariance_id\x18\x01 \x01(\tR\n" +
	"varianceId\x12H\n" +
	"\faction_taken\x18\x02 \x01(\x0e2%.fintech.reconciliation.v1.ActionTypeR\vactionTaken\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12+\n" +
	"\x11requires_approval\x18\x05 \x01(\bR\x10requiresApproval\"\x8a\x01\n" +
	"\x10ApprovalResponse\x12\x1f\n" +
	"\vvariance_id\x18\x01 \x01(\tR\n" +
	"varianceId\x12\x1a\n" +
	"\bapproved\x18\x02 \x01(\bR\bapproved\x12\x1f\n" +
	"\vapprover_id\x18\x03 \x01(\tR\n" +
	"approverId\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xc3\x02\n" +
	"\x0eProgressUpdate\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12'\n" +
	"\x0ftotal_variances\x18\x02 \x01(\x05R\x0etotalVariances\x12/\n" +
	"\x13processed_variances\x18\x03 \x01(\x05R\x12processedVariances\x12)\n" +
	"\x10pending_approval\x18\x04 \x01(\x05R\x0fpendingApproval\x121\n" +
	"\x14unresolved_variances\x18\x05 \x01(\x05R\x13unresolvedVariances\x123\n" +
	"\x15completion_percentage\x18\x06 \x01(\x01R\x14completionPercentage\x12%\n" +
	"\x0ecurrent_status\x18\a \x01(\tR\rcurrentStatus\"\xfa\x01\n" +
	"\x17ReconciliationCompleted\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12R\n" +
	"\ffinal_report\x18\x02 \x01(\v2/.fintech.reconciliation.v1.ReconciliationReportR\vfinalReport\x12-\n" +
	"\x12completion_message\x18\x03 \x01(\tR\x11completionMessage\x12=\n" +
	"\fcompleted_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\"q\n" +
	"\n" +
	"ReconError\x12\x1d\n" +
	"\n" +
	"error_code\x18\x01 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vvariance_id\x18\x03 \x01(\tR\n" +
	"varianceId\"\xef\x01\n" +
	"\x1dGenerateReconciliationRequest\x12(\n" +
	"\x10date_range_start\x18\x01 \x01(\tR\x0edateRangeStart\x12$\n" +
	"\x0edate_range_end\x18\x02 \x01(\tR\fdateRangeEnd\x12%\n" +
	"\x0eaccount_filter\x18\x03 \x03(\tR\raccountFilter\x12,\n" +
	"\x12auto_match_enabled\x18\x04 \x01(\bR\x10autoMatchEnabled\x12)\n" +
	"\x10tolerance_amount\x18\x05 \x01(\x01R\x0ftoleranceAmount\"\x83\x01\n" +
	"\x1eGenerateReconciliationResponse\x12G\n" +
	"\x06report\x18\x01 \x01(\v2/.fintech.reconciliation.v1.ReconciliationReportR\x06report\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"=\n" +
	"\x1eGetReconciliationStatusRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"j\n" +
	"\x1fGetReconciliationStatusResponse\x12G\n" +
	"\x06report\x18\x01 \x01(\v2/.fintech.reconciliation.v1.ReconciliationReportR\x06report*\xf9\x01\n" +
	"\x14ReconciliationStatus\x12%\n" +
	"!RECONCILIATION_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRECONCILIATION_STATUS_PENDING\x10\x01\x12%\n" +
	"!RECONCILIATION_STATUS_IN_PROGRESS\x10\x02\x12#\n" +
	"\x1fRECONCILIATION_STATUS_COMPLETED\x10\x03\x12 \n" +
	"\x1cRECONCILIATION_STATUS_FAILED\x10\x04\x12)\n" +
	"%RECONCILIATION_STATUS_REQUIRES_REVIEW\x10\x05*\xd6\x01\n" +
	"\fVarianceType\x12\x1d\n" +
	"\x19VARIANCE_TYPE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eVARIANCE_TYPE_MISSING_INTERNAL\x10\x01\x12\"\n" +
	"\x1eVARIANCE_TYPE_MISSING_EXTERNAL\x10\x02\x12!\n" +
	"\x1dVARIANCE_TYPE_AMOUNT_MISMATCH\x10\x03\x12\x1f\n" +
	"\x1bVARIANCE_TYPE_DATE_MISMATCH\x10\x04\x12\x1b\n" +
	"\x17VARIANCE_TYPE_DUPLICATE\x10\x05*\xa3\x01\n" +
	"\n" +
	"ActionType\x12\x1b\n" +
	"\x17ACTION_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ACTION_TYPE_ACCEPT\x10\x01\x12\x16\n" +
	"\x12ACTION_TYPE_REJECT\x10\x02\x12\x16\n" +
	"\x12ACTION_TYPE_ADJUST\x10\x03\x12\x16\n" +
	"\x12ACTION_TYPE_IGNORE\x10\x04\x12\x18\n" +
	"\x14ACTION_TYPE_ESCALATE\x10\x052\xab\x03\n" +
	"\x15ReconciliationService\x12\x8d\x01\n" +
	"\x16GenerateReconciliation\x128.fintech.reconciliation.v1.GenerateReconciliationRequest\x1a9.fintech.reconciliation.v1.GenerateReconciliationResponse\x12\x90\x01\n" +
	"\x17GetReconciliationStatus\x129.fintech.reconciliation.v1.GetReconciliationStatusRequest\x1a:.fintech.reconciliation.v1.GetReconciliationStatusResponse\x12o\n" +
	"\x19InteractiveReconciliation\x12&.fintech.reconciliation.v1.ReconAction\x1a&.fintech.reconciliation.v1.ReconResult(\x010\x01B!Z\x1ffintech-api/proto/gen/protob\x06proto3"

var (
	file_proto_reconciliation_proto_rawDescOnce sync.Once
	file_proto_reconciliation_proto_rawDescData []byte
)

func file_proto_reconciliation_proto_rawDescGZIP() []byte {
	file_proto_reconciliation_proto_rawDescOnce.Do(func() {
		file_proto_reconciliation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reconciliation_proto_rawDesc), len(file_proto_reconciliation_proto_rawDesc)))
	})
	return file_proto_reconciliation_proto_rawDescData
}

var file_proto_reconciliation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_reconciliation_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_reconciliation_proto_goTypes = []any{
	(ReconciliationStatus)(0),               // 0: fintech.reconciliation.v1.ReconciliationStatus
	(VarianceType)(0),                       // 1: fintech.reconciliation.v1.VarianceType
	(ActionType)(0),                         // 2: fintech.reconciliation.v1.ActionType
	(*ReconciliationReport)(nil),            // 3: fintech.reconciliation.v1.ReconciliationReport
	(*Variance)(nil),                        // 4: fintech.reconciliation.v1.Variance
	(*ReconAction)(nil),                     // 5: fintech.reconciliation.v1.ReconAction
	(*StartReconciliation)(nil),             // 6: fintech.reconciliation.v1.StartReconciliation
	(*ProcessVariance)(nil),                 // 7: fintech.reconciliation.v1.ProcessVariance
	(*ApprovalRequest)(nil),                 // 8: fintech.reconciliation.v1.ApprovalRequest
	(*GetProgress)(nil),                     // 9: fintech.reconciliation.v1.GetProgress
	(*CompleteReconciliation)(nil),          // 10: fintech.reconciliation.v1.CompleteReconciliation
	(*ReconResult)(nil),                     // 11: fintech.reconciliation.v1.ReconResult
	(*ReconciliationStarted)(nil),           // 12: fintech.reconciliation.v1.ReconciliationStarted
	(*VarianceDetected)(nil),                // 13: fintech.reconciliation.v1.VarianceDetected
	(*VarianceProcessed)(nil),               // 14: fintech.reconciliation.v1.VarianceProcessed
	(*ApprovalResponse)(nil),                // 15: fintech.reconciliation.v1.ApprovalResponse
	(*ProgressUpdate)(nil),                  // 16: fintech.reconciliation.v1.ProgressUpdate
	(*ReconciliationCompleted)(nil),         // 17: fintech.reconciliation.v1.ReconciliationCompleted
	(*ReconError)(nil),                      // 18: fintech.reconciliation.v1.ReconError
	(*GenerateReconciliationRequest)(nil),   // 19: fintech.reconciliation.v1.GenerateReconciliationRequest
	(*GenerateReconciliationResponse)(nil),  // 20: fintech.reconciliation.v1.GenerateReconciliationResponse
	(*GetReconciliationStatusRequest)(nil),  // 21: fintech.reconciliation.v1.GetReconciliationStatusRequest
	(*GetReconciliationStatusResponse)(nil), // 22: fintech.reconciliation.v1.GetReconciliationStatusResponse
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
}
var file_proto_reconciliation_proto_depIdxs = []int32{
	0,  // 0: fintech.reconciliation.v1.ReconciliationReport.status:type_name -> fintech.reconciliation.v1.ReconciliationStatus
	4,  // 1: fintech.reconciliation.v1.ReconciliationReport.variances:type_name -> fintech.reconciliation.v1.Variance
	23, // 2: fintech.reconciliation.v1.ReconciliationReport.generated_at:type_name -> google.protobuf.Timestamp
	23, // 3: fintech.reconciliation.v1.ReconciliationReport.completed_at:type_name -> google.protobuf.Timestamp
	1,  // 4: fintech.reconciliation.v1.Variance.type:type_name -> fintech.reconciliation.v1.VarianceType
	23, // 5: fintech.reconciliation.v1.Variance.internal_date:type_name -> google.protobuf.Timestamp
	23, // 6: fintech.reconciliation.v1.Variance.external_date:type_name -> google.protobuf.Timestamp
	6,  // 7: fintech.reconciliation.v1.ReconAction.start_reconciliation:type_name -> fintech.reconciliation.v1.StartReconciliation
	7,  // 8: fintech.reconciliation.v1.ReconAction.process_variance:type_name -> fintech.reconciliation.v1.ProcessVariance
	8,  // 9: fintech.reconciliation.v1.ReconAction.approval_request:type_name -> fintech.reconciliation.v1.ApprovalRequest
	9,  // 10: fintech.reconciliation.v1.ReconAction.get_progress:type_name -> fintech.reconciliation.v1.GetProgress
	10, // 11: fintech.reconciliation.v1.ReconAction.complete_reconciliation:type_name -> fintech.reconciliation.v1.CompleteReconciliation
	2,  // 12: fintech.reconciliation.v1.ProcessVariance.action:type_name -> fintech.reconciliation.v1.ActionType
	12, // 13: fintech.reconciliation.v1.ReconResult.reconciliation_started:type_name -> fintech.reconciliation.v1.ReconciliationStarted
	13, // 14: fintech.reconciliation.v1.ReconResult.variance_detected:type_name -> fintech.reconciliation.v1.VarianceDetected
	14, // 15: fintech.reconciliation.v1.ReconResult.variance_processed:type_name -> fintech.reconciliation.v1.VarianceProcessed
	15, // 16: fintech.reconciliation.v1.ReconResult.approval_response:type_name -> fintech.reconciliation.v1.ApprovalResponse
	16, // 17: fintech.reconciliation.v1.ReconResult.progress_update:type_name -> fintech.reconciliation.v1.ProgressUpdate
	17, // 18: fintech.reconciliation.v1.ReconResult.reconciliation_completed:type_name -> fintech.reconciliation.v1.ReconciliationCompleted
	18, // 19: fintech.reconciliation.v1.ReconResult.recon_error:type_name -> fintech.reconciliation.v1.ReconError
	3,  // 20: fintech.reconciliation.v1.ReconciliationStarted.initial_report:type_name -> fintech.reconciliation.v1.ReconciliationReport
	4,  // 21: fintech.reconciliation.v1.VarianceDetected.variance:type_name -> fintech.reconciliation.v1.Variance
	2,  // 22: fintech.reconciliation.v1.VarianceProcessed.action_taken:type_name -> fintech.reconciliation.v1.ActionType
	3,  // 23: fintech.reconciliation.v1.ReconciliationCompleted.final_report:type_name -> fintech.reconciliation.v1.ReconciliationReport
	23, // 24: fintech.reconciliation.v1.ReconciliationCompleted.completed_at:type_name -> google.protobuf.Timestamp
	3,  // 25: fintech.reconciliation.v1.GenerateReconciliationResponse.report:type_name -> fintech.reconciliation.v1.ReconciliationReport
	3,  // 26: fintech.reconciliation.v1.GetReconciliationStatusResponse.report:type_name -> fintech.reconciliation.v1.ReconciliationReport
	19, // 27: fintech.reconciliation.v1.ReconciliationService.GenerateReconciliation:input_type -> fintech.reconciliation.v1.GenerateReconciliationRequest
	21, // 28: fintech.reconciliation.v1.ReconciliationService.GetReconciliationStatus:input_type -> fintech.reconciliation.v1.GetReconciliationStatusRequest
	5,  // 29: fintech.reconciliation.v1.ReconciliationService.InteractiveReconciliation:input_type -> fintech.reconciliation.v1.ReconAction
	20, // 30: fintech.reconciliation.v1.ReconciliationService.GenerateReconciliation:output_type -> fintech.reconciliation.v1.GenerateReconciliationResponse
	22, // 31: fintech.reconciliation.v1.ReconciliationService.GetReconciliationStatus:output_type -> fintech.reconciliation.v1.GetReconciliationStatusResponse
	11, // 32: fintech.reconciliation.v1.ReconciliationService.InteractiveReconciliation:output_type -> fintech.reconciliation.v1.ReconResult
	30, // [30:33] is the sub-list for method output_type
	27, // [27:30] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_proto_reconciliation_proto_init() }
func file_proto_reconciliation_proto_init() {
	if File_proto_reconciliation_proto != nil {
		return
	}
	file_proto_reconciliation_proto_msgTypes[2].OneofWrappers = []any{
		(*ReconAction_StartReconciliation)(nil),
		(*ReconAction_ProcessVariance)(nil),
		(*ReconAction_ApprovalRequest)(nil),
		(*ReconAction_GetProgress)(nil),
		(*ReconAction_CompleteReconciliation)(nil),
	}
	file_proto_reconciliation_proto_msgTypes[8].OneofWrappers = []any{
		(*ReconResult_ReconciliationStarted)(nil),
		(*ReconResult_VarianceDetected)(nil),
		(*ReconResult_VarianceProcessed)(nil),
		(*ReconResult_ApprovalResponse)(nil),
		(*ReconResult_ProgressUpdate)(nil),
		(*ReconResult_ReconciliationCompleted)(nil),
		(*ReconResult_ReconError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reconciliation_proto_rawDesc), len(file_proto_reconciliation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reconciliation_proto_goTypes,
		DependencyIndexes: file_proto_reconciliation_proto_depIdxs,
		EnumInfos:         file_proto_reconciliation_proto_enumTypes,
		MessageInfos:      file_proto_reconciliation_proto_msgTypes,
	}.Build()
	File_proto_reconciliation_proto = out.File
	file_proto_reconciliation_proto_goTypes = nil
	file_proto_reconciliation_proto_depIdxs = nil
}
