// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: transaction_validation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Validation result enum
type ValidationResult int32

const (
	ValidationResult_VALIDATION_RESULT_UNSPECIFIED       ValidationResult = 0
	ValidationResult_VALIDATION_RESULT_VALID             ValidationResult = 1
	ValidationResult_VALIDATION_RESULT_INVALID           ValidationResult = 2
	ValidationResult_VALIDATION_RESULT_REQUIRES_APPROVAL ValidationResult = 3
)

// Enum value maps for ValidationResult.
var (
	ValidationResult_name = map[int32]string{
		0: "VALIDATION_RESULT_UNSPECIFIED",
		1: "VALIDATION_RESULT_VALID",
		2: "VALIDATION_RESULT_INVALID",
		3: "VALIDATION_RESULT_REQUIRES_APPROVAL",
	}
	ValidationResult_value = map[string]int32{
		"VALIDATION_RESULT_UNSPECIFIED":       0,
		"VALIDATION_RESULT_VALID":             1,
		"VALIDATION_RESULT_INVALID":           2,
		"VALIDATION_RESULT_REQUIRES_APPROVAL": 3,
	}
)

func (x ValidationResult) Enum() *ValidationResult {
	p := new(ValidationResult)
	*p = x
	return p
}

func (x ValidationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_validation_proto_enumTypes[0].Descriptor()
}

func (ValidationResult) Type() protoreflect.EnumType {
	return &file_transaction_validation_proto_enumTypes[0]
}

func (x ValidationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationResult.Descriptor instead.
func (ValidationResult) EnumDescriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{0}
}

// Validation error severity
type ValidationSeverity int32

const (
	ValidationSeverity_VALIDATION_SEVERITY_UNSPECIFIED ValidationSeverity = 0
	ValidationSeverity_VALIDATION_SEVERITY_INFO        ValidationSeverity = 1
	ValidationSeverity_VALIDATION_SEVERITY_WARNING     ValidationSeverity = 2
	ValidationSeverity_VALIDATION_SEVERITY_ERROR       ValidationSeverity = 3
	ValidationSeverity_VALIDATION_SEVERITY_CRITICAL    ValidationSeverity = 4
)

// Enum value maps for ValidationSeverity.
var (
	ValidationSeverity_name = map[int32]string{
		0: "VALIDATION_SEVERITY_UNSPECIFIED",
		1: "VALIDATION_SEVERITY_INFO",
		2: "VALIDATION_SEVERITY_WARNING",
		3: "VALIDATION_SEVERITY_ERROR",
		4: "VALIDATION_SEVERITY_CRITICAL",
	}
	ValidationSeverity_value = map[string]int32{
		"VALIDATION_SEVERITY_UNSPECIFIED": 0,
		"VALIDATION_SEVERITY_INFO":        1,
		"VALIDATION_SEVERITY_WARNING":     2,
		"VALIDATION_SEVERITY_ERROR":       3,
		"VALIDATION_SEVERITY_CRITICAL":    4,
	}
)

func (x ValidationSeverity) Enum() *ValidationSeverity {
	p := new(ValidationSeverity)
	*p = x
	return p
}

func (x ValidationSeverity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationSeverity) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_validation_proto_enumTypes[1].Descriptor()
}

func (ValidationSeverity) Type() protoreflect.EnumType {
	return &file_transaction_validation_proto_enumTypes[1]
}

func (x ValidationSeverity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationSeverity.Descriptor instead.
func (ValidationSeverity) EnumDescriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{1}
}

// Account type enum
type AccountType int32

const (
	AccountType_ACCOUNT_TYPE_UNSPECIFIED AccountType = 0
	AccountType_ACCOUNT_TYPE_BANK        AccountType = 1
	AccountType_ACCOUNT_TYPE_CASH        AccountType = 2
	AccountType_ACCOUNT_TYPE_INVESTMENT  AccountType = 3
	AccountType_ACCOUNT_TYPE_CREDIT      AccountType = 4
	AccountType_ACCOUNT_TYPE_SAVINGS     AccountType = 5
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "ACCOUNT_TYPE_UNSPECIFIED",
		1: "ACCOUNT_TYPE_BANK",
		2: "ACCOUNT_TYPE_CASH",
		3: "ACCOUNT_TYPE_INVESTMENT",
		4: "ACCOUNT_TYPE_CREDIT",
		5: "ACCOUNT_TYPE_SAVINGS",
	}
	AccountType_value = map[string]int32{
		"ACCOUNT_TYPE_UNSPECIFIED": 0,
		"ACCOUNT_TYPE_BANK":        1,
		"ACCOUNT_TYPE_CASH":        2,
		"ACCOUNT_TYPE_INVESTMENT":  3,
		"ACCOUNT_TYPE_CREDIT":      4,
		"ACCOUNT_TYPE_SAVINGS":     5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_transaction_validation_proto_enumTypes[2].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_transaction_validation_proto_enumTypes[2]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{2}
}

// Transaction validation request
type ValidateTransactionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromAccountId   string                 `protobuf:"bytes,2,opt,name=from_account_id,json=fromAccountId,proto3" json:"from_account_id,omitempty"`
	ToAccountId     string                 `protobuf:"bytes,3,opt,name=to_account_id,json=toAccountId,proto3" json:"to_account_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency        string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Description     string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Reference       string                 `protobuf:"bytes,7,opt,name=reference,proto3" json:"reference,omitempty"`
	TransactionType string                 `protobuf:"bytes,8,opt,name=transaction_type,json=transactionType,proto3" json:"transaction_type,omitempty"` // "transfer", "payment", "deposit", "withdrawal"
	Metadata        map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidateTransactionRequest) Reset() {
	*x = ValidateTransactionRequest{}
	mi := &file_transaction_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTransactionRequest) ProtoMessage() {}

func (x *ValidateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTransactionRequest.ProtoReflect.Descriptor instead.
func (*ValidateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateTransactionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTransactionRequest) GetFromAccountId() string {
	if x != nil {
		return x.FromAccountId
	}
	return ""
}

func (x *ValidateTransactionRequest) GetToAccountId() string {
	if x != nil {
		return x.ToAccountId
	}
	return ""
}

func (x *ValidateTransactionRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ValidateTransactionRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ValidateTransactionRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ValidateTransactionRequest) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ValidateTransactionRequest) GetTransactionType() string {
	if x != nil {
		return x.TransactionType
	}
	return ""
}

func (x *ValidateTransactionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// Transaction validation response
type ValidateTransactionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Result           ValidationResult       `protobuf:"varint,1,opt,name=result,proto3,enum=fintech.transaction_validation.v1.ValidationResult" json:"result,omitempty"`
	ValidationErrors []*ValidationError     `protobuf:"bytes,2,rep,name=validation_errors,json=validationErrors,proto3" json:"validation_errors,omitempty"`
	AvailableBalance float64                `protobuf:"fixed64,3,opt,name=available_balance,json=availableBalance,proto3" json:"available_balance,omitempty"`
	EstimatedFees    *TransactionFees       `protobuf:"bytes,4,opt,name=estimated_fees,json=estimatedFees,proto3" json:"estimated_fees,omitempty"`
	EstimatedTotal   float64                `protobuf:"fixed64,5,opt,name=estimated_total,json=estimatedTotal,proto3" json:"estimated_total,omitempty"`
	Warnings         []string               `protobuf:"bytes,6,rep,name=warnings,proto3" json:"warnings,omitempty"`
	ComplianceCheck  *ComplianceCheck       `protobuf:"bytes,7,opt,name=compliance_check,json=complianceCheck,proto3" json:"compliance_check,omitempty"`
	Requires_2Fa     bool                   `protobuf:"varint,8,opt,name=requires_2fa,json=requires2fa,proto3" json:"requires_2fa,omitempty"`
	ValidatedAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=validated_at,json=validatedAt,proto3" json:"validated_at,omitempty"`
	ValidationId     string                 `protobuf:"bytes,10,opt,name=validation_id,json=validationId,proto3" json:"validation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ValidateTransactionResponse) Reset() {
	*x = ValidateTransactionResponse{}
	mi := &file_transaction_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTransactionResponse) ProtoMessage() {}

func (x *ValidateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTransactionResponse.ProtoReflect.Descriptor instead.
func (*ValidateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTransactionResponse) GetResult() ValidationResult {
	if x != nil {
		return x.Result
	}
	return ValidationResult_VALIDATION_RESULT_UNSPECIFIED
}

func (x *ValidateTransactionResponse) GetValidationErrors() []*ValidationError {
	if x != nil {
		return x.ValidationErrors
	}
	return nil
}

func (x *ValidateTransactionResponse) GetAvailableBalance() float64 {
	if x != nil {
		return x.AvailableBalance
	}
	return 0
}

func (x *ValidateTransactionResponse) GetEstimatedFees() *TransactionFees {
	if x != nil {
		return x.EstimatedFees
	}
	return nil
}

func (x *ValidateTransactionResponse) GetEstimatedTotal() float64 {
	if x != nil {
		return x.EstimatedTotal
	}
	return 0
}

func (x *ValidateTransactionResponse) GetWarnings() []string {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *ValidateTransactionResponse) GetComplianceCheck() *ComplianceCheck {
	if x != nil {
		return x.ComplianceCheck
	}
	return nil
}

func (x *ValidateTransactionResponse) GetRequires_2Fa() bool {
	if x != nil {
		return x.Requires_2Fa
	}
	return false
}

func (x *ValidateTransactionResponse) GetValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidatedAt
	}
	return nil
}

func (x *ValidateTransactionResponse) GetValidationId() string {
	if x != nil {
		return x.ValidationId
	}
	return ""
}

// Batch validation request
type BatchValidateRequest struct {
	state            protoimpl.MessageState        `protogen:"open.v1"`
	UserId           string                        `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Transactions     []*ValidateTransactionRequest `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	StopOnFirstError bool                          `protobuf:"varint,3,opt,name=stop_on_first_error,json=stopOnFirstError,proto3" json:"stop_on_first_error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchValidateRequest) Reset() {
	*x = BatchValidateRequest{}
	mi := &file_transaction_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateRequest) ProtoMessage() {}

func (x *BatchValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateRequest.ProtoReflect.Descriptor instead.
func (*BatchValidateRequest) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{2}
}

func (x *BatchValidateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *BatchValidateRequest) GetTransactions() []*ValidateTransactionRequest {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *BatchValidateRequest) GetStopOnFirstError() bool {
	if x != nil {
		return x.StopOnFirstError
	}
	return false
}

// Batch validation response
type BatchValidateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Results          []ValidationResult     `protobuf:"varint,1,rep,packed,name=results,proto3,enum=fintech.transaction_validation.v1.ValidationResult" json:"results,omitempty"`
	ValidCount       int32                  `protobuf:"varint,2,opt,name=valid_count,json=validCount,proto3" json:"valid_count,omitempty"`
	InvalidCount     int32                  `protobuf:"varint,3,opt,name=invalid_count,json=invalidCount,proto3" json:"invalid_count,omitempty"`
	WarningCount     int32                  `protobuf:"varint,4,opt,name=warning_count,json=warningCount,proto3" json:"warning_count,omitempty"`
	TotalAmount      float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TotalFees        float64                `protobuf:"fixed64,6,opt,name=total_fees,json=totalFees,proto3" json:"total_fees,omitempty"`
	BatchWarnings    []string               `protobuf:"bytes,7,rep,name=batch_warnings,json=batchWarnings,proto3" json:"batch_warnings,omitempty"`
	BatchValidatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=batch_validated_at,json=batchValidatedAt,proto3" json:"batch_validated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BatchValidateResponse) Reset() {
	*x = BatchValidateResponse{}
	mi := &file_transaction_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateResponse) ProtoMessage() {}

func (x *BatchValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateResponse.ProtoReflect.Descriptor instead.
func (*BatchValidateResponse) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{3}
}

func (x *BatchValidateResponse) GetResults() []ValidationResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *BatchValidateResponse) GetValidCount() int32 {
	if x != nil {
		return x.ValidCount
	}
	return 0
}

func (x *BatchValidateResponse) GetInvalidCount() int32 {
	if x != nil {
		return x.InvalidCount
	}
	return 0
}

func (x *BatchValidateResponse) GetWarningCount() int32 {
	if x != nil {
		return x.WarningCount
	}
	return 0
}

func (x *BatchValidateResponse) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *BatchValidateResponse) GetTotalFees() float64 {
	if x != nil {
		return x.TotalFees
	}
	return 0
}

func (x *BatchValidateResponse) GetBatchWarnings() []string {
	if x != nil {
		return x.BatchWarnings
	}
	return nil
}

func (x *BatchValidateResponse) GetBatchValidatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.BatchValidatedAt
	}
	return nil
}

// Validation error details
type ValidationError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Severity      ValidationSeverity     `protobuf:"varint,4,opt,name=severity,proto3,enum=fintech.transaction_validation.v1.ValidationSeverity" json:"severity,omitempty"`
	Suggestion    string                 `protobuf:"bytes,5,opt,name=suggestion,proto3" json:"suggestion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationError) Reset() {
	*x = ValidationError{}
	mi := &file_transaction_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationError) ProtoMessage() {}

func (x *ValidationError) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationError.ProtoReflect.Descriptor instead.
func (*ValidationError) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ValidationError) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ValidationError) GetSeverity() ValidationSeverity {
	if x != nil {
		return x.Severity
	}
	return ValidationSeverity_VALIDATION_SEVERITY_UNSPECIFIED
}

func (x *ValidationError) GetSuggestion() string {
	if x != nil {
		return x.Suggestion
	}
	return ""
}

// Transaction fees breakdown
type TransactionFees struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseFee       float64                `protobuf:"fixed64,1,opt,name=base_fee,json=baseFee,proto3" json:"base_fee,omitempty"`
	ProcessingFee float64                `protobuf:"fixed64,2,opt,name=processing_fee,json=processingFee,proto3" json:"processing_fee,omitempty"`
	FxFee         float64                `protobuf:"fixed64,3,opt,name=fx_fee,json=fxFee,proto3" json:"fx_fee,omitempty"`
	ComplianceFee float64                `protobuf:"fixed64,4,opt,name=compliance_fee,json=complianceFee,proto3" json:"compliance_fee,omitempty"`
	TotalFee      float64                `protobuf:"fixed64,5,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	FeeComponents []*FeeComponent        `protobuf:"bytes,7,rep,name=fee_components,json=feeComponents,proto3" json:"fee_components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFees) Reset() {
	*x = TransactionFees{}
	mi := &file_transaction_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFees) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFees) ProtoMessage() {}

func (x *TransactionFees) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFees.ProtoReflect.Descriptor instead.
func (*TransactionFees) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{5}
}

func (x *TransactionFees) GetBaseFee() float64 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

func (x *TransactionFees) GetProcessingFee() float64 {
	if x != nil {
		return x.ProcessingFee
	}
	return 0
}

func (x *TransactionFees) GetFxFee() float64 {
	if x != nil {
		return x.FxFee
	}
	return 0
}

func (x *TransactionFees) GetComplianceFee() float64 {
	if x != nil {
		return x.ComplianceFee
	}
	return 0
}

func (x *TransactionFees) GetTotalFee() float64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *TransactionFees) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionFees) GetFeeComponents() []*FeeComponent {
	if x != nil {
		return x.FeeComponents
	}
	return nil
}

// Fee component details
type FeeComponent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"` // "fixed", "percentage", "variable"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeeComponent) Reset() {
	*x = FeeComponent{}
	mi := &file_transaction_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeeComponent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeComponent) ProtoMessage() {}

func (x *FeeComponent) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeComponent.ProtoReflect.Descriptor instead.
func (*FeeComponent) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{6}
}

func (x *FeeComponent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FeeComponent) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *FeeComponent) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FeeComponent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Compliance check result
type ComplianceCheck struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Passed            bool                   `protobuf:"varint,1,opt,name=passed,proto3" json:"passed,omitempty"`
	ComplianceLevel   string                 `protobuf:"bytes,2,opt,name=compliance_level,json=complianceLevel,proto3" json:"compliance_level,omitempty"` // "low", "medium", "high"
	Flags             []string               `protobuf:"bytes,3,rep,name=flags,proto3" json:"flags,omitempty"`
	RiskScore         int32                  `protobuf:"varint,4,opt,name=risk_score,json=riskScore,proto3" json:"risk_score,omitempty"`
	RequiresKyc       bool                   `protobuf:"varint,5,opt,name=requires_kyc,json=requiresKyc,proto3" json:"requires_kyc,omitempty"`
	RequiredDocuments []string               `protobuf:"bytes,6,rep,name=required_documents,json=requiredDocuments,proto3" json:"required_documents,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ComplianceCheck) Reset() {
	*x = ComplianceCheck{}
	mi := &file_transaction_validation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComplianceCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComplianceCheck) ProtoMessage() {}

func (x *ComplianceCheck) ProtoReflect() protoreflect.Message {
	mi := &file_transaction_validation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComplianceCheck.ProtoReflect.Descriptor instead.
func (*ComplianceCheck) Descriptor() ([]byte, []int) {
	return file_transaction_validation_proto_rawDescGZIP(), []int{7}
}

func (x *ComplianceCheck) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *ComplianceCheck) GetComplianceLevel() string {
	if x != nil {
		return x.ComplianceLevel
	}
	return ""
}

func (x *ComplianceCheck) GetFlags() []string {
	if x != nil {
		return x.Flags
	}
	return nil
}

func (x *ComplianceCheck) GetRiskScore() int32 {
	if x != nil {
		return x.RiskScore
	}
	return 0
}

func (x *ComplianceCheck) GetRequiresKyc() bool {
	if x != nil {
		return x.RequiresKyc
	}
	return false
}

func (x *ComplianceCheck) GetRequiredDocuments() []string {
	if x != nil {
		return x.RequiredDocuments
	}
	return nil
}

var File_transaction_validation_proto protoreflect.FileDescriptor

const file_transaction_validation_proto_rawDesc = "" +
	"\n" +
	"\x1ctransaction_validation.proto\x12!fintech.transaction_validation.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x03\n" +
	"\x1aValidateTransactionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12&\n" +
	"\x0ffrom_account_id\x18\x02 \x01(\tR\rfromAccountId\x12\"\n" +
	"\rto_account_id\x18\x03 \x01(\tR\vtoAccountId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1c\n" +
	"\treference\x18\a \x01(\tR\treference\x12)\n" +
	"\x10transaction_type\x18\b \x01(\tR\x0ftransactionType\x12g\n" +
	"\bmetadata\x18\t \x03(\v2K.fintech.transaction_validation.v1.ValidateTransactionRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x04\n" +
	"\x1bValidateTransactionResponse\x12K\n" +
	"\x06result\x18\x01 \x01(\x0e23.fintech.transaction_validation.v1.ValidationResultR\x06result\x12_\n" +
	"\x11validation_errors\x18\x02 \x03(\v22.fintech.transaction_validation.v1.ValidationErrorR\x10validationErrors\x12+\n" +
	"\x11available_balance\x18\x03 \x01(\x01R\x10availableBalance\x12Y\n" +
	"\x0eestimated_fees\x18\x04 \x01(\v22.fintech.transaction_validation.v1.TransactionFeesR\restimatedFees\x12'\n" +
	"\x0festimated_total\x18\x05 \x01(\x01R\x0eestimatedTotal\x12\x1a\n" +
	"\bwarnings\x18\x06 \x03(\tR\bwarnings\x12]\n" +
	"\x10compliance_check\x18\a \x01(\v22.fintech.transaction_validation.v1.ComplianceCheckR\x0fcomplianceCheck\x12!\n" +
	"\frequires_2fa\x18\b \x01(\bR\vrequires2fa\x12=\n" +
	"\fvalidated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vvalidatedAt\x12#\n" +
	"\rvalidation_id\x18\n" +
	" \x01(\tR\fvalidationId\"\xc1\x01\n" +
	"\x14BatchValidateRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12a\n" +
	"\ftransactions\x18\x02 \x03(\v2=.fintech.transaction_validation.v1.ValidateTransactionRequestR\ftransactions\x12-\n" +
	"\x13stop_on_first_error\x18\x03 \x01(\bR\x10stopOnFirstError\"\x84\x03\n" +
	"\x15BatchValidateResponse\x12M\n" +
	"\aresults\x18\x01 \x03(\x0e23.fintech.transaction_validation.v1.ValidationResultR\aresults\x12\x1f\n" +
	"\vvalid_count\x18\x02 \x01(\x05R\n" +
	"validCount\x12#\n" +
	"\rinvalid_count\x18\x03 \x01(\x05R\finvalidCount\x12#\n" +
	"\rwarning_count\x18\x04 \x01(\x05R\fwarningCount\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1d\n" +
	"\n" +
	"total_fees\x18\x06 \x01(\x01R\ttotalFees\x12%\n" +
	"\x0ebatch_warnings\x18\a \x03(\tR\rbatchWarnings\x12H\n" +
	"\x12batch_validated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10batchValidatedAt\"\xde\x01\n" +
	"\x0fValidationError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12Q\n" +
	"\bseverity\x18\x04 \x01(\x0e25.fintech.transaction_validation.v1.ValidationSeverityR\bseverity\x12\x1e\n" +
	"\n" +
	"suggestion\x18\x05 \x01(\tR\n" +
	"suggestion\"\xa2\x02\n" +
	"\x0fTransactionFees\x12\x19\n" +
	"\bbase_fee\x18\x01 \x01(\x01R\abaseFee\x12%\n" +
	"\x0eprocessing_fee\x18\x02 \x01(\x01R\rprocessingFee\x12\x15\n" +
	"\x06fx_fee\x18\x03 \x01(\x01R\x05fxFee\x12%\n" +
	"\x0ecompliance_fee\x18\x04 \x01(\x01R\rcomplianceFee\x12\x1b\n" +
	"\ttotal_fee\x18\x05 \x01(\x01R\btotalFee\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12V\n" +
	"\x0efee_components\x18\a \x03(\v2/.fintech.transaction_validation.v1.FeeComponentR\rfeeComponents\"p\n" +
	"\fFeeComponent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\"\xdb\x01\n" +
	"\x0fComplianceCheck\x12\x16\n" +
	"\x06passed\x18\x01 \x01(\bR\x06passed\x12)\n" +
	"\x10compliance_level\x18\x02 \x01(\tR\x0fcomplianceLevel\x12\x14\n" +
	"\x05flags\x18\x03 \x03(\tR\x05flags\x12\x1d\n" +
	"\n" +
	"risk_score\x18\x04 \x01(\x05R\triskScore\x12!\n" +
	"\frequires_kyc\x18\x05 \x01(\bR\vrequiresKyc\x12-\n" +
	"\x12required_documents\x18\x06 \x03(\tR\x11requiredDocuments*\x9a\x01\n" +
	"\x10ValidationResult\x12!\n" +
	"\x1dVALIDATION_RESULT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VALIDATION_RESULT_VALID\x10\x01\x12\x1d\n" +
	"\x19VALIDATION_RESULT_INVALID\x10\x02\x12'\n" +
	"#VALIDATION_RESULT_REQUIRES_APPROVAL\x10\x03*\xb9\x01\n" +
	"\x12ValidationSeverity\x12#\n" +
	"\x1fVALIDATION_SEVERITY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18VALIDATION_SEVERITY_INFO\x10\x01\x12\x1f\n" +
	"\x1bVALIDATION_SEVERITY_WARNING\x10\x02\x12\x1d\n" +
	"\x19VALIDATION_SEVERITY_ERROR\x10\x03\x12 \n" +
	"\x1cVALIDATION_SEVERITY_CRITICAL\x10\x04*\xa9\x01\n" +
	"\vAccountType\x12\x1c\n" +
	"\x18ACCOUNT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ACCOUNT_TYPE_BANK\x10\x01\x12\x15\n" +
	"\x11ACCOUNT_TYPE_CASH\x10\x02\x12\x1b\n" +
	"\x17ACCOUNT_TYPE_INVESTMENT\x10\x03\x12\x17\n" +
	"\x13ACCOUNT_TYPE_CREDIT\x10\x04\x12\x18\n" +
	"\x14ACCOUNT_TYPE_SAVINGS\x10\x052\xc6\x02\n" +
	"\x1cTransactionValidationService\x12\x94\x01\n" +
	"\x13ValidateTransaction\x12=.fintech.transaction_validation.v1.ValidateTransactionRequest\x1a>.fintech.transaction_validation.v1.ValidateTransactionResponse\x12\x8e\x01\n" +
	"\x19BatchValidateTransactions\x127.fintech.transaction_validation.v1.BatchValidateRequest\x1a8.fintech.transaction_validation.v1.BatchValidateResponseB!Z\x1ffintech-api/proto/gen/protob\x06proto3"

var (
	file_transaction_validation_proto_rawDescOnce sync.Once
	file_transaction_validation_proto_rawDescData []byte
)

func file_transaction_validation_proto_rawDescGZIP() []byte {
	file_transaction_validation_proto_rawDescOnce.Do(func() {
		file_transaction_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_transaction_validation_proto_rawDesc), len(file_transaction_validation_proto_rawDesc)))
	})
	return file_transaction_validation_proto_rawDescData
}

var file_transaction_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_transaction_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_transaction_validation_proto_goTypes = []any{
	(ValidationResult)(0),               // 0: fintech.transaction_validation.v1.ValidationResult
	(ValidationSeverity)(0),             // 1: fintech.transaction_validation.v1.ValidationSeverity
	(AccountType)(0),                    // 2: fintech.transaction_validation.v1.AccountType
	(*ValidateTransactionRequest)(nil),  // 3: fintech.transaction_validation.v1.ValidateTransactionRequest
	(*ValidateTransactionResponse)(nil), // 4: fintech.transaction_validation.v1.ValidateTransactionResponse
	(*BatchValidateRequest)(nil),        // 5: fintech.transaction_validation.v1.BatchValidateRequest
	(*BatchValidateResponse)(nil),       // 6: fintech.transaction_validation.v1.BatchValidateResponse
	(*ValidationError)(nil),             // 7: fintech.transaction_validation.v1.ValidationError
	(*TransactionFees)(nil),             // 8: fintech.transaction_validation.v1.TransactionFees
	(*FeeComponent)(nil),                // 9: fintech.transaction_validation.v1.FeeComponent
	(*ComplianceCheck)(nil),             // 10: fintech.transaction_validation.v1.ComplianceCheck
	nil,                                 // 11: fintech.transaction_validation.v1.ValidateTransactionRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_transaction_validation_proto_depIdxs = []int32{
	11, // 0: fintech.transaction_validation.v1.ValidateTransactionRequest.metadata:type_name -> fintech.transaction_validation.v1.ValidateTransactionRequest.MetadataEntry
	0,  // 1: fintech.transaction_validation.v1.ValidateTransactionResponse.result:type_name -> fintech.transaction_validation.v1.ValidationResult
	7,  // 2: fintech.transaction_validation.v1.ValidateTransactionResponse.validation_errors:type_name -> fintech.transaction_validation.v1.ValidationError
	8,  // 3: fintech.transaction_validation.v1.ValidateTransactionResponse.estimated_fees:type_name -> fintech.transaction_validation.v1.TransactionFees
	10, // 4: fintech.transaction_validation.v1.ValidateTransactionResponse.compliance_check:type_name -> fintech.transaction_validation.v1.ComplianceCheck
	12, // 5: fintech.transaction_validation.v1.ValidateTransactionResponse.validated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: fintech.transaction_validation.v1.BatchValidateRequest.transactions:type_name -> fintech.transaction_validation.v1.ValidateTransactionRequest
	0,  // 7: fintech.transaction_validation.v1.BatchValidateResponse.results:type_name -> fintech.transaction_validation.v1.ValidationResult
	12, // 8: fintech.transaction_validation.v1.BatchValidateResponse.batch_validated_at:type_name -> google.protobuf.Timestamp
	1,  // 9: fintech.transaction_validation.v1.ValidationError.severity:type_name -> fintech.transaction_validation.v1.ValidationSeverity
	9,  // 10: fintech.transaction_validation.v1.TransactionFees.fee_components:type_name -> fintech.transaction_validation.v1.FeeComponent
	3,  // 11: fintech.transaction_validation.v1.TransactionValidationService.ValidateTransaction:input_type -> fintech.transaction_validation.v1.ValidateTransactionRequest
	5,  // 12: fintech.transaction_validation.v1.TransactionValidationService.BatchValidateTransactions:input_type -> fintech.transaction_validation.v1.BatchValidateRequest
	4,  // 13: fintech.transaction_validation.v1.TransactionValidationService.ValidateTransaction:output_type -> fintech.transaction_validation.v1.ValidateTransactionResponse
	6,  // 14: fintech.transaction_validation.v1.TransactionValidationService.BatchValidateTransactions:output_type -> fintech.transaction_validation.v1.BatchValidateResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_transaction_validation_proto_init() }
func file_transaction_validation_proto_init() {
	if File_transaction_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_transaction_validation_proto_rawDesc), len(file_transaction_validation_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_transaction_validation_proto_goTypes,
		DependencyIndexes: file_transaction_validation_proto_depIdxs,
		EnumInfos:         file_transaction_validation_proto_enumTypes,
		MessageInfos:      file_transaction_validation_proto_msgTypes,
	}.Build()
	File_transaction_validation_proto = out.File
	file_transaction_validation_proto_goTypes = nil
	file_transaction_validation_proto_depIdxs = nil
}
