// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: webhook.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Webhook event types
type WebhookEventType int32

const (
	WebhookEventType_WEBHOOK_EVENT_TYPE_UNSPECIFIED       WebhookEventType = 0
	WebhookEventType_WEBHOOK_EVENT_TYPE_PAYMENT_CREATED   WebhookEventType = 1
	WebhookEventType_WEBHOOK_EVENT_TYPE_PAYMENT_UPDATED   WebhookEventType = 2
	WebhookEventType_WEBHOOK_EVENT_TYPE_PAYMENT_COMPLETED WebhookEventType = 3
	WebhookEventType_WEBHOOK_EVENT_TYPE_PAYMENT_FAILED    WebhookEventType = 4
	WebhookEventType_WEBHOOK_EVENT_TYPE_ACCOUNT_CREATED   WebhookEventType = 5
	WebhookEventType_WEBHOOK_EVENT_TYPE_ACCOUNT_UPDATED   WebhookEventType = 6
	WebhookEventType_WEBHOOK_EVENT_TYPE_KYC_VERIFIED      WebhookEventType = 7
	WebhookEventType_WEBHOOK_EVENT_TYPE_KYC_REJECTED      WebhookEventType = 8
	WebhookEventType_WEBHOOK_EVENT_TYPE_RECON_FAILED      WebhookEventType = 9
	WebhookEventType_WEBHOOK_EVENT_TYPE_RECON_COMPLETED   WebhookEventType = 10
	WebhookEventType_WEBHOOK_EVENT_TYPE_COMPLIANCE_ALERT  WebhookEventType = 11
)

// Enum value maps for WebhookEventType.
var (
	WebhookEventType_name = map[int32]string{
		0:  "WEBHOOK_EVENT_TYPE_UNSPECIFIED",
		1:  "WEBHOOK_EVENT_TYPE_PAYMENT_CREATED",
		2:  "WEBHOOK_EVENT_TYPE_PAYMENT_UPDATED",
		3:  "WEBHOOK_EVENT_TYPE_PAYMENT_COMPLETED",
		4:  "WEBHOOK_EVENT_TYPE_PAYMENT_FAILED",
		5:  "WEBHOOK_EVENT_TYPE_ACCOUNT_CREATED",
		6:  "WEBHOOK_EVENT_TYPE_ACCOUNT_UPDATED",
		7:  "WEBHOOK_EVENT_TYPE_KYC_VERIFIED",
		8:  "WEBHOOK_EVENT_TYPE_KYC_REJECTED",
		9:  "WEBHOOK_EVENT_TYPE_RECON_FAILED",
		10: "WEBHOOK_EVENT_TYPE_RECON_COMPLETED",
		11: "WEBHOOK_EVENT_TYPE_COMPLIANCE_ALERT",
	}
	WebhookEventType_value = map[string]int32{
		"WEBHOOK_EVENT_TYPE_UNSPECIFIED":       0,
		"WEBHOOK_EVENT_TYPE_PAYMENT_CREATED":   1,
		"WEBHOOK_EVENT_TYPE_PAYMENT_UPDATED":   2,
		"WEBHOOK_EVENT_TYPE_PAYMENT_COMPLETED": 3,
		"WEBHOOK_EVENT_TYPE_PAYMENT_FAILED":    4,
		"WEBHOOK_EVENT_TYPE_ACCOUNT_CREATED":   5,
		"WEBHOOK_EVENT_TYPE_ACCOUNT_UPDATED":   6,
		"WEBHOOK_EVENT_TYPE_KYC_VERIFIED":      7,
		"WEBHOOK_EVENT_TYPE_KYC_REJECTED":      8,
		"WEBHOOK_EVENT_TYPE_RECON_FAILED":      9,
		"WEBHOOK_EVENT_TYPE_RECON_COMPLETED":   10,
		"WEBHOOK_EVENT_TYPE_COMPLIANCE_ALERT":  11,
	}
)

func (x WebhookEventType) Enum() *WebhookEventType {
	p := new(WebhookEventType)
	*p = x
	return p
}

func (x WebhookEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_webhook_proto_enumTypes[0].Descriptor()
}

func (WebhookEventType) Type() protoreflect.EnumType {
	return &file_webhook_proto_enumTypes[0]
}

func (x WebhookEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookEventType.Descriptor instead.
func (WebhookEventType) EnumDescriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{0}
}

// Webhook status
type WebhookStatus int32

const (
	WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED WebhookStatus = 0
	WebhookStatus_WEBHOOK_STATUS_ACTIVE      WebhookStatus = 1
	WebhookStatus_WEBHOOK_STATUS_INACTIVE    WebhookStatus = 2
	WebhookStatus_WEBHOOK_STATUS_FAILED      WebhookStatus = 3
	WebhookStatus_WEBHOOK_STATUS_SUSPENDED   WebhookStatus = 4
)

// Enum value maps for WebhookStatus.
var (
	WebhookStatus_name = map[int32]string{
		0: "WEBHOOK_STATUS_UNSPECIFIED",
		1: "WEBHOOK_STATUS_ACTIVE",
		2: "WEBHOOK_STATUS_INACTIVE",
		3: "WEBHOOK_STATUS_FAILED",
		4: "WEBHOOK_STATUS_SUSPENDED",
	}
	WebhookStatus_value = map[string]int32{
		"WEBHOOK_STATUS_UNSPECIFIED": 0,
		"WEBHOOK_STATUS_ACTIVE":      1,
		"WEBHOOK_STATUS_INACTIVE":    2,
		"WEBHOOK_STATUS_FAILED":      3,
		"WEBHOOK_STATUS_SUSPENDED":   4,
	}
)

func (x WebhookStatus) Enum() *WebhookStatus {
	p := new(WebhookStatus)
	*p = x
	return p
}

func (x WebhookStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WebhookStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_webhook_proto_enumTypes[1].Descriptor()
}

func (WebhookStatus) Type() protoreflect.EnumType {
	return &file_webhook_proto_enumTypes[1]
}

func (x WebhookStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WebhookStatus.Descriptor instead.
func (WebhookStatus) EnumDescriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{1}
}

// Webhook configuration
type Webhook struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WebhookId            string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url                  string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Events               []WebhookEventType     `protobuf:"varint,4,rep,packed,name=events,proto3,enum=fintech.webhook.v1.WebhookEventType" json:"events,omitempty"`
	Status               WebhookStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=fintech.webhook.v1.WebhookStatus" json:"status,omitempty"`
	SharedSecret         string                 `protobuf:"bytes,6,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`                                             // For signature verification
	Headers              map[string]string      `protobuf:"bytes,7,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Custom headers
	TimeoutSeconds       int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	RetryCount           int32                  `protobuf:"varint,9,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	VerifySsl            bool                   `protobuf:"varint,10,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastTriggered        *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=last_triggered,json=lastTriggered,proto3" json:"last_triggered,omitempty"`
	TotalDeliveries      int32                  `protobuf:"varint,14,opt,name=total_deliveries,json=totalDeliveries,proto3" json:"total_deliveries,omitempty"`
	SuccessfulDeliveries int32                  `protobuf:"varint,15,opt,name=successful_deliveries,json=successfulDeliveries,proto3" json:"successful_deliveries,omitempty"`
	FailedDeliveries     int32                  `protobuf:"varint,16,opt,name=failed_deliveries,json=failedDeliveries,proto3" json:"failed_deliveries,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Webhook) Reset() {
	*x = Webhook{}
	mi := &file_webhook_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Webhook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Webhook) ProtoMessage() {}

func (x *Webhook) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Webhook.ProtoReflect.Descriptor instead.
func (*Webhook) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{0}
}

func (x *Webhook) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *Webhook) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Webhook) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Webhook) GetEvents() []WebhookEventType {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Webhook) GetStatus() WebhookStatus {
	if x != nil {
		return x.Status
	}
	return WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED
}

func (x *Webhook) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *Webhook) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *Webhook) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *Webhook) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *Webhook) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

func (x *Webhook) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Webhook) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Webhook) GetLastTriggered() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTriggered
	}
	return nil
}

func (x *Webhook) GetTotalDeliveries() int32 {
	if x != nil {
		return x.TotalDeliveries
	}
	return 0
}

func (x *Webhook) GetSuccessfulDeliveries() int32 {
	if x != nil {
		return x.SuccessfulDeliveries
	}
	return 0
}

func (x *Webhook) GetFailedDeliveries() int32 {
	if x != nil {
		return x.FailedDeliveries
	}
	return 0
}

// Webhook delivery log
type WebhookDelivery struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId     string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	WebhookId      string                 `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	EventType      WebhookEventType       `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=fintech.webhook.v1.WebhookEventType" json:"event_type,omitempty"`
	Payload        string                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // JSON payload sent
	ResponseStatus int32                  `protobuf:"varint,5,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseBody   string                 `protobuf:"bytes,6,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseTimeMs float64                `protobuf:"fixed64,7,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Successful     bool                   `protobuf:"varint,8,opt,name=successful,proto3" json:"successful,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,9,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AttemptNumber  int32                  `protobuf:"varint,10,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	AttemptedAt    *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WebhookDelivery) Reset() {
	*x = WebhookDelivery{}
	mi := &file_webhook_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDelivery) ProtoMessage() {}

func (x *WebhookDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDelivery.ProtoReflect.Descriptor instead.
func (*WebhookDelivery) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *WebhookDelivery) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *WebhookDelivery) GetEventType() WebhookEventType {
	if x != nil {
		return x.EventType
	}
	return WebhookEventType_WEBHOOK_EVENT_TYPE_UNSPECIFIED
}

func (x *WebhookDelivery) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *WebhookDelivery) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *WebhookDelivery) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *WebhookDelivery) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *WebhookDelivery) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *WebhookDelivery) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WebhookDelivery) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *WebhookDelivery) GetAttemptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttemptedAt
	}
	return nil
}

// Request/Response messages
type RegisterWebhookRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Events         []WebhookEventType     `protobuf:"varint,3,rep,packed,name=events,proto3,enum=fintech.webhook.v1.WebhookEventType" json:"events,omitempty"`
	Headers        map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Optional custom headers
	TimeoutSeconds int32                  `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`                                      // Optional, defaults to 30
	VerifySsl      bool                   `protobuf:"varint,6,opt,name=verify_ssl,json=verifySsl,proto3" json:"verify_ssl,omitempty"`                                                     // Optional, defaults to true
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterWebhookRequest) Reset() {
	*x = RegisterWebhookRequest{}
	mi := &file_webhook_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWebhookRequest) ProtoMessage() {}

func (x *RegisterWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWebhookRequest.ProtoReflect.Descriptor instead.
func (*RegisterWebhookRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWebhookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterWebhookRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *RegisterWebhookRequest) GetEvents() []WebhookEventType {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *RegisterWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *RegisterWebhookRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *RegisterWebhookRequest) GetVerifySsl() bool {
	if x != nil {
		return x.VerifySsl
	}
	return false
}

type RegisterWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhook       *Webhook               `protobuf:"bytes,1,opt,name=webhook,proto3" json:"webhook,omitempty"`
	SharedSecret  string                 `protobuf:"bytes,2,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"` // Secret for signature verification
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWebhookResponse) Reset() {
	*x = RegisterWebhookResponse{}
	mi := &file_webhook_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWebhookResponse) ProtoMessage() {}

func (x *RegisterWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWebhookResponse.ProtoReflect.Descriptor instead.
func (*RegisterWebhookResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWebhookResponse) GetWebhook() *Webhook {
	if x != nil {
		return x.Webhook
	}
	return nil
}

func (x *RegisterWebhookResponse) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

func (x *RegisterWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // For authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookRequest) Reset() {
	*x = DeleteWebhookRequest{}
	mi := &file_webhook_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookRequest) ProtoMessage() {}

func (x *DeleteWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebhookRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DeleteWebhookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DeleteWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteWebhookResponse) Reset() {
	*x = DeleteWebhookResponse{}
	mi := &file_webhook_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebhookResponse) ProtoMessage() {}

func (x *DeleteWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebhookResponse.ProtoReflect.Descriptor instead.
func (*DeleteWebhookResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DeleteWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	StatusFilter  WebhookStatus          `protobuf:"varint,2,opt,name=status_filter,json=statusFilter,proto3,enum=fintech.webhook.v1.WebhookStatus" json:"status_filter,omitempty"` // Optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksRequest) Reset() {
	*x = ListWebhooksRequest{}
	mi := &file_webhook_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksRequest) ProtoMessage() {}

func (x *ListWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{6}
}

func (x *ListWebhooksRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListWebhooksRequest) GetStatusFilter() WebhookStatus {
	if x != nil {
		return x.StatusFilter
	}
	return WebhookStatus_WEBHOOK_STATUS_UNSPECIFIED
}

type ListWebhooksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Webhooks      []*Webhook             `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWebhooksResponse) Reset() {
	*x = ListWebhooksResponse{}
	mi := &file_webhook_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWebhooksResponse) ProtoMessage() {}

func (x *ListWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{7}
}

func (x *ListWebhooksResponse) GetWebhooks() []*Webhook {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ListWebhooksResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TestWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	EventType     WebhookEventType       `protobuf:"varint,2,opt,name=event_type,json=eventType,proto3,enum=fintech.webhook.v1.WebhookEventType" json:"event_type,omitempty"` // Event type to simulate
	TestPayload   string                 `protobuf:"bytes,3,opt,name=test_payload,json=testPayload,proto3" json:"test_payload,omitempty"`                                     // Optional custom payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookRequest) Reset() {
	*x = TestWebhookRequest{}
	mi := &file_webhook_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookRequest) ProtoMessage() {}

func (x *TestWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookRequest.ProtoReflect.Descriptor instead.
func (*TestWebhookRequest) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{8}
}

func (x *TestWebhookRequest) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *TestWebhookRequest) GetEventType() WebhookEventType {
	if x != nil {
		return x.EventType
	}
	return WebhookEventType_WEBHOOK_EVENT_TYPE_UNSPECIFIED
}

func (x *TestWebhookRequest) GetTestPayload() string {
	if x != nil {
		return x.TestPayload
	}
	return ""
}

type TestWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivery      *WebhookDelivery       `protobuf:"bytes,1,opt,name=delivery,proto3" json:"delivery,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestWebhookResponse) Reset() {
	*x = TestWebhookResponse{}
	mi := &file_webhook_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestWebhookResponse) ProtoMessage() {}

func (x *TestWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestWebhookResponse.ProtoReflect.Descriptor instead.
func (*TestWebhookResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{9}
}

func (x *TestWebhookResponse) GetDelivery() *WebhookDelivery {
	if x != nil {
		return x.Delivery
	}
	return nil
}

func (x *TestWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Bidirectional streaming messages for WebhookDebugger
type WebhookDebugCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Command:
	//
	//	*WebhookDebugCommand_StartDebugging
	//	*WebhookDebugCommand_StopDebugging
	//	*WebhookDebugCommand_TestEndpoint
	//	*WebhookDebugCommand_UpdateConfig
	//	*WebhookDebugCommand_RetryDelivery
	Command       isWebhookDebugCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookDebugCommand) Reset() {
	*x = WebhookDebugCommand{}
	mi := &file_webhook_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDebugCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDebugCommand) ProtoMessage() {}

func (x *WebhookDebugCommand) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDebugCommand.ProtoReflect.Descriptor instead.
func (*WebhookDebugCommand) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{10}
}

func (x *WebhookDebugCommand) GetCommand() isWebhookDebugCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *WebhookDebugCommand) GetStartDebugging() *StartDebugging {
	if x != nil {
		if x, ok := x.Command.(*WebhookDebugCommand_StartDebugging); ok {
			return x.StartDebugging
		}
	}
	return nil
}

func (x *WebhookDebugCommand) GetStopDebugging() *StopDebugging {
	if x != nil {
		if x, ok := x.Command.(*WebhookDebugCommand_StopDebugging); ok {
			return x.StopDebugging
		}
	}
	return nil
}

func (x *WebhookDebugCommand) GetTestEndpoint() *TestEndpoint {
	if x != nil {
		if x, ok := x.Command.(*WebhookDebugCommand_TestEndpoint); ok {
			return x.TestEndpoint
		}
	}
	return nil
}

func (x *WebhookDebugCommand) GetUpdateConfig() *UpdateConfig {
	if x != nil {
		if x, ok := x.Command.(*WebhookDebugCommand_UpdateConfig); ok {
			return x.UpdateConfig
		}
	}
	return nil
}

func (x *WebhookDebugCommand) GetRetryDelivery() *RetryDelivery {
	if x != nil {
		if x, ok := x.Command.(*WebhookDebugCommand_RetryDelivery); ok {
			return x.RetryDelivery
		}
	}
	return nil
}

type isWebhookDebugCommand_Command interface {
	isWebhookDebugCommand_Command()
}

type WebhookDebugCommand_StartDebugging struct {
	StartDebugging *StartDebugging `protobuf:"bytes,1,opt,name=start_debugging,json=startDebugging,proto3,oneof"`
}

type WebhookDebugCommand_StopDebugging struct {
	StopDebugging *StopDebugging `protobuf:"bytes,2,opt,name=stop_debugging,json=stopDebugging,proto3,oneof"`
}

type WebhookDebugCommand_TestEndpoint struct {
	TestEndpoint *TestEndpoint `protobuf:"bytes,3,opt,name=test_endpoint,json=testEndpoint,proto3,oneof"`
}

type WebhookDebugCommand_UpdateConfig struct {
	UpdateConfig *UpdateConfig `protobuf:"bytes,4,opt,name=update_config,json=updateConfig,proto3,oneof"`
}

type WebhookDebugCommand_RetryDelivery struct {
	RetryDelivery *RetryDelivery `protobuf:"bytes,5,opt,name=retry_delivery,json=retryDelivery,proto3,oneof"`
}

func (*WebhookDebugCommand_StartDebugging) isWebhookDebugCommand_Command() {}

func (*WebhookDebugCommand_StopDebugging) isWebhookDebugCommand_Command() {}

func (*WebhookDebugCommand_TestEndpoint) isWebhookDebugCommand_Command() {}

func (*WebhookDebugCommand_UpdateConfig) isWebhookDebugCommand_Command() {}

func (*WebhookDebugCommand_RetryDelivery) isWebhookDebugCommand_Command() {}

type StartDebugging struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WebhookId            string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	CaptureRequests      bool                   `protobuf:"varint,2,opt,name=capture_requests,json=captureRequests,proto3" json:"capture_requests,omitempty"`
	CaptureResponses     bool                   `protobuf:"varint,3,opt,name=capture_responses,json=captureResponses,proto3" json:"capture_responses,omitempty"`
	EnableVerboseLogging bool                   `protobuf:"varint,4,opt,name=enable_verbose_logging,json=enableVerboseLogging,proto3" json:"enable_verbose_logging,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *StartDebugging) Reset() {
	*x = StartDebugging{}
	mi := &file_webhook_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDebugging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDebugging) ProtoMessage() {}

func (x *StartDebugging) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDebugging.ProtoReflect.Descriptor instead.
func (*StartDebugging) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{11}
}

func (x *StartDebugging) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *StartDebugging) GetCaptureRequests() bool {
	if x != nil {
		return x.CaptureRequests
	}
	return false
}

func (x *StartDebugging) GetCaptureResponses() bool {
	if x != nil {
		return x.CaptureResponses
	}
	return false
}

func (x *StartDebugging) GetEnableVerboseLogging() bool {
	if x != nil {
		return x.EnableVerboseLogging
	}
	return false
}

type StopDebugging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDebugging) Reset() {
	*x = StopDebugging{}
	mi := &file_webhook_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDebugging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDebugging) ProtoMessage() {}

func (x *StopDebugging) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDebugging.ProtoReflect.Descriptor instead.
func (*StopDebugging) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{12}
}

func (x *StopDebugging) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TestEndpoint struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Url            string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	EventType      WebhookEventType       `protobuf:"varint,3,opt,name=event_type,json=eventType,proto3,enum=fintech.webhook.v1.WebhookEventType" json:"event_type,omitempty"`
	CustomPayload  string                 `protobuf:"bytes,4,opt,name=custom_payload,json=customPayload,proto3" json:"custom_payload,omitempty"`
	CustomHeaders  map[string]string      `protobuf:"bytes,5,rep,name=custom_headers,json=customHeaders,proto3" json:"custom_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TimeoutSeconds int32                  `protobuf:"varint,6,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TestEndpoint) Reset() {
	*x = TestEndpoint{}
	mi := &file_webhook_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestEndpoint) ProtoMessage() {}

func (x *TestEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestEndpoint.ProtoReflect.Descriptor instead.
func (*TestEndpoint) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{13}
}

func (x *TestEndpoint) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *TestEndpoint) GetEventType() WebhookEventType {
	if x != nil {
		return x.EventType
	}
	return WebhookEventType_WEBHOOK_EVENT_TYPE_UNSPECIFIED
}

func (x *TestEndpoint) GetCustomPayload() string {
	if x != nil {
		return x.CustomPayload
	}
	return ""
}

func (x *TestEndpoint) GetCustomHeaders() map[string]string {
	if x != nil {
		return x.CustomHeaders
	}
	return nil
}

func (x *TestEndpoint) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type UpdateConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebhookId     string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	NewUrl        string                 `protobuf:"bytes,2,opt,name=new_url,json=newUrl,proto3" json:"new_url,omitempty"`
	NewHeaders    map[string]string      `protobuf:"bytes,3,rep,name=new_headers,json=newHeaders,proto3" json:"new_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NewTimeout    int32                  `protobuf:"varint,4,opt,name=new_timeout,json=newTimeout,proto3" json:"new_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfig) Reset() {
	*x = UpdateConfig{}
	mi := &file_webhook_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfig) ProtoMessage() {}

func (x *UpdateConfig) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfig.ProtoReflect.Descriptor instead.
func (*UpdateConfig) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateConfig) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *UpdateConfig) GetNewUrl() string {
	if x != nil {
		return x.NewUrl
	}
	return ""
}

func (x *UpdateConfig) GetNewHeaders() map[string]string {
	if x != nil {
		return x.NewHeaders
	}
	return nil
}

func (x *UpdateConfig) GetNewTimeout() int32 {
	if x != nil {
		return x.NewTimeout
	}
	return 0
}

type RetryDelivery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId    string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	ForceRetry    bool                   `protobuf:"varint,2,opt,name=force_retry,json=forceRetry,proto3" json:"force_retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryDelivery) Reset() {
	*x = RetryDelivery{}
	mi := &file_webhook_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryDelivery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryDelivery) ProtoMessage() {}

func (x *RetryDelivery) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryDelivery.ProtoReflect.Descriptor instead.
func (*RetryDelivery) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{15}
}

func (x *RetryDelivery) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *RetryDelivery) GetForceRetry() bool {
	if x != nil {
		return x.ForceRetry
	}
	return false
}

type WebhookDebugResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Response:
	//
	//	*WebhookDebugResponse_DeliveryAttempt
	//	*WebhookDebugResponse_DebugStats
	//	*WebhookDebugResponse_DebugLog
	//	*WebhookDebugResponse_DebugStatus
	Response      isWebhookDebugResponse_Response `protobuf_oneof:"response"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookDebugResponse) Reset() {
	*x = WebhookDebugResponse{}
	mi := &file_webhook_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookDebugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookDebugResponse) ProtoMessage() {}

func (x *WebhookDebugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookDebugResponse.ProtoReflect.Descriptor instead.
func (*WebhookDebugResponse) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{16}
}

func (x *WebhookDebugResponse) GetResponse() isWebhookDebugResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *WebhookDebugResponse) GetDeliveryAttempt() *DeliveryAttempt {
	if x != nil {
		if x, ok := x.Response.(*WebhookDebugResponse_DeliveryAttempt); ok {
			return x.DeliveryAttempt
		}
	}
	return nil
}

func (x *WebhookDebugResponse) GetDebugStats() *DebugStats {
	if x != nil {
		if x, ok := x.Response.(*WebhookDebugResponse_DebugStats); ok {
			return x.DebugStats
		}
	}
	return nil
}

func (x *WebhookDebugResponse) GetDebugLog() *DebugLog {
	if x != nil {
		if x, ok := x.Response.(*WebhookDebugResponse_DebugLog); ok {
			return x.DebugLog
		}
	}
	return nil
}

func (x *WebhookDebugResponse) GetDebugStatus() *DebugStatus {
	if x != nil {
		if x, ok := x.Response.(*WebhookDebugResponse_DebugStatus); ok {
			return x.DebugStatus
		}
	}
	return nil
}

type isWebhookDebugResponse_Response interface {
	isWebhookDebugResponse_Response()
}

type WebhookDebugResponse_DeliveryAttempt struct {
	DeliveryAttempt *DeliveryAttempt `protobuf:"bytes,1,opt,name=delivery_attempt,json=deliveryAttempt,proto3,oneof"`
}

type WebhookDebugResponse_DebugStats struct {
	DebugStats *DebugStats `protobuf:"bytes,2,opt,name=debug_stats,json=debugStats,proto3,oneof"`
}

type WebhookDebugResponse_DebugLog struct {
	DebugLog *DebugLog `protobuf:"bytes,3,opt,name=debug_log,json=debugLog,proto3,oneof"`
}

type WebhookDebugResponse_DebugStatus struct {
	DebugStatus *DebugStatus `protobuf:"bytes,4,opt,name=debug_status,json=debugStatus,proto3,oneof"`
}

func (*WebhookDebugResponse_DeliveryAttempt) isWebhookDebugResponse_Response() {}

func (*WebhookDebugResponse_DebugStats) isWebhookDebugResponse_Response() {}

func (*WebhookDebugResponse_DebugLog) isWebhookDebugResponse_Response() {}

func (*WebhookDebugResponse_DebugStatus) isWebhookDebugResponse_Response() {}

type DeliveryAttempt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DeliveryId      string                 `protobuf:"bytes,1,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	WebhookId       string                 `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	Url             string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Method          string                 `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	RequestHeaders  map[string]string      `protobuf:"bytes,5,rep,name=request_headers,json=requestHeaders,proto3" json:"request_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	RequestBody     string                 `protobuf:"bytes,6,opt,name=request_body,json=requestBody,proto3" json:"request_body,omitempty"`
	ResponseStatus  int32                  `protobuf:"varint,7,opt,name=response_status,json=responseStatus,proto3" json:"response_status,omitempty"`
	ResponseHeaders map[string]string      `protobuf:"bytes,8,rep,name=response_headers,json=responseHeaders,proto3" json:"response_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResponseBody    string                 `protobuf:"bytes,9,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`
	ResponseTimeMs  float64                `protobuf:"fixed64,10,opt,name=response_time_ms,json=responseTimeMs,proto3" json:"response_time_ms,omitempty"`
	Successful      bool                   `protobuf:"varint,11,opt,name=successful,proto3" json:"successful,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,12,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AttemptedAt     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeliveryAttempt) Reset() {
	*x = DeliveryAttempt{}
	mi := &file_webhook_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAttempt) ProtoMessage() {}

func (x *DeliveryAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAttempt.ProtoReflect.Descriptor instead.
func (*DeliveryAttempt) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{17}
}

func (x *DeliveryAttempt) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DeliveryAttempt) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DeliveryAttempt) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DeliveryAttempt) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *DeliveryAttempt) GetRequestHeaders() map[string]string {
	if x != nil {
		return x.RequestHeaders
	}
	return nil
}

func (x *DeliveryAttempt) GetRequestBody() string {
	if x != nil {
		return x.RequestBody
	}
	return ""
}

func (x *DeliveryAttempt) GetResponseStatus() int32 {
	if x != nil {
		return x.ResponseStatus
	}
	return 0
}

func (x *DeliveryAttempt) GetResponseHeaders() map[string]string {
	if x != nil {
		return x.ResponseHeaders
	}
	return nil
}

func (x *DeliveryAttempt) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *DeliveryAttempt) GetResponseTimeMs() float64 {
	if x != nil {
		return x.ResponseTimeMs
	}
	return 0
}

func (x *DeliveryAttempt) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

func (x *DeliveryAttempt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryAttempt) GetAttemptedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AttemptedAt
	}
	return nil
}

type DebugStats struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	WebhookId           string                 `protobuf:"bytes,1,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	TotalAttempts       int32                  `protobuf:"varint,2,opt,name=total_attempts,json=totalAttempts,proto3" json:"total_attempts,omitempty"`
	SuccessfulAttempts  int32                  `protobuf:"varint,3,opt,name=successful_attempts,json=successfulAttempts,proto3" json:"successful_attempts,omitempty"`
	FailedAttempts      int32                  `protobuf:"varint,4,opt,name=failed_attempts,json=failedAttempts,proto3" json:"failed_attempts,omitempty"`
	AvgResponseTimeMs   float64                `protobuf:"fixed64,5,opt,name=avg_response_time_ms,json=avgResponseTimeMs,proto3" json:"avg_response_time_ms,omitempty"`
	SuccessRate         float64                `protobuf:"fixed64,6,opt,name=success_rate,json=successRate,proto3" json:"success_rate,omitempty"`
	StatusCodeBreakdown map[string]int32       `protobuf:"bytes,7,rep,name=status_code_breakdown,json=statusCodeBreakdown,proto3" json:"status_code_breakdown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // status_code -> count
	PeriodStart         *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd           *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DebugStats) Reset() {
	*x = DebugStats{}
	mi := &file_webhook_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugStats) ProtoMessage() {}

func (x *DebugStats) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugStats.ProtoReflect.Descriptor instead.
func (*DebugStats) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{18}
}

func (x *DebugStats) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DebugStats) GetTotalAttempts() int32 {
	if x != nil {
		return x.TotalAttempts
	}
	return 0
}

func (x *DebugStats) GetSuccessfulAttempts() int32 {
	if x != nil {
		return x.SuccessfulAttempts
	}
	return 0
}

func (x *DebugStats) GetFailedAttempts() int32 {
	if x != nil {
		return x.FailedAttempts
	}
	return 0
}

func (x *DebugStats) GetAvgResponseTimeMs() float64 {
	if x != nil {
		return x.AvgResponseTimeMs
	}
	return 0
}

func (x *DebugStats) GetSuccessRate() float64 {
	if x != nil {
		return x.SuccessRate
	}
	return 0
}

func (x *DebugStats) GetStatusCodeBreakdown() map[string]int32 {
	if x != nil {
		return x.StatusCodeBreakdown
	}
	return nil
}

func (x *DebugStats) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *DebugStats) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

type DebugLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "info", "warn", "error", "debug"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	WebhookId     string                 `protobuf:"bytes,3,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	DeliveryId    string                 `protobuf:"bytes,4,opt,name=delivery_id,json=deliveryId,proto3" json:"delivery_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugLog) Reset() {
	*x = DebugLog{}
	mi := &file_webhook_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugLog) ProtoMessage() {}

func (x *DebugLog) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugLog.ProtoReflect.Descriptor instead.
func (*DebugLog) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{19}
}

func (x *DebugLog) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DebugLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DebugLog) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DebugLog) GetDeliveryId() string {
	if x != nil {
		return x.DeliveryId
	}
	return ""
}

func (x *DebugLog) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *DebugLog) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type DebugStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IsDebugging       bool                   `protobuf:"varint,1,opt,name=is_debugging,json=isDebugging,proto3" json:"is_debugging,omitempty"`
	WebhookId         string                 `protobuf:"bytes,2,opt,name=webhook_id,json=webhookId,proto3" json:"webhook_id,omitempty"`
	ActiveConnections int32                  `protobuf:"varint,3,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	StartedAt         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Configuration     string                 `protobuf:"bytes,5,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Message           string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DebugStatus) Reset() {
	*x = DebugStatus{}
	mi := &file_webhook_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugStatus) ProtoMessage() {}

func (x *DebugStatus) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugStatus.ProtoReflect.Descriptor instead.
func (*DebugStatus) Descriptor() ([]byte, []int) {
	return file_webhook_proto_rawDescGZIP(), []int{20}
}

func (x *DebugStatus) GetIsDebugging() bool {
	if x != nil {
		return x.IsDebugging
	}
	return false
}

func (x *DebugStatus) GetWebhookId() string {
	if x != nil {
		return x.WebhookId
	}
	return ""
}

func (x *DebugStatus) GetActiveConnections() int32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *DebugStatus) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *DebugStatus) GetConfiguration() string {
	if x != nil {
		return x.Configuration
	}
	return ""
}

func (x *DebugStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_webhook_proto protoreflect.FileDescriptor

const file_webhook_proto_rawDesc = "" +
	"\n" +
	"\rwebhook.proto\x12\x12fintech.webhook.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x06\n" +
	"\aWebhook\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12<\n" +
	"\x06events\x18\x04 \x03(\x0e2$.fintech.webhook.v1.WebhookEventTypeR\x06events\x129\n" +
	"\x06status\x18\x05 \x01(\x0e2!.fintech.webhook.v1.WebhookStatusR\x06status\x12#\n" +
	"\rshared_secret\x18\x06 \x01(\tR\fsharedSecret\x12B\n" +
	"\aheaders\x18\a \x03(\v2(.fintech.webhook.v1.Webhook.HeadersEntryR\aheaders\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vretry_count\x18\t \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\n" +
	" \x01(\bR\tverifySsl\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12A\n" +
	"\x0elast_triggered\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\rlastTriggered\x12)\n" +
	"\x10total_deliveries\x18\x0e \x01(\x05R\x0ftotalDeliveries\x123\n" +
	"\x15successful_deliveries\x18\x0f \x01(\x05R\x14successfulDeliveries\x12+\n" +
	"\x11failed_deliveries\x18\x10 \x01(\x05R\x10failedDeliveries\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x03\n" +
	"\x0fWebhookDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tR\twebhookId\x12C\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2$.fintech.webhook.v1.WebhookEventTypeR\teventType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\tR\apayload\x12'\n" +
	"\x0fresponse_status\x18\x05 \x01(\x05R\x0eresponseStatus\x12#\n" +
	"\rresponse_body\x18\x06 \x01(\tR\fresponseBody\x12(\n" +
	"\x10response_time_ms\x18\a \x01(\x01R\x0eresponseTimeMs\x12\x1e\n" +
	"\n" +
	"successful\x18\b \x01(\bR\n" +
	"successful\x12#\n" +
	"\rerror_message\x18\t \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eattempt_number\x18\n" +
	" \x01(\x05R\rattemptNumber\x12=\n" +
	"\fattempted_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vattemptedAt\"\xd8\x02\n" +
	"\x16RegisterWebhookRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12<\n" +
	"\x06events\x18\x03 \x03(\x0e2$.fintech.webhook.v1.WebhookEventTypeR\x06events\x12Q\n" +
	"\aheaders\x18\x04 \x03(\v27.fintech.webhook.v1.RegisterWebhookRequest.HeadersEntryR\aheaders\x12'\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05R\x0etimeoutSeconds\x12\x1d\n" +
	"\n" +
	"verify_ssl\x18\x06 \x01(\bR\tverifySsl\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8f\x01\n" +
	"\x17RegisterWebhookResponse\x125\n" +
	"\awebhook\x18\x01 \x01(\v2\x1b.fintech.webhook.v1.WebhookR\awebhook\x12#\n" +
	"\rshared_secret\x18\x02 \x01(\tR\fsharedSecret\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"N\n" +
	"\x14DeleteWebhookRequest\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"K\n" +
	"\x15DeleteWebhookResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"v\n" +
	"\x13ListWebhooksRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12F\n" +
	"\rstatus_filter\x18\x02 \x01(\x0e2!.fintech.webhook.v1.WebhookStatusR\fstatusFilter\"p\n" +
	"\x14ListWebhooksResponse\x127\n" +
	"\bwebhooks\x18\x01 \x03(\v2\x1b.fintech.webhook.v1.WebhookR\bwebhooks\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"\x9b\x01\n" +
	"\x12TestWebhookRequest\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12C\n" +
	"\n" +
	"event_type\x18\x02 \x01(\x0e2$.fintech.webhook.v1.WebhookEventTypeR\teventType\x12!\n" +
	"\ftest_payload\x18\x03 \x01(\tR\vtestPayload\"\x8a\x01\n" +
	"\x13TestWebhookResponse\x12?\n" +
	"\bdelivery\x18\x01 \x01(\v2#.fintech.webhook.v1.WebhookDeliveryR\bdelivery\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\"\x99\x03\n" +
	"\x13WebhookDebugCommand\x12M\n" +
	"\x0fstart_debugging\x18\x01 \x01(\v2\".fintech.webhook.v1.StartDebuggingH\x00R\x0estartDebugging\x12J\n" +
	"\x0estop_debugging\x18\x02 \x01(\v2!.fintech.webhook.v1.StopDebuggingH\x00R\rstopDebugging\x12G\n" +
	"\rtest_endpoint\x18\x03 \x01(\v2 .fintech.webhook.v1.TestEndpointH\x00R\ftestEndpoint\x12G\n" +
	"\rupdate_config\x18\x04 \x01(\v2 .fintech.webhook.v1.UpdateConfigH\x00R\fupdateConfig\x12J\n" +
	"\x0eretry_delivery\x18\x05 \x01(\v2!.fintech.webhook.v1.RetryDeliveryH\x00R\rretryDeliveryB\t\n" +
	"\acommand\"\xbd\x01\n" +
	"\x0eStartDebugging\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12)\n" +
	"\x10capture_requests\x18\x02 \x01(\bR\x0fcaptureRequests\x12+\n" +
	"\x11capture_responses\x18\x03 \x01(\bR\x10captureResponses\x124\n" +
	"\x16enable_verbose_logging\x18\x04 \x01(\bR\x14enableVerboseLogging\"'\n" +
	"\rStopDebugging\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xd3\x02\n" +
	"\fTestEndpoint\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12C\n" +
	"\n" +
	"event_type\x18\x03 \x01(\x0e2$.fintech.webhook.v1.WebhookEventTypeR\teventType\x12%\n" +
	"\x0ecustom_payload\x18\x04 \x01(\tR\rcustomPayload\x12Z\n" +
	"\x0ecustom_headers\x18\x05 \x03(\v23.fintech.webhook.v1.TestEndpoint.CustomHeadersEntryR\rcustomHeaders\x12'\n" +
	"\x0ftimeout_seconds\x18\x06 \x01(\x05R\x0etimeoutSeconds\x1a@\n" +
	"\x12CustomHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\fUpdateConfig\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12\x17\n" +
	"\anew_url\x18\x02 \x01(\tR\x06newUrl\x12Q\n" +
	"\vnew_headers\x18\x03 \x03(\v20.fintech.webhook.v1.UpdateConfig.NewHeadersEntryR\n" +
	"newHeaders\x12\x1f\n" +
	"\vnew_timeout\x18\x04 \x01(\x05R\n" +
	"newTimeout\x1a=\n" +
	"\x0fNewHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\rRetryDelivery\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1f\n" +
	"\vforce_retry\x18\x02 \x01(\bR\n" +
	"forceRetry\"\xba\x02\n" +
	"\x14WebhookDebugResponse\x12P\n" +
	"\x10delivery_attempt\x18\x01 \x01(\v2#.fintech.webhook.v1.DeliveryAttemptH\x00R\x0fdeliveryAttempt\x12A\n" +
	"\vdebug_stats\x18\x02 \x01(\v2\x1e.fintech.webhook.v1.DebugStatsH\x00R\n" +
	"debugStats\x12;\n" +
	"\tdebug_log\x18\x03 \x01(\v2\x1c.fintech.webhook.v1.DebugLogH\x00R\bdebugLog\x12D\n" +
	"\fdebug_status\x18\x04 \x01(\v2\x1f.fintech.webhook.v1.DebugStatusH\x00R\vdebugStatusB\n" +
	"\n" +
	"\bresponse\"\xe8\x05\n" +
	"\x0fDeliveryAttempt\x12\x1f\n" +
	"\vdelivery_id\x18\x01 \x01(\tR\n" +
	"deliveryId\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tR\twebhookId\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x04 \x01(\tR\x06method\x12`\n" +
	"\x0frequest_headers\x18\x05 \x03(\v27.fintech.webhook.v1.DeliveryAttempt.RequestHeadersEntryR\x0erequestHeaders\x12!\n" +
	"\frequest_body\x18\x06 \x01(\tR\vrequestBody\x12'\n" +
	"\x0fresponse_status\x18\a \x01(\x05R\x0eresponseStatus\x12c\n" +
	"\x10response_headers\x18\b \x03(\v28.fintech.webhook.v1.DeliveryAttempt.ResponseHeadersEntryR\x0fresponseHeaders\x12#\n" +
	"\rresponse_body\x18\t \x01(\tR\fresponseBody\x12(\n" +
	"\x10response_time_ms\x18\n" +
	" \x01(\x01R\x0eresponseTimeMs\x12\x1e\n" +
	"\n" +
	"successful\x18\v \x01(\bR\n" +
	"successful\x12#\n" +
	"\rerror_message\x18\f \x01(\tR\ferrorMessage\x12=\n" +
	"\fattempted_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vattemptedAt\x1aA\n" +
	"\x13RequestHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14ResponseHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x04\n" +
	"\n" +
	"DebugStats\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x01 \x01(\tR\twebhookId\x12%\n" +
	"\x0etotal_attempts\x18\x02 \x01(\x05R\rtotalAttempts\x12/\n" +
	"\x13successful_attempts\x18\x03 \x01(\x05R\x12successfulAttempts\x12'\n" +
	"\x0ffailed_attempts\x18\x04 \x01(\x05R\x0efailedAttempts\x12/\n" +
	"\x14avg_response_time_ms\x18\x05 \x01(\x01R\x11avgResponseTimeMs\x12!\n" +
	"\fsuccess_rate\x18\x06 \x01(\x01R\vsuccessRate\x12k\n" +
	"\x15status_code_breakdown\x18\a \x03(\v27.fintech.webhook.v1.DebugStats.StatusCodeBreakdownEntryR\x13statusCodeBreakdown\x12=\n" +
	"\fperiod_start\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x1aF\n" +
	"\x18StatusCodeBreakdownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xb9\x02\n" +
	"\bDebugLog\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x03 \x01(\tR\twebhookId\x12\x1f\n" +
	"\vdelivery_id\x18\x04 \x01(\tR\n" +
	"deliveryId\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.fintech.webhook.v1.DebugLog.MetadataEntryR\bmetadata\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf9\x01\n" +
	"\vDebugStatus\x12!\n" +
	"\fis_debugging\x18\x01 \x01(\bR\visDebugging\x12\x1d\n" +
	"\n" +
	"webhook_id\x18\x02 \x01(\tR\twebhookId\x12-\n" +
	"\x12active_connections\x18\x03 \x01(\x05R\x11activeConnections\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12$\n" +
	"\rconfiguration\x18\x05 \x01(\tR\rconfiguration\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage*\xe7\x03\n" +
	"\x10WebhookEventType\x12\"\n" +
	"\x1eWEBHOOK_EVENT_TYPE_UNSPECIFIED\x10\x00\x12&\n" +
	"\"WEBHOOK_EVENT_TYPE_PAYMENT_CREATED\x10\x01\x12&\n" +
	"\"WEBHOOK_EVENT_TYPE_PAYMENT_UPDATED\x10\x02\x12(\n" +
	"$WEBHOOK_EVENT_TYPE_PAYMENT_COMPLETED\x10\x03\x12%\n" +
	"!WEBHOOK_EVENT_TYPE_PAYMENT_FAILED\x10\x04\x12&\n" +
	"\"WEBHOOK_EVENT_TYPE_ACCOUNT_CREATED\x10\x05\x12&\n" +
	"\"WEBHOOK_EVENT_TYPE_ACCOUNT_UPDATED\x10\x06\x12#\n" +
	"\x1fWEBHOOK_EVENT_TYPE_KYC_VERIFIED\x10\a\x12#\n" +
	"\x1fWEBHOOK_EVENT_TYPE_KYC_REJECTED\x10\b\x12#\n" +
	"\x1fWEBHOOK_EVENT_TYPE_RECON_FAILED\x10\t\x12&\n" +
	"\"WEBHOOK_EVENT_TYPE_RECON_COMPLETED\x10\n" +
	"\x12'\n" +
	"#WEBHOOK_EVENT_TYPE_COMPLIANCE_ALERT\x10\v*\xa0\x01\n" +
	"\rWebhookStatus\x12\x1e\n" +
	"\x1aWEBHOOK_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15WEBHOOK_STATUS_ACTIVE\x10\x01\x12\x1b\n" +
	"\x17WEBHOOK_STATUS_INACTIVE\x10\x02\x12\x19\n" +
	"\x15WEBHOOK_STATUS_FAILED\x10\x03\x12\x1c\n" +
	"\x18WEBHOOK_STATUS_SUSPENDED\x10\x042\xf2\x03\n" +
	"\x0eWebhookService\x12c\n" +
	"\bRegister\x12*.fintech.webhook.v1.RegisterWebhookRequest\x1a+.fintech.webhook.v1.RegisterWebhookResponse\x12]\n" +
	"\x06Delete\x12(.fintech.webhook.v1.DeleteWebhookRequest\x1a).fintech.webhook.v1.DeleteWebhookResponse\x12Y\n" +
	"\x04List\x12'.fintech.webhook.v1.ListWebhooksRequest\x1a(.fintech.webhook.v1.ListWebhooksResponse\x12W\n" +
	"\x04Test\x12&.fintech.webhook.v1.TestWebhookRequest\x1a'.fintech.webhook.v1.TestWebhookResponse\x12h\n" +
	"\x0fWebhookDebugger\x12'.fintech.webhook.v1.WebhookDebugCommand\x1a(.fintech.webhook.v1.WebhookDebugResponse(\x010\x01B!Z\x1ffintech-api/proto/gen/protob\x06proto3"

var (
	file_webhook_proto_rawDescOnce sync.Once
	file_webhook_proto_rawDescData []byte
)

func file_webhook_proto_rawDescGZIP() []byte {
	file_webhook_proto_rawDescOnce.Do(func() {
		file_webhook_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_proto_rawDesc), len(file_webhook_proto_rawDesc)))
	})
	return file_webhook_proto_rawDescData
}

var file_webhook_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_webhook_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_webhook_proto_goTypes = []any{
	(WebhookEventType)(0),           // 0: fintech.webhook.v1.WebhookEventType
	(WebhookStatus)(0),              // 1: fintech.webhook.v1.WebhookStatus
	(*Webhook)(nil),                 // 2: fintech.webhook.v1.Webhook
	(*WebhookDelivery)(nil),         // 3: fintech.webhook.v1.WebhookDelivery
	(*RegisterWebhookRequest)(nil),  // 4: fintech.webhook.v1.RegisterWebhookRequest
	(*RegisterWebhookResponse)(nil), // 5: fintech.webhook.v1.RegisterWebhookResponse
	(*DeleteWebhookRequest)(nil),    // 6: fintech.webhook.v1.DeleteWebhookRequest
	(*DeleteWebhookResponse)(nil),   // 7: fintech.webhook.v1.DeleteWebhookResponse
	(*ListWebhooksRequest)(nil),     // 8: fintech.webhook.v1.ListWebhooksRequest
	(*ListWebhooksResponse)(nil),    // 9: fintech.webhook.v1.ListWebhooksResponse
	(*TestWebhookRequest)(nil),      // 10: fintech.webhook.v1.TestWebhookRequest
	(*TestWebhookResponse)(nil),     // 11: fintech.webhook.v1.TestWebhookResponse
	(*WebhookDebugCommand)(nil),     // 12: fintech.webhook.v1.WebhookDebugCommand
	(*StartDebugging)(nil),          // 13: fintech.webhook.v1.StartDebugging
	(*StopDebugging)(nil),           // 14: fintech.webhook.v1.StopDebugging
	(*TestEndpoint)(nil),            // 15: fintech.webhook.v1.TestEndpoint
	(*UpdateConfig)(nil),            // 16: fintech.webhook.v1.UpdateConfig
	(*RetryDelivery)(nil),           // 17: fintech.webhook.v1.RetryDelivery
	(*WebhookDebugResponse)(nil),    // 18: fintech.webhook.v1.WebhookDebugResponse
	(*DeliveryAttempt)(nil),         // 19: fintech.webhook.v1.DeliveryAttempt
	(*DebugStats)(nil),              // 20: fintech.webhook.v1.DebugStats
	(*DebugLog)(nil),                // 21: fintech.webhook.v1.DebugLog
	(*DebugStatus)(nil),             // 22: fintech.webhook.v1.DebugStatus
	nil,                             // 23: fintech.webhook.v1.Webhook.HeadersEntry
	nil,                             // 24: fintech.webhook.v1.RegisterWebhookRequest.HeadersEntry
	nil,                             // 25: fintech.webhook.v1.TestEndpoint.CustomHeadersEntry
	nil,                             // 26: fintech.webhook.v1.UpdateConfig.NewHeadersEntry
	nil,                             // 27: fintech.webhook.v1.DeliveryAttempt.RequestHeadersEntry
	nil,                             // 28: fintech.webhook.v1.DeliveryAttempt.ResponseHeadersEntry
	nil,                             // 29: fintech.webhook.v1.DebugStats.StatusCodeBreakdownEntry
	nil,                             // 30: fintech.webhook.v1.DebugLog.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 31: google.protobuf.Timestamp
}
var file_webhook_proto_depIdxs = []int32{
	0,  // 0: fintech.webhook.v1.Webhook.events:type_name -> fintech.webhook.v1.WebhookEventType
	1,  // 1: fintech.webhook.v1.Webhook.status:type_name -> fintech.webhook.v1.WebhookStatus
	23, // 2: fintech.webhook.v1.Webhook.headers:type_name -> fintech.webhook.v1.Webhook.HeadersEntry
	31, // 3: fintech.webhook.v1.Webhook.created_at:type_name -> google.protobuf.Timestamp
	31, // 4: fintech.webhook.v1.Webhook.updated_at:type_name -> google.protobuf.Timestamp
	31, // 5: fintech.webhook.v1.Webhook.last_triggered:type_name -> google.protobuf.Timestamp
	0,  // 6: fintech.webhook.v1.WebhookDelivery.event_type:type_name -> fintech.webhook.v1.WebhookEventType
	31, // 7: fintech.webhook.v1.WebhookDelivery.attempted_at:type_name -> google.protobuf.Timestamp
	0,  // 8: fintech.webhook.v1.RegisterWebhookRequest.events:type_name -> fintech.webhook.v1.WebhookEventType
	24, // 9: fintech.webhook.v1.RegisterWebhookRequest.headers:type_name -> fintech.webhook.v1.RegisterWebhookRequest.HeadersEntry
	2,  // 10: fintech.webhook.v1.RegisterWebhookResponse.webhook:type_name -> fintech.webhook.v1.Webhook
	1,  // 11: fintech.webhook.v1.ListWebhooksRequest.status_filter:type_name -> fintech.webhook.v1.WebhookStatus
	2,  // 12: fintech.webhook.v1.ListWebhooksResponse.webhooks:type_name -> fintech.webhook.v1.Webhook
	0,  // 13: fintech.webhook.v1.TestWebhookRequest.event_type:type_name -> fintech.webhook.v1.WebhookEventType
	3,  // 14: fintech.webhook.v1.TestWebhookResponse.delivery:type_name -> fintech.webhook.v1.WebhookDelivery
	13, // 15: fintech.webhook.v1.WebhookDebugCommand.start_debugging:type_name -> fintech.webhook.v1.StartDebugging
	14, // 16: fintech.webhook.v1.WebhookDebugCommand.stop_debugging:type_name -> fintech.webhook.v1.StopDebugging
	15, // 17: fintech.webhook.v1.WebhookDebugCommand.test_endpoint:type_name -> fintech.webhook.v1.TestEndpoint
	16, // 18: fintech.webhook.v1.WebhookDebugCommand.update_config:type_name -> fintech.webhook.v1.UpdateConfig
	17, // 19: fintech.webhook.v1.WebhookDebugCommand.retry_delivery:type_name -> fintech.webhook.v1.RetryDelivery
	0,  // 20: fintech.webhook.v1.TestEndpoint.event_type:type_name -> fintech.webhook.v1.WebhookEventType
	25, // 21: fintech.webhook.v1.TestEndpoint.custom_headers:type_name -> fintech.webhook.v1.TestEndpoint.CustomHeadersEntry
	26, // 22: fintech.webhook.v1.UpdateConfig.new_headers:type_name -> fintech.webhook.v1.UpdateConfig.NewHeadersEntry
	19, // 23: fintech.webhook.v1.WebhookDebugResponse.delivery_attempt:type_name -> fintech.webhook.v1.DeliveryAttempt
	20, // 24: fintech.webhook.v1.WebhookDebugResponse.debug_stats:type_name -> fintech.webhook.v1.DebugStats
	21, // 25: fintech.webhook.v1.WebhookDebugResponse.debug_log:type_name -> fintech.webhook.v1.DebugLog
	22, // 26: fintech.webhook.v1.WebhookDebugResponse.debug_status:type_name -> fintech.webhook.v1.DebugStatus
	27, // 27: fintech.webhook.v1.DeliveryAttempt.request_headers:type_name -> fintech.webhook.v1.DeliveryAttempt.RequestHeadersEntry
	28, // 28: fintech.webhook.v1.DeliveryAttempt.response_headers:type_name -> fintech.webhook.v1.DeliveryAttempt.ResponseHeadersEntry
	31, // 29: fintech.webhook.v1.DeliveryAttempt.attempted_at:type_name -> google.protobuf.Timestamp
	29, // 30: fintech.webhook.v1.DebugStats.status_code_breakdown:type_name -> fintech.webhook.v1.DebugStats.StatusCodeBreakdownEntry
	31, // 31: fintech.webhook.v1.DebugStats.period_start:type_name -> google.protobuf.Timestamp
	31, // 32: fintech.webhook.v1.DebugStats.period_end:type_name -> google.protobuf.Timestamp
	30, // 33: fintech.webhook.v1.DebugLog.metadata:type_name -> fintech.webhook.v1.DebugLog.MetadataEntry
	31, // 34: fintech.webhook.v1.DebugLog.timestamp:type_name -> google.protobuf.Timestamp
	31, // 35: fintech.webhook.v1.DebugStatus.started_at:type_name -> google.protobuf.Timestamp
	4,  // 36: fintech.webhook.v1.WebhookService.Register:input_type -> fintech.webhook.v1.RegisterWebhookRequest
	6,  // 37: fintech.webhook.v1.WebhookService.Delete:input_type -> fintech.webhook.v1.DeleteWebhookRequest
	8,  // 38: fintech.webhook.v1.WebhookService.List:input_type -> fintech.webhook.v1.ListWebhooksRequest
	10, // 39: fintech.webhook.v1.WebhookService.Test:input_type -> fintech.webhook.v1.TestWebhookRequest
	12, // 40: fintech.webhook.v1.WebhookService.WebhookDebugger:input_type -> fintech.webhook.v1.WebhookDebugCommand
	5,  // 41: fintech.webhook.v1.WebhookService.Register:output_type -> fintech.webhook.v1.RegisterWebhookResponse
	7,  // 42: fintech.webhook.v1.WebhookService.Delete:output_type -> fintech.webhook.v1.DeleteWebhookResponse
	9,  // 43: fintech.webhook.v1.WebhookService.List:output_type -> fintech.webhook.v1.ListWebhooksResponse
	11, // 44: fintech.webhook.v1.WebhookService.Test:output_type -> fintech.webhook.v1.TestWebhookResponse
	18, // 45: fintech.webhook.v1.WebhookService.WebhookDebugger:output_type -> fintech.webhook.v1.WebhookDebugResponse
	41, // [41:46] is the sub-list for method output_type
	36, // [36:41] is the sub-list for method input_type
	36, // [36:36] is the sub-list for extension type_name
	36, // [36:36] is the sub-list for extension extendee
	0,  // [0:36] is the sub-list for field type_name
}

func init() { file_webhook_proto_init() }
func file_webhook_proto_init() {
	if File_webhook_proto != nil {
		return
	}
	file_webhook_proto_msgTypes[10].OneofWrappers = []any{
		(*WebhookDebugCommand_StartDebugging)(nil),
		(*WebhookDebugCommand_StopDebugging)(nil),
		(*WebhookDebugCommand_TestEndpoint)(nil),
		(*WebhookDebugCommand_UpdateConfig)(nil),
		(*WebhookDebugCommand_RetryDelivery)(nil),
	}
	file_webhook_proto_msgTypes[16].OneofWrappers = []any{
		(*WebhookDebugResponse_DeliveryAttempt)(nil),
		(*WebhookDebugResponse_DebugStats)(nil),
		(*WebhookDebugResponse_DebugLog)(nil),
		(*WebhookDebugResponse_DebugStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_proto_rawDesc), len(file_webhook_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_webhook_proto_goTypes,
		DependencyIndexes: file_webhook_proto_depIdxs,
		EnumInfos:         file_webhook_proto_enumTypes,
		MessageInfos:      file_webhook_proto_msgTypes,
	}.Build()
	File_webhook_proto = out.File
	file_webhook_proto_goTypes = nil
	file_webhook_proto_depIdxs = nil
}
